RigidChips: CD3DMesh Class Reference
CD3DMesh Class Reference
#include <d3dfile.h>
Public Member Functions
HRESULT Render (LPDIRECT3DDEVICE8 pd3dDevice, BOOL bDrawOpaqueSubsets=TRUE, BOOL bDrawAlphaSubsets=TRUE)
LPD3DXMESH GetSysMemMesh ()
LPD3DXMESH GetLocalMesh ()
VOID UseMeshMaterials (BOOL bFlag)
HRESULT SetFVF (LPDIRECT3DDEVICE8 pd3dDevice, DWORD dwFVF)
HRESULT RestoreDeviceObjects (LPDIRECT3DDEVICE8 pd3dDevice)
HRESULT InvalidateDeviceObjects ()
HRESULT Create (LPDIRECT3DDEVICE8 pd3dDevice, TCHAR *strFilename)
HRESULT Create (LPDIRECT3DDEVICE8 pd3dDevice, LPDIRECTXFILEDATA pFileData)
HRESULT Destroy ()
CD3DMesh (TCHAR *strName=_T("CD3DFile_Mesh"))
virtual ~CD3DMesh ()
Public Attributes
TCHAR m_strName [512]
LPD3DXMESH m_pSysMemMesh
LPD3DXMESH m_pLocalMesh
DWORD m_dwNumMaterials
D3DMATERIAL8 * m_pMaterials
LPDIRECT3DTEXTURE8 * m_pTextures
BOOL m_bUseMaterials
Constructor & Destructor Documentation
CD3DMesh::CD3DMesh (TCHAR * strName = _T("CD3DFile_Mesh"))
CD3DMesh::~CD3DMesh () virtual
Member Function Documentation
HRESULT CD3DMesh::Create (LPDIRECT3DDEVICE8 pd3dDevice, TCHAR * strFilename)
Referenced by CMyD3DApplication::InitDeviceObjects(), LoadLand(), and CD3DFile::LoadMesh().
HRESULT CD3DMesh::Create (LPDIRECT3DDEVICE8 pd3dDevice, LPDIRECTXFILEDATA pFileData)
HRESULT CD3DMesh::Destroy ()
Referenced by CMyD3DApplication::DeleteDeviceObjects(), CD3DFrame::Destroy(), LoadLand(), and ~CD3DMesh().
LPD3DXMESH CD3DMesh::GetLocalMesh () inline
LPD3DXMESH CD3DMesh::GetSysMemMesh () inline
Referenced by CMyD3DApplication::FrameMove(), LoadLand(), and luaGetH().
HRESULT CD3DMesh::InvalidateDeviceObjects ()
Referenced by Destroy(), CD3DFrame::InvalidateDeviceObjects(), and CMyD3DApplication::InvalidateDeviceObjects().
HRESULT CD3DMesh::Render (LPDIRECT3DDEVICE8 pd3dDevice, BOOL bDrawOpaqueSubsets = TRUE, BOOL bDrawAlphaSubsets = TRUE)
Referenced by GRigid::Disp(), GRigid::DispJet(), GWorld::DispNetChip(), GWorld::DispNetChipInfo(), GWorld::DispNetJet(), GRigid::DispObject(), CD3DFrame::Render(), CMyD3DApplication::Render(), and CMyD3DApplication::RenderSky().
HRESULT CD3DMesh::RestoreDeviceObjects (LPDIRECT3DDEVICE8 pd3dDevice)
Referenced by CD3DFrame::RestoreDeviceObjects(), and CMyD3DApplication::RestoreDeviceObjects().
HRESULT CD3DMesh::SetFVF (LPDIRECT3DDEVICE8 pd3dDevice, DWORD dwFVF)
VOID CD3DMesh::UseMeshMaterials (BOOL bFlag) inline
Member Data Documentation
BOOL CD3DMesh::m_bUseMaterials
Referenced by CD3DMesh(), and Render().
DWORD CD3DMesh::m_dwNumMaterials
Referenced by CD3DMesh(), Create(), Destroy(), LoadLand(), Render(), and CMyD3DApplication::RenderSky().
LPD3DXMESH CD3DMesh::m_pLocalMesh
Referenced by CD3DMesh(), GetLocalMesh(), InvalidateDeviceObjects(), Render(), RestoreDeviceObjects(), and SetFVF().
D3DMATERIAL8* CD3DMesh::m_pMaterials
Referenced by CD3DMesh(), Create(), Destroy(), GRigid::Disp(), GWorld::DispNetChip(), GWorld::DispNetChipInfo(), GRigid::DispObject(), LoadLand(), Render(), CMyD3DApplication::Render(), and CMyD3DApplication::RenderSky().
LPD3DXMESH CD3DMesh::m_pSysMemMesh
Referenced by CD3DMesh(), Create(), Destroy(), GetSysMemMesh(), RestoreDeviceObjects(), and SetFVF().
LPDIRECT3DTEXTURE8* CD3DMesh::m_pTextures
Referenced by CD3DMesh(), Create(), Destroy(), and Render().
TCHAR CD3DMesh::m_strName[512]
Referenced by CD3DMesh(), and CD3DFrame::FindMesh().
The documentation for this class was generated from the following files:
d3dfile.h
d3dfile.cpp