RigidChips: GSocket Class Reference
GSocket Class Reference
#include <GSocket.hpp>
Public Member Functions
GSocket ()
virtual ~GSocket ()
int Send (const char *buf, int len, int flags)
int Recv (char *buf, int len, int flags)
Protected Member Functions
int Init ()
int Term ()
int Bind (u_short family, char *data, int namelen)
int Listen (int backlog=3)
int Accept (u_short *family, char *data, int *addrlen)
int Connect (u_short family, char *data, int namelen)
int Open (int af, int type, int protocol)
int Close ()
int Shutdown (int how)
Private Attributes
WSADATA m_wsadata
SOCKET m_socket
SOCKET m_socket_client
Constructor & Destructor Documentation
GSocket::GSocket ()
GSocket::~GSocket () virtual
Member Function Documentation
int GSocket::Accept (u_short * family, char * data, int * addrlen) protected
int GSocket::Bind (u_short family, char * data, int namelen) protected
int GSocket::Close () protected
Referenced by HttpSocket::Term().
int GSocket::Connect (u_short family, char * data, int namelen) protected
Referenced by HttpSocket::Connect().
int GSocket::Init () protected
Referenced by HttpSocket::Init().
int GSocket::Listen (int backlog = 3) protected
int GSocket::Open (int af, int type, int protocol) protected
int GSocket::Recv (char * buf, int len, int flags)
int GSocket::Send (const char * buf, int len, int flags)
int GSocket::Shutdown (int how) protected
Referenced by HttpSocket::Shutdown().
int GSocket::Term () protected
Referenced by HttpSocket::Term().
Member Data Documentation
SOCKET GSocket::m_socket private
SOCKET GSocket::m_socket_client private
WSADATA GSocket::m_wsadata private
The documentation for this class was generated from the following files:
GSocket.hpp
GSocket.cpp