RigidChips: GMatrix33 Class Reference
GMatrix33 Class Reference
#include <GVector.hpp>
Public Member Functions
GMatrix33 (bool flag=true)
GMatrix33 (GFloat f[3][3])
GMatrix33 (const GMatrix)
GMatrix33 (const GVector &u, const GVector &v, const GVector &w)
void get (double a[3][3])
void get (float a[3][3])
void put (double a[3][3])
void put (float a[3][3])
bool operator== (const GMatrix33 &) const
bool operator!= (const GMatrix33 &) const
GMatrix33 operator+ (const GMatrix33 &) const
GMatrix33 operator- (const GMatrix33 &) const
GMatrix33 operator* (const GMatrix33 &m) const
GVector operator* (const GVector &v) const
GMatrix33 operator* (const GFloat &) const
GMatrix33 inverse (void) const
void inverse (GMatrix33 &im) const
GMatrix33 transpose (void) const
GMatrix33 & operator= (const GMatrix33 &)
GMatrix33 & operator= (const GMatrix &)
GMatrix33 & operator+= (const GMatrix33 &)
GMatrix33 & operator-= (const GMatrix33 &)
GMatrix33 & operator*= (const GMatrix33 &)
GMatrix33 & operator*= (const GFloat &)
GMatrix33 scale (const GFloat &) const
GMatrix33 scale (const GVector &) const
GMatrix33 rotateX (const GFloat) const
GMatrix33 rotateY (const GFloat) const
GMatrix33 rotateZ (const GFloat) const
GMatrix33 rotate (const GVector &) const
GMatrix33 rotate (const GVector &axis, GFloat angle) const
void getEular (GFloat &yaw, GFloat &pitch, GFloat &roll)
GQuat quat (void)
void unity (void)
bool isUnity (void) const
Public Attributes
GFloat elem [3][3]
Friends
GVector operator* (GVector v, GMatrix33 m)
Constructor & Destructor Documentation
GMatrix33::GMatrix33 (bool flag = true) inline
GMatrix33::GMatrix33 (GFloat f[3][3]) inline
GMatrix33::GMatrix33 (const GMatrix m)
GMatrix33::GMatrix33 (const GVector & u, const GVector & v, const GVector & w) inline
Member Function Documentation
void GMatrix33::get (double a[3][3]) inline
void GMatrix33::get (float a[3][3]) inline
void GMatrix33::getEular (GFloat & yaw, GFloat & pitch, GFloat & roll)
GMatrix33 GMatrix33::inverse (void) const
Referenced by GWorld::AddObject(), GWorld::AddRigid(), GRigid::Reset(), GRigid::RSet(), GRigid::SetTensor(), and GWorld::UpdateRigid().
void GMatrix33::inverse (GMatrix33 & im) const
bool GMatrix33::isUnity (void) const
bool GMatrix33::operator!= (const GMatrix33 & m) const
GMatrix33 GMatrix33::operator* (const GMatrix33 & m) const inline
GVector GMatrix33::operator* (const GVector & v) const inline
GMatrix33 GMatrix33::operator* (const GFloat & f) const
GMatrix33 & GMatrix33::operator*= (const GMatrix33 & m)
GMatrix33 & GMatrix33::operator*= (const GFloat & f)
GMatrix33 GMatrix33::operator+ (const GMatrix33 & m) const
GMatrix33 & GMatrix33::operator+= (const GMatrix33 & m)
GMatrix33 GMatrix33::operator- (const GMatrix33 & m) const
GMatrix33 & GMatrix33::operator-= (const GMatrix33 & m)
GMatrix33 & GMatrix33::operator= (const GMatrix33 & m)
GMatrix33 & GMatrix33::operator= (const GMatrix & m)
bool GMatrix33::operator== (const GMatrix33 & m) const
void GMatrix33::put (double a[3][3]) inline
void GMatrix33::put (float a[3][3]) inline
GQuat GMatrix33::quat (void)
GMatrix33 GMatrix33::rotate (const GVector & v) const
Referenced by GWorld::CalcHinge(), and GWorld::RestoreLink().
GMatrix33 GMatrix33::rotate (const GVector & axis, GFloat angle) const
GMatrix33 GMatrix33::rotateX (const GFloat angle) const
Referenced by GWorld::AddObject(), GWorld::AddRigid(), and GWorld::UpdateRigid().
GMatrix33 GMatrix33::rotateY (const GFloat angle) const
Referenced by GWorld::AddObject(), GWorld::AddRigid(), and GWorld::UpdateRigid().
GMatrix33 GMatrix33::rotateZ (const GFloat angle) const
Referenced by GWorld::AddObject(), GWorld::AddRigid(), and GWorld::UpdateRigid().
GMatrix33 GMatrix33::scale (const GFloat & f) const
GMatrix33 GMatrix33::scale (const GVector & v) const
GMatrix33 GMatrix33::transpose (void) const
Referenced by GQuat::matrix33(), rotate(), rotateX(), rotateY(), and rotateZ().
void GMatrix33::unity (void)
Friends And Related Function Documentation
GVector operator* (GVector v, GMatrix33 m) friend
Member Data Documentation
GFloat GMatrix33::elem[3][3]
Referenced by GRigid::CalcMassMat(), getEular(), getObjI(), GMatrix::GMatrix(), GMatrix33(), inverse(), isUnity(), luaGetObjI(), GQuat::matrix33(), operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), GMatrix::operator=(), operator=(), operator==(), quat(), rotate(), rotateX(), rotateY(), rotateZ(), scale(), GRigid::SetTensor(), transpose(), and unity().
The documentation for this class was generated from the following files:
GVector.hpp
GVector.cpp