RigidChips: IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS > Class Template Reference
IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS > Class Template Reference
#include <dmoimpl.h>
Classes
class LockIt
Protected Member Functions
bool InputTypeSet (DWORD ulInputStreamIndex) const
bool OutputTypeSet (DWORD ulOutputStreamIndex) const
const DMO_MEDIA_TYPE * InputType (DWORD ulInputStreamIndex)
const DMO_MEDIA_TYPE * OutputType (DWORD ulOutputStreamIndex)
bool CheckTypesSet ()
IMediaObjectImpl ()
virtual ~IMediaObjectImpl ()
STDMETHODIMP GetStreamCount (unsigned long *pulNumberOfInputStreams, unsigned long *pulNumberOfOutputStreams)
STDMETHODIMP GetInputStreamInfo (ULONG ulStreamIndex, DWORD *pdwFlags)
STDMETHODIMP GetOutputStreamInfo (ULONG ulStreamIndex, DWORD *pdwFlags)
STDMETHODIMP GetInputType (ULONG ulStreamIndex, ULONG ulTypeIndex, DMO_MEDIA_TYPE *pmt)
STDMETHODIMP GetOutputType (ULONG ulStreamIndex, ULONG ulTypeIndex, DMO_MEDIA_TYPE *pmt)
STDMETHODIMP GetInputCurrentType (ULONG ulStreamIndex, DMO_MEDIA_TYPE *pmt)
STDMETHODIMP GetOutputCurrentType (ULONG ulStreamIndex, DMO_MEDIA_TYPE *pmt)
STDMETHODIMP GetInputSizeInfo (ULONG ulStreamIndex, ULONG *pulSize, ULONG *pcbMaxLookahead, ULONG *pulAlignment)
STDMETHODIMP GetOutputSizeInfo (ULONG ulStreamIndex, ULONG *pulSize, ULONG *pulAlignment)
STDMETHODIMP SetInputType (ULONG ulStreamIndex, const DMO_MEDIA_TYPE *pmt, DWORD dwFlags)
STDMETHODIMP SetOutputType (ULONG ulStreamIndex, const DMO_MEDIA_TYPE *pmt, DWORD dwFlags)
STDMETHODIMP GetInputStatus (ULONG ulStreamIndex, DWORD *pdwStatus)
STDMETHODIMP GetInputMaxLatency (unsigned long ulStreamIndex, REFERENCE_TIME *prtLatency)
STDMETHODIMP SetInputMaxLatency (unsigned long ulStreamIndex, REFERENCE_TIME rtLatency)
STDMETHODIMP Discontinuity (ULONG ulStreamIndex)
STDMETHODIMP Flush ()
STDMETHODIMP AllocateStreamingResources ()
STDMETHODIMP FreeStreamingResources ()
STDMETHODIMP ProcessInput (DWORD ulStreamIndex, IMediaBuffer *pBuffer, DWORD dwFlags, REFERENCE_TIME rtTimestamp, REFERENCE_TIME rtTimelength)
STDMETHODIMP ProcessOutput (DWORD dwFlags, DWORD ulOutputBufferCount, DMO_OUTPUT_DATA_BUFFER *pOutputBuffers, DWORD *pdwStatus)
STDMETHODIMP DMOLock (LONG lLock)
Private Attributes
struct {
DWORD fTypeSet:1
DWORD fIncomplete:1
DMO_MEDIA_TYPE CurrentMediaType
} m_InputInfo [NUMBEROFINPUTS]
struct {
DWORD fTypeSet:1
DWORD fIncomplete:1
DMO_MEDIA_TYPE CurrentMediaType
} m_OutputInfo [NUMBEROFOUTPUTS]
bool m_fTypesSet
bool m_fFlushed
bool m_fResourcesAllocated
Additional Inherited Members
Public Member Functions inherited from IMediaObject
HRESULT GetStreamCount ([out] DWORD *pcInputStreams, [out] DWORD *pcOutputStreams)
HRESULT GetInputStreamInfo (DWORD dwInputStreamIndex, [out] DWORD *pdwFlags)
HRESULT GetOutputStreamInfo (DWORD dwOutputStreamIndex, [out] DWORD *pdwFlags)
HRESULT GetInputType (DWORD dwInputStreamIndex, DWORD dwTypeIndex, [out] DMO_MEDIA_TYPE *pmt)
HRESULT GetOutputType (DWORD dwOutputStreamIndex, DWORD dwTypeIndex, [out] DMO_MEDIA_TYPE *pmt)
HRESULT SetInputType (DWORD dwInputStreamIndex, [in] const DMO_MEDIA_TYPE *pmt, DWORD dwFlags)
HRESULT SetOutputType (DWORD dwOutputStreamIndex, [in] const DMO_MEDIA_TYPE *pmt, DWORD dwFlags)
HRESULT GetInputCurrentType (DWORD dwInputStreamIndex, [out] DMO_MEDIA_TYPE *pmt)
HRESULT GetOutputCurrentType (DWORD dwOutputStreamIndex, [out] DMO_MEDIA_TYPE *pmt)
HRESULT GetInputSizeInfo (DWORD dwInputStreamIndex, [out] DWORD *pcbSize, [out] DWORD *pcbMaxLookahead, [out] DWORD *pcbAlignment)
HRESULT GetOutputSizeInfo (DWORD dwOutputStreamIndex, [out] DWORD *pcbSize, [out] DWORD *pcbAlignment)
HRESULT GetInputMaxLatency (DWORD dwInputStreamIndex, [out] REFERENCE_TIME *prtMaxLatency)
HRESULT SetInputMaxLatency (DWORD dwInputStreamIndex, REFERENCE_TIME rtMaxLatency)
HRESULT Discontinuity (DWORD dwInputStreamIndex)
HRESULT GetInputStatus (DWORD dwInputStreamIndex, [out] DWORD *dwFlags)
HRESULT Lock (LONG bLock)
Constructor & Destructor Documentation
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::IMediaObjectImpl () inline protected
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> virtual IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::~IMediaObjectImpl () inline protected virtual
Member Function Documentation
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> STDMETHODIMP IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::AllocateStreamingResources () inline protected
Implements IMediaObject.
Referenced by IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::ProcessInput(), and IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::ProcessOutput().
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> bool IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::CheckTypesSet () inline protected
Referenced by IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::SetInputType(), and IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::SetOutputType().
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> STDMETHODIMP IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::Discontinuity (ULONG ulStreamIndex) inline protected
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> STDMETHODIMP IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::DMOLock (LONG lLock) inline protected
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> STDMETHODIMP IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::Flush () inline protected
Implements IMediaObject.
Referenced by IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::FreeStreamingResources(), IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::SetInputType(), and IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::SetOutputType().
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> STDMETHODIMP IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::FreeStreamingResources () inline protected
Implements IMediaObject.
Referenced by IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::SetInputType(), and IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::SetOutputType().
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> STDMETHODIMP IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::GetInputCurrentType (ULONG ulStreamIndex, DMO_MEDIA_TYPE * pmt) inline protected
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> STDMETHODIMP IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::GetInputMaxLatency (unsigned long ulStreamIndex, REFERENCE_TIME * prtLatency) inline protected
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> STDMETHODIMP IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::GetInputSizeInfo (ULONG ulStreamIndex, ULONG * pulSize, ULONG * pcbMaxLookahead, ULONG * pulAlignment) inline protected
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> STDMETHODIMP IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::GetInputStatus (ULONG ulStreamIndex, DWORD * pdwStatus) inline protected
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> STDMETHODIMP IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::GetInputStreamInfo (ULONG ulStreamIndex, DWORD * pdwFlags) inline protected
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> STDMETHODIMP IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::GetInputType (ULONG ulStreamIndex, ULONG ulTypeIndex, DMO_MEDIA_TYPE * pmt) inline protected
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> STDMETHODIMP IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::GetOutputCurrentType (ULONG ulStreamIndex, DMO_MEDIA_TYPE * pmt) inline protected
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> STDMETHODIMP IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::GetOutputSizeInfo (ULONG ulStreamIndex, ULONG * pulSize, ULONG * pulAlignment) inline protected
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> STDMETHODIMP IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::GetOutputStreamInfo (ULONG ulStreamIndex, DWORD * pdwFlags) inline protected
Referenced by IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::CheckTypesSet().
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> STDMETHODIMP IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::GetOutputType (ULONG ulStreamIndex, ULONG ulTypeIndex, DMO_MEDIA_TYPE * pmt) inline protected
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> STDMETHODIMP IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::GetStreamCount (unsigned long * pulNumberOfInputStreams, unsigned long * pulNumberOfOutputStreams) inline protected
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> const DMO_MEDIA_TYPE* IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::InputType (DWORD ulInputStreamIndex) inline protected
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> bool IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::InputTypeSet (DWORD ulInputStreamIndex) const inline protected
Referenced by IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::CheckTypesSet(), IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::GetInputCurrentType(), IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::GetInputSizeInfo(), IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::InputType(), IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::SetInputType(), and IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::~IMediaObjectImpl().
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> const DMO_MEDIA_TYPE* IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::OutputType (DWORD ulOutputStreamIndex) inline protected
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> bool IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::OutputTypeSet (DWORD ulOutputStreamIndex) const inline protected
Referenced by IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::CheckTypesSet(), IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::GetOutputCurrentType(), IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::GetOutputSizeInfo(), IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::OutputType(), IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::SetOutputType(), and IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::~IMediaObjectImpl().
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> STDMETHODIMP IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::ProcessInput (DWORD ulStreamIndex, IMediaBuffer * pBuffer, DWORD dwFlags, REFERENCE_TIME rtTimestamp, REFERENCE_TIME rtTimelength) inline protected
Implements IMediaObject.
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> STDMETHODIMP IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::ProcessOutput (DWORD dwFlags, DWORD ulOutputBufferCount, DMO_OUTPUT_DATA_BUFFER * pOutputBuffers, DWORD * pdwStatus) inline protected
Implements IMediaObject.
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> STDMETHODIMP IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::SetInputMaxLatency (unsigned long ulStreamIndex, REFERENCE_TIME rtLatency) inline protected
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> STDMETHODIMP IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::SetInputType (ULONG ulStreamIndex, const DMO_MEDIA_TYPE * pmt, DWORD dwFlags) inline protected
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> STDMETHODIMP IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::SetOutputType (ULONG ulStreamIndex, const DMO_MEDIA_TYPE * pmt, DWORD dwFlags) inline protected
Member Data Documentation
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> DMO_MEDIA_TYPE IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::CurrentMediaType
Referenced by IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::GetInputCurrentType(), IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::GetOutputCurrentType(), IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::SetInputType(), IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::SetOutputType(), and IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::~IMediaObjectImpl().
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> DWORD IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::fIncomplete
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> DWORD IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::fTypeSet
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> bool IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::m_fFlushed private
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> bool IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::m_fResourcesAllocated private
template<class _DERIVED_ , int NUMBEROFINPUTS, int NUMBEROFOUTPUTS> bool IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::m_fTypesSet private
struct { ... } IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::m_InputInfo[NUMBEROFINPUTS]
Referenced by IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::GetInputCurrentType(), IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::IMediaObjectImpl(), IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::InputType(), IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::InputTypeSet(), IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::SetInputType(), and IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::~IMediaObjectImpl().
struct { ... } IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::m_OutputInfo[NUMBEROFOUTPUTS]
The documentation for this class was generated from the following file:
microsoft directx 9.0 sdk (summer 2004)/Include/dmoimpl.h