RigidChips: GDPlay Class Reference
GDPlay Class Reference
#include <GDPlay.hpp>
Public Member Functions
GDPlay ()
~GDPlay ()
IDirectPlay8LobbiedApplication * GetLobbyApp ()
void SetReceiveFunc (ReceiveFunc func)
void SetCreateFunc (CreateFunc func)
void SetDestroyFunc (DestroyFunc func)
void SetTerminateFunc (TerminateFunc func)
BOOL GetConnect ()
void SetConnect (BOOL f)
DPNID GetLocalPlayerDPNID ()
DPNID GetHostPlayerDPNID ()
HRESULT GetSessionName (char *strSessionName)
DWORD GetCurrentPlayers ()
HRESULT GetHostName (char *strHostName, char *strProvider)
HRESULT Init (HINSTANCE hInst)
void NewSession (char *sessionName, char *username, int tcpPort, GUID appGuid)
void ConnectSession (char *hostname, char *username, int tcpPort, GUID appGuid)
void CancelConnect ()
bool GetCancelConnect ()
HRESULT SendAll (BYTE *data, DWORD size)
HRESULT SendTo (DPNID dpnid, BYTE *data, DWORD size)
int GetNumPlayers ()
int GetMaxPlayers ()
DWORD GetPlayersDPID (DPNID *dpnid)
HRESULT GetPlayersName (DPNID dpnid, char *name)
void Close ()
void End ()
Static Public Member Functions
static HRESULT CALLBACK myMessageHandler (PVOID pvUserContext, DWORD dwMessageType, PVOID pMessage)
Private Attributes
HINSTANCE m_hInst
CRITICAL_SECTION m_csPlayerContext
IDirectPlay8Peer * m_pDP
LONG m_MaxPlayers
LONG m_NumberOfActivePlayers
ReceiveFunc m_ReceiveFunc
CreateFunc m_CreateFunc
DestroyFunc m_DestroyFunc
TerminateFunc m_TerminateFunc
DPNID m_dpnidLocalPlayer
DPNID m_dpnidHostPlayer
IDirectPlay8LobbiedApplication * m_pLobbyApp
DPNHANDLE m_hHostAsyncOp
DPNHANDLE m_hConnectAsyncOp
BOOL m_Connect
Constructor & Destructor Documentation
GDPlay::GDPlay () inline
GDPlay::~GDPlay () inline
Member Function Documentation
void GDPlay::CancelConnect () inline
Referenced by DlgNetworkProc().
void GDPlay::Close () inline
Referenced by DlgNetworkProc().
void GDPlay::ConnectSession (char * hostname, char * username, int tcpPort, GUID appGuid) inline
Referenced by DlgNetworkProc().
void GDPlay::End () inline
Referenced by CMyD3DApplication::FinalCleanup(), and ~GDPlay().
bool GDPlay::GetCancelConnect () inline
Referenced by DlgNetworkProc().
BOOL GDPlay::GetConnect () inline
Referenced by DlgNetworkProc().
DWORD GDPlay::GetCurrentPlayers () inline
Referenced by CMyD3DApplication::Render().
HRESULT GDPlay::GetHostName (char * strHostName, char * strProvider) inline
Referenced by DlgNetworkProc().
DPNID GDPlay::GetHostPlayerDPNID () inline
Referenced by DlgNetworkProc(), CMyD3DApplication::FrameMove(), getPlayerHostID(), luaGetPlayerHostID(), and PlayersInfoDisp().
IDirectPlay8LobbiedApplication* GDPlay::GetLobbyApp () inline
DPNID GDPlay::GetLocalPlayerDPNID () inline
Referenced by DlgNetworkProc(), CMyD3DApplication::FrameMove(), getPlayerArms(), getPlayerChips(), getPlayerCrushes(), getPlayerInits(), getPlayerMyID(), getPlayerResets(), getPlayerX(), getPlayerY(), getPlayerYForces(), getPlayerZ(), luaGetPlayerArms(), luaGetPlayerChips(), luaGetPlayerCrushes(), luaGetPlayerInits(), luaGetPlayerMyID(), luaGetPlayerResets(), luaGetPlayerX(), luaGetPlayerY(), luaGetPlayerYForces(), luaGetPlayerZ(), MyReceiveFunc(), and PlayersInfoDisp().
int GDPlay::GetMaxPlayers () inline
Referenced by AttackDataDisp(), MyCreateFunc(), MyDestroyFunc(), MyReceiveFunc(), MyTerminateFunc(), PlayersInfoDisp(), and CMyD3DApplication::Render().
int GDPlay::GetNumPlayers () inline
Referenced by GWorld::DispNetJetAll(), DlgNetworkProc(), CMyD3DApplication::FrameMove(), getPlayerArms(), getPlayerChips(), getPlayerColor(), getPlayerCrushes(), getPlayerID(), getPlayerInits(), getPlayerName(), getPlayerName2(), getPlayerResets(), getPlayers(), getPlayerX(), getPlayerY(), getPlayerYForces(), getPlayerZ(), CMyD3DApplication::InitChips(), luaGetPlayerArms(), luaGetPlayerChips(), luaGetPlayerColor(), luaGetPlayerCrushes(), luaGetPlayerID(), luaGetPlayerInits(), luaGetPlayerName(), luaGetPlayerResets(), luaGetPlayers(), luaGetPlayerX(), luaGetPlayerY(), luaGetPlayerYForces(), luaGetPlayerZ(), luaReceiveMessage(), luaReceiveMessageClear(), MyReceiveFunc(), CMyD3DApplication::OneTimeSceneInit(), CMyD3DApplication::Render(), and CMyD3DApplication::ResetChips().
DWORD GDPlay::GetPlayersDPID (DPNID * dpnid) inline
Referenced by MyCreateFunc(), and MyDestroyFunc().
HRESULT GDPlay::GetPlayersName (DPNID dpnid, char * name) inline
Referenced by DlgNetworkProc(), MyCreateFunc(), MyDestroyFunc(), and MyReceiveFunc().
HRESULT GDPlay::GetSessionName (char * strSessionName) inline
Referenced by DlgNetworkProc(), and CMyD3DApplication::FrameMove().
HRESULT GDPlay::Init (HINSTANCE hInst) inline
Referenced by Close(), and CMyD3DApplication::CMyD3DApplication().
static HRESULT CALLBACK GDPlay::myMessageHandler (PVOID pvUserContext, DWORD dwMessageType, PVOID pMessage) inline static
Referenced by Init().
void GDPlay::NewSession (char * sessionName, char * username, int tcpPort, GUID appGuid) inline
Referenced by DlgNetworkProc().
HRESULT GDPlay::SendAll (BYTE * data, DWORD size) inline
Referenced by DlgNetworkProc(), and CMyD3DApplication::FrameMove().
HRESULT GDPlay::SendTo (DPNID dpnid, BYTE * data, DWORD size) inline
Referenced by DlgNetworkProc(), and MyReceiveFunc().
void GDPlay::SetConnect (BOOL f) inline
Referenced by CMyD3DApplication::FrameMove().
void GDPlay::SetCreateFunc (CreateFunc func) inline
Referenced by DlgNetworkProc().
void GDPlay::SetDestroyFunc (DestroyFunc func) inline
Referenced by DlgNetworkProc().
void GDPlay::SetReceiveFunc (ReceiveFunc func) inline
Referenced by DlgNetworkProc().
void GDPlay::SetTerminateFunc (TerminateFunc func) inline
Referenced by DlgNetworkProc().
Member Data Documentation
BOOL GDPlay::m_Connect private
Referenced by GetConnect(), and myMessageHandler().
CreateFunc GDPlay::m_CreateFunc private
Referenced by myMessageHandler().
CRITICAL_SECTION GDPlay::m_csPlayerContext private
Referenced by myMessageHandler().
DestroyFunc GDPlay::m_DestroyFunc private
Referenced by myMessageHandler().
DPNID GDPlay::m_dpnidHostPlayer private
Referenced by GetHostPlayerDPNID(), and myMessageHandler().
DPNID GDPlay::m_dpnidLocalPlayer private
Referenced by GetLocalPlayerDPNID(), and myMessageHandler().
DPNHANDLE GDPlay::m_hConnectAsyncOp private
DPNHANDLE GDPlay::m_hHostAsyncOp private
HINSTANCE GDPlay::m_hInst private
LONG GDPlay::m_MaxPlayers private
Referenced by GetMaxPlayers(), and NewSession().
LONG GDPlay::m_NumberOfActivePlayers private
Referenced by GetNumPlayers(), and myMessageHandler().
IDirectPlay8Peer* GDPlay::m_pDP private
Referenced by myMessageHandler().
IDirectPlay8LobbiedApplication* GDPlay::m_pLobbyApp private
Referenced by GetLobbyApp().
ReceiveFunc GDPlay::m_ReceiveFunc private
Referenced by myMessageHandler().
TerminateFunc GDPlay::m_TerminateFunc private
Referenced by myMessageHandler().
The documentation for this class was generated from the following file:
GDPlay.hpp