RigidChips: GMatrix Class Reference
GMatrix Class Reference
#include <GVector.hpp>
Public Member Functions
GMatrix (bool flag=true)
GMatrix (GFloat f[4][4])
GMatrix (GFloat f[16])
GMatrix (const GMatrix &)
GMatrix (const GMatrix33)
GMatrix (const GVector &u, const GVector &v, const GVector &w)
void get (double a[4][4])
void get (float a[4][4])
void put (double a[4][4])
void put (float a[4][4])
bool operator== (const GMatrix &) const
bool operator!= (const GMatrix &) const
GMatrix operator+ (const GMatrix &) const
GMatrix operator- (const GMatrix &) const
GMatrix operator* (const GMatrix &m) const
GVector operator* (const GVector &v) const
GMatrix operator* (const GFloat &) const
GMatrix inverse33 (void) const
GMatrix inverse (void) const
void inverse (GMatrix &im) const
GMatrix transpose (void) const
void transpose (GMatrix &m) const
GMatrix & operator= (const GMatrix &)
GMatrix & operator= (const GMatrix33 &)
GMatrix & operator+= (const GMatrix &)
GMatrix & operator-= (const GMatrix &)
GMatrix & operator*= (const GMatrix &)
GMatrix & operator*= (const GFloat &)
GMatrix scale (const GFloat &) const
GMatrix scale (const GVector &) const
GMatrix translate (const GVector &) const
GMatrix rotateX (const GFloat) const
GMatrix rotateY (const GFloat) const
GMatrix rotateZ (const GFloat) const
GMatrix rotate (const GVector &) const
GMatrix rotate (const GVector &axis, GFloat angle) const
void getEular (GFloat &yaw, GFloat &pitch, GFloat &roll)
GMatrix viewMatrixR (const GVector &at, const GVector &eye, const GVector &up) const
GMatrix viewMatrixL (const GVector &at, const GVector &eye, const GVector &up) const
GMatrix projectionMatrix (GFloat fovy, GFloat aspect, GFloat nearZ, GFloat farZ) const
GMatrix projectionMatrixX (GFloat fovy, GFloat aspect, GFloat nearZ, GFloat farZ) const
GMatrix projectionMatrix (GFloat d) const
void unity (void)
GMatrix select33 (void) const
bool isUnity (void) const
GQuat quat (void)
Public Attributes
GFloat elem [4][4]
Friends
GVector operator* (GVector v, GMatrix m)
Constructor & Destructor Documentation
GMatrix::GMatrix (bool flag = true) inline
GMatrix::GMatrix (GFloat f[4][4]) inline
GMatrix::GMatrix (GFloat f[16]) inline
GMatrix::GMatrix (const GMatrix & m)
GMatrix::GMatrix (const GMatrix33 m)
GMatrix::GMatrix (const GVector & u, const GVector & v, const GVector & w) inline
Member Function Documentation
void GMatrix::get (double a[4][4]) inline
void GMatrix::get (float a[4][4]) inline
void GMatrix::getEular (GFloat & yaw, GFloat & pitch, GFloat & roll)
GMatrix GMatrix::inverse (void) const
Referenced by GRigid::Calc(), GRigid::CalcLight(), and luaRy().
void GMatrix::inverse (GMatrix & im) const
GMatrix GMatrix::inverse33 (void) const
bool GMatrix::isUnity (void) const
bool GMatrix::operator!= (const GMatrix & m) const
GMatrix GMatrix::operator* (const GMatrix & m) const inline
GVector GMatrix::operator* (const GVector & v) const inline
GMatrix GMatrix::operator* (const GFloat & f) const
GMatrix & GMatrix::operator*= (const GMatrix & m)
GMatrix & GMatrix::operator*= (const GFloat & f)
GMatrix GMatrix::operator+ (const GMatrix & m) const
GMatrix & GMatrix::operator+= (const GMatrix & m)
GMatrix GMatrix::operator- (const GMatrix & m) const
GMatrix & GMatrix::operator-= (const GMatrix & m)
GMatrix & GMatrix::operator= (const GMatrix & m)
GMatrix & GMatrix::operator= (const GMatrix33 & m)
bool GMatrix::operator== (const GMatrix & m) const
GMatrix GMatrix::projectionMatrix (GFloat fovy, GFloat aspect, GFloat nearZ, GFloat farZ) const
GMatrix GMatrix::projectionMatrix (GFloat d) const
GMatrix GMatrix::projectionMatrixX (GFloat fovy, GFloat aspect, GFloat nearZ, GFloat farZ) const
void GMatrix::put (double a[4][4]) inline
void GMatrix::put (float a[4][4]) inline
GQuat GMatrix::quat (void)
Referenced by CMyD3DApplication::FrameMove(), and GRigid::RSet().
GMatrix GMatrix::rotate (const GVector & v) const
Referenced by GWorld::AddCowl(), GWorld::AddHinge(), GWorld::CalcCowl(), GWorld::CalcLinkCowl(), GWorld::CheckLink(), and CMyD3DApplication::ViewSet().
GMatrix GMatrix::rotate (const GVector & axis, GFloat angle) const
GMatrix GMatrix::rotateX (const GFloat angle) const
Referenced by luaCollisionObjRingArea(), luaCollisionRingArea(), luaDirect(), luaDirectObj(), luaRotate(), and luaRotateObj().
GMatrix GMatrix::rotateY (const GFloat angle) const
Referenced by luaCollisionObjRingArea(), luaCollisionRingArea(), luaDirect(), luaDirectObj(), luaRotate(), luaRotateObj(), ResetChip(), ResetChip2(), and ResetObject().
GMatrix GMatrix::rotateZ (const GFloat angle) const
Referenced by luaCollisionObjRingArea(), luaCollisionRingArea(), luaDirect(), luaDirectObj(), luaRotate(), and luaRotateObj().
GMatrix GMatrix::scale (const GFloat & f) const
Referenced by GRigid::DispShadow().
GMatrix GMatrix::scale (const GVector & v) const
GMatrix GMatrix::select33 (void) const
GMatrix GMatrix::translate (const GVector & v) const
Referenced by GWorld::AddJoint(), GRigid::Calc(), GWorld::DispNetChip(), GWorld::DispNetJetAll(), GRigid::DispShadow(), GRigid::Impulse(), GRigid::Reset(), GWorld::RestoreLink(), GRigid::RotateWithChild(), GRigid::RSet(), GRigid::TranslateWithChild(), and GRigid::TranslateWithParent().
GMatrix GMatrix::transpose (void) const
Referenced by GWorld::AddObject(), GWorld::AddRigid(), GRigid::Calc(), GRigid::CalcLight(), GRigid::CollisionCheck(), luaRx(), luaRz(), GQuat::matrix(), projectionMatrix(), projectionMatrixX(), GRigid::Reset(), GWorld::RestoreLink(), rotate(), GRigid::RotateWithChildAbs(), rotateX(), rotateY(), rotateZ(), GRigid::RSet(), rx(), ry(), rz(), GVector::star(), translate(), GWorld::UpdateRigid(), viewMatrixL(), and viewMatrixR().
void GMatrix::transpose (GMatrix & m) const
void GMatrix::unity (void)
GMatrix GMatrix::viewMatrixL (const GVector & at, const GVector & eye, const GVector & up) const
GMatrix GMatrix::viewMatrixR (const GVector & at, const GVector & eye, const GVector & up) const
Friends And Related Function Documentation
GVector operator* (GVector v, GMatrix m) friend
Member Data Documentation
GFloat GMatrix::elem[4][4]
Referenced by GRigid::CollisionCheck(), GRigid::Disp(), GRigid::DispJet(), GWorld::DispNetChip(), GWorld::DispNetJet(), GRigid::DispObject(), ex(), ey(), ez(), getEular(), GMatrix(), GMatrix33::GMatrix33(), inverse(), inverse33(), isUnity(), luaCollisionObjRingArea(), luaCollisionRingArea(), luaEx(), luaEy(), luaEz(), luaRx(), luaRy(), luaRz(), GQuat::matrix(), operator!=(), operator*(), GMatrix33::operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator=(), GMatrix33::operator=(), operator==(), projectionMatrix(), projectionMatrixX(), quat(), CMyD3DApplication::Render(), rotate(), rotateX(), rotateY(), rotateZ(), rx(), ry(), rz(), scale(), select33(), GVector::star(), translate(), transpose(), unity(), viewMatrixL(), and viewMatrixR().
The documentation for this class was generated from the following files:
GVector.hpp
GVector.cpp