RigidChips: GBullet Class Reference
GBullet Class Reference
#include <GParticle.hpp>
Public Member Functions
GBullet (int n)
~GBullet ()
GBulletVertex * Add (GRigid *rigid, GVector pos, GVector vec, GFloat power, GFloat size, GFloat dist, GVector t, DWORD dpnid)
void Clear ()
void Move ()
Public Attributes
GBulletVertex * Vertex
int NextVertex
int MaxVertex
Constructor & Destructor Documentation
GBullet::GBullet (int n) inline
GBullet::~GBullet () inline
Member Function Documentation
GBulletVertex* GBullet::Add (GRigid * rigid, GVector pos, GVector vec, GFloat power, GFloat size, GFloat dist, GVector t, DWORD dpnid) inline
Referenced by CMyD3DApplication::FrameMove(), and MyReceiveFunc().
void GBullet::Clear () inline
Referenced by CMyD3DApplication::FrameMove(), GBullet(), CMyD3DApplication::InitChips(), and CMyD3DApplication::ResetChips().
void GBullet::Move () inline
Referenced by GWorld::Move().
Member Data Documentation
int GBullet::MaxVertex
Referenced by Clear(), CMyD3DApplication::FrameMove(), Move(), GWorld::Move(), and CMyD3DApplication::Render().
int GBullet::NextVertex
Referenced by Add().
GBulletVertex* GBullet::Vertex
Referenced by CMyD3DApplication::FrameMove(), GWorld::Move(), CMyD3DApplication::Render(), and ~GBullet().
The documentation for this class was generated from the following file:
GParticle.hpp