RigidChips: CD3DFile Class Reference
CD3DFile Class Reference
#include <d3dfile.h>
Public Member Functions
HRESULT Create (LPDIRECT3DDEVICE8 pd3dDevice, TCHAR *strFilename)
HRESULT CreateFromResource (LPDIRECT3DDEVICE8 pd3dDevice, TCHAR *strResource, TCHAR *strType)
HRESULT Render (LPDIRECT3DDEVICE8 pd3dDevice, D3DXMATRIX *pmatWorldMatrix=NULL)
CD3DFile ()
Public Member Functions inherited from CD3DFrame
VOID SetMatrix (D3DXMATRIX *pmat)
D3DXMATRIX * GetMatrix ()
CD3DMesh * FindMesh (TCHAR *strMeshName)
CD3DFrame * FindFrame (TCHAR *strFrameName)
BOOL EnumMeshes (BOOL(*EnumMeshCB)(CD3DMesh *, VOID *), VOID *pContext)
HRESULT Destroy ()
HRESULT RestoreDeviceObjects (LPDIRECT3DDEVICE8 pd3dDevice)
HRESULT InvalidateDeviceObjects ()
HRESULT Render (LPDIRECT3DDEVICE8 pd3dDevice, BOOL bDrawOpaqueSubsets=TRUE, BOOL bDrawAlphaSubsets=TRUE, D3DXMATRIX *pmatWorldMartix=NULL)
CD3DFrame (TCHAR *strName=_T("CD3DFile_Frame"))
virtual ~CD3DFrame ()
Private Member Functions
HRESULT LoadMesh (LPDIRECT3DDEVICE8 pd3dDevice, LPDIRECTXFILEDATA pFileData, CD3DFrame *pParentFrame)
HRESULT LoadFrame (LPDIRECT3DDEVICE8 pd3dDevice, LPDIRECTXFILEDATA pFileData, CD3DFrame *pParentFrame)
Additional Inherited Members
Public Attributes inherited from CD3DFrame
TCHAR m_strName [512]
D3DXMATRIX m_mat
CD3DMesh * m_pMesh
TCHAR m_strMeshName [512]
CD3DFrame * m_pNext
CD3DFrame * m_pChild
Constructor & Destructor Documentation
CD3DFile::CD3DFile () inline
Member Function Documentation
HRESULT CD3DFile::Create (LPDIRECT3DDEVICE8 pd3dDevice, TCHAR * strFilename)
HRESULT CD3DFile::CreateFromResource (LPDIRECT3DDEVICE8 pd3dDevice, TCHAR * strResource, TCHAR * strType)
HRESULT CD3DFile::LoadFrame (LPDIRECT3DDEVICE8 pd3dDevice, LPDIRECTXFILEDATA pFileData, CD3DFrame * pParentFrame) private
Referenced by Create(), and CreateFromResource().
HRESULT CD3DFile::LoadMesh (LPDIRECT3DDEVICE8 pd3dDevice, LPDIRECTXFILEDATA pFileData, CD3DFrame * pParentFrame) private
Referenced by LoadFrame().
HRESULT CD3DFile::Render (LPDIRECT3DDEVICE8 pd3dDevice, D3DXMATRIX * pmatWorldMatrix = NULL)
The documentation for this class was generated from the following files:
d3dfile.h
d3dfile.cpp