RigidChips: CMyD3DApplication Class Reference
CMyD3DApplication Class Reference
#include <Rigidmain.h>
Public Member Functions
HRESULT ViewSet ()
VOID Pause (BOOL bPause)
void SetRegulationMenu ()
LRESULT MsgProc (HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam)
CMyD3DApplication ()
HRESULT ResetChips (float x, float z, float a)
HRESULT ResetChips (float y, float a)
HRESULT InitChips (float a, int hereFlag)
HRESULT InputAddDeviceCB (CInputDeviceManager::DeviceInfo *pDeviceInfo, const DIDEVICEINSTANCE *pdidi)
BOOL ConfigureInputDevicesCB (IUnknown *pUnknown)
Public Member Functions inherited from CD3DApplication
virtual HRESULT Create (HINSTANCE hInstance)
virtual INT Run ()
CD3DApplication ()
Static Public Member Functions
static HRESULT CALLBACK StaticInputAddDeviceCB (CInputDeviceManager::DeviceInfo *pDeviceInfo, const DIDEVICEINSTANCE *pdidi, LPVOID pParam)
static BOOL CALLBACK StaticConfigureInputDevicesCB (IUnknown *pUnknown, VOID *pUserData)
Public Attributes
BOOL m_bLoadingApp
CD3DFont * m_pFont
CD3DFont * m_pFontL
CD3DFont * m_pFont3D
CInputDeviceManager * m_pInputDeviceManager
DIACTIONFORMAT m_diafGame
LPDIRECT3DSURFACE8 m_pDIConfigSurface
UserInput m_UserInput
FLOAT m_fSoundPlayRepeatCountdown
FLOAT m_fSoundPlayRepeatCountdown2
FLOAT m_fWorldRotX
FLOAT m_fWorldRotY
int m_appID
BOOL m_inputFocus
HIMC m_hIMC
Public Attributes inherited from CD3DApplication
BOOL m_bWindowed
LPDIRECT3D8 m_pD3D
LPDIRECT3DDEVICE8 m_pd3dDevice
D3DCAPS8 m_d3dCaps
Protected Member Functions
HRESULT LoadData (char *filename)
HRESULT LoadProp (FILE *fp, int i)
HRESULT SaveProp (FILE *fp, int i)
HRESULT LoadLog (char *fname)
HRESULT SaveLog (char *fname)
HRESULT PlayLog ()
HRESULT OneTimeSceneInit ()
HRESULT InitDeviceObjects ()
HRESULT RestoreDeviceObjects ()
HRESULT InvalidateDeviceObjects ()
HRESULT DeleteDeviceObjects ()
void RenderSky ()
HRESULT Render ()
HRESULT FrameMove ()
HRESULT FinalCleanup ()
HRESULT ConfirmDevice (D3DCAPS8 *, DWORD, D3DFORMAT)
HRESULT RenderText ()
HRESULT InitInput (HWND hWnd)
void ClearInput (UserInput *pUserInput)
void DummyInput (UserInput *pUserInput)
void UpdateInput (UserInput *pUserInput)
void CleanupDirectInput ()
HRESULT InitAudio (HWND hWnd)
VOID ReadSettings ()
VOID WriteSettings ()
Protected Member Functions inherited from CD3DApplication
HRESULT DisplayErrorMsg (HRESULT hr, DWORD dwType)
HRESULT BuildDeviceList ()
BOOL FindDepthStencilFormat (UINT iAdapter, D3DDEVTYPE DeviceType, D3DFORMAT TargetFormat, D3DFORMAT *pDepthStencilFormat)
HRESULT Initialize3DEnvironment ()
HRESULT Resize3DEnvironment ()
HRESULT ToggleFullscreen ()
HRESULT ForceWindowed ()
HRESULT UserSelectNewDevice ()
VOID Cleanup3DEnvironment ()
HRESULT Render3DEnvironment ()
virtual HRESULT AdjustWindowForChange ()
Additional Inherited Members
Static Protected Member Functions inherited from CD3DApplication
static INT_PTR CALLBACK SelectDeviceProc (HWND hDlg, UINT msg, WPARAM wParam, LPARAM lParam)
Protected Attributes inherited from CD3DApplication
D3DAdapterInfo m_Adapters [10]
DWORD m_dwNumAdapters
DWORD m_dwAdapter
BOOL m_bActive
BOOL m_bReady
BOOL m_bHasFocus
BOOL m_bFocus
DWORD m_dLimidFPS
BOOL m_bFrameMoving
BOOL m_bSingleStep
D3DPRESENT_PARAMETERS m_d3dpp
HWND m_hWnd
HWND m_hWndFocus
D3DSURFACE_DESC m_d3dsdBackBuffer
DWORD m_dwCreateFlags
DWORD m_dwWindowStyle
RECT m_rcWindowBounds
RECT m_rcWindowClient
FLOAT m_fTime
FLOAT m_fElapsedTime
FLOAT m_fFPS
TCHAR m_strDeviceStats [90]
TCHAR m_strFrameStats [90]
TCHAR * m_strWindowTitle
BOOL m_bUseDepthBuffer
DWORD m_dwMinDepthBits
DWORD m_dwMinStencilBits
DWORD m_dwCreationWidth
DWORD m_dwCreationHeight
BOOL m_bShowCursorWhenFullscreen
BOOL m_bClipCursorWhenFullscreen
Constructor & Destructor Documentation
CMyD3DApplication::CMyD3DApplication ()
Member Function Documentation
VOID CMyD3DApplication::CleanupDirectInput () protected
Referenced by FinalCleanup().
void CMyD3DApplication::ClearInput (UserInput * pUserInput) protected
Referenced by FrameMove(), InitDeviceObjects(), and OneTimeSceneInit().
BOOL CMyD3DApplication::ConfigureInputDevicesCB (IUnknown * pUnknown)
Referenced by StaticConfigureInputDevicesCB().
HRESULT CMyD3DApplication::ConfirmDevice (D3DCAPS8 * pCaps, DWORD dwBehavior, D3DFORMAT Format) protected virtual
Reimplemented from CD3DApplication.
HRESULT CMyD3DApplication::DeleteDeviceObjects () protected virtual
Reimplemented from CD3DApplication.
void CMyD3DApplication::DummyInput (UserInput * pUserInput) protected
Referenced by FrameMove().
HRESULT CMyD3DApplication::FinalCleanup () protected virtual
Reimplemented from CD3DApplication.
HRESULT CMyD3DApplication::FrameMove () protected virtual
Reimplemented from CD3DApplication.
HRESULT CMyD3DApplication::InitAudio (HWND hWnd) protected
HRESULT CMyD3DApplication::InitChips (float a, int hereFlag)
Referenced by FrameMove(), and LoadData().
HRESULT CMyD3DApplication::InitDeviceObjects () protected virtual
Reimplemented from CD3DApplication.
HRESULT CMyD3DApplication::InitInput (HWND hWnd) protected
Referenced by OneTimeSceneInit().
HRESULT CMyD3DApplication::InputAddDeviceCB (CInputDeviceManager::DeviceInfo * pDeviceInfo, const DIDEVICEINSTANCE * pdidi)
Referenced by StaticInputAddDeviceCB().
HRESULT CMyD3DApplication::InvalidateDeviceObjects () protected virtual
Reimplemented from CD3DApplication.
HRESULT CMyD3DApplication::LoadData (char * filename) protected
Referenced by FrameMove(), and MsgProc().
HRESULT CMyD3DApplication::LoadLog (char * fname) protected
Referenced by FrameMove().
HRESULT CMyD3DApplication::LoadProp (FILE * fp, int i) protected
Referenced by LoadLog().
LRESULT CMyD3DApplication::MsgProc (HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam) virtual
Reimplemented from CD3DApplication.
HRESULT CMyD3DApplication::OneTimeSceneInit () protected virtual
Reimplemented from CD3DApplication.
VOID CMyD3DApplication::Pause (BOOL bPause) virtual
Reimplemented from CD3DApplication.
Referenced by DlgNetworkProc(), FinalCleanup(), and FrameMove().
HRESULT CMyD3DApplication::PlayLog () protected
Referenced by FrameMove().
VOID CMyD3DApplication::ReadSettings () protected
Referenced by CMyD3DApplication().
HRESULT CMyD3DApplication::Render (void) protected virtual
Reimplemented from CD3DApplication.
Referenced by ConfigureInputDevicesCB().
void CMyD3DApplication::RenderSky () protected
Referenced by ViewSet().
HRESULT CMyD3DApplication::RenderText () protected
Referenced by Render().
HRESULT CMyD3DApplication::ResetChips (float x, float z, float a)
Referenced by FrameMove(), LoadData(), and luaUpdateChips().
HRESULT CMyD3DApplication::ResetChips (float y, float a)
HRESULT CMyD3DApplication::RestoreDeviceObjects () protected virtual
Reimplemented from CD3DApplication.
HRESULT CMyD3DApplication::SaveLog (char * fname) protected
Referenced by FrameMove().
HRESULT CMyD3DApplication::SaveProp (FILE * fp, int i) protected
Referenced by SaveLog().
void CMyD3DApplication::SetRegulationMenu ()
Referenced by FrameMove(), luaSetRegulationFlag(), and PlayLog().
BOOL CALLBACK CMyD3DApplication::StaticConfigureInputDevicesCB (IUnknown * pUnknown, VOID * pUserData) static
Referenced by FrameMove().
HRESULT CALLBACK CMyD3DApplication::StaticInputAddDeviceCB (CInputDeviceManager::DeviceInfo * pDeviceInfo, const DIDEVICEINSTANCE * pdidi, LPVOID pParam) static
Referenced by InitInput().
void CMyD3DApplication::UpdateInput (UserInput * pUserInput) protected
Referenced by FrameMove().
HRESULT CMyD3DApplication::ViewSet ()
Referenced by luaLine2D(), luaLine3D(), and Render().
VOID CMyD3DApplication::WriteSettings () protected
Referenced by FinalCleanup().
Member Data Documentation
int CMyD3DApplication::m_appID
Referenced by CMyD3DApplication().
BOOL CMyD3DApplication::m_bLoadingApp
Referenced by CMyD3DApplication(), MsgProc(), and OneTimeSceneInit().
DIACTIONFORMAT CMyD3DApplication::m_diafGame
Referenced by InitInput().
FLOAT CMyD3DApplication::m_fSoundPlayRepeatCountdown
FLOAT CMyD3DApplication::m_fSoundPlayRepeatCountdown2
FLOAT CMyD3DApplication::m_fWorldRotX
Referenced by CMyD3DApplication().
FLOAT CMyD3DApplication::m_fWorldRotY
Referenced by CMyD3DApplication().
HIMC CMyD3DApplication::m_hIMC
Referenced by CMyD3DApplication(), and OneTimeSceneInit().
BOOL CMyD3DApplication::m_inputFocus
Referenced by CMyD3DApplication().
LPDIRECT3DSURFACE8 CMyD3DApplication::m_pDIConfigSurface
Referenced by CMyD3DApplication(), FrameMove(), InvalidateDeviceObjects(), and RestoreDeviceObjects().
CD3DFont* CMyD3DApplication::m_pFont
Referenced by CMyD3DApplication(), DeleteDeviceObjects(), FinalCleanup(), InitDeviceObjects(), InvalidateDeviceObjects(), RenderText(), and RestoreDeviceObjects().
CD3DFont* CMyD3DApplication::m_pFont3D
Referenced by CMyD3DApplication(), DeleteDeviceObjects(), GWorld::DispNetChipInfo(), FinalCleanup(), InitDeviceObjects(), InvalidateDeviceObjects(), and RestoreDeviceObjects().
CD3DFont* CMyD3DApplication::m_pFontL
Referenced by CMyD3DApplication(), DeleteDeviceObjects(), FinalCleanup(), InitDeviceObjects(), InvalidateDeviceObjects(), RenderText(), and RestoreDeviceObjects().
CInputDeviceManager* CMyD3DApplication::m_pInputDeviceManager
Referenced by CleanupDirectInput(), CMyD3DApplication(), FrameMove(), InitInput(), Pause(), and UpdateInput().
UserInput CMyD3DApplication::m_UserInput
Referenced by CMyD3DApplication(), FrameMove(), InitDeviceObjects(), MsgProc(), and OneTimeSceneInit().
The documentation for this class was generated from the following files:
Rigidmain.h
Rigidmain.cpp