RigidChips: BDATuningModel::TNLocatorHelper< LOCATORTYPE > Class Template Reference
BDATuningModel::TNLocatorHelper< LOCATORTYPE > Class Template Reference
#include <tune.h>
Public Member Functions
TNLocatorHelper ()
TNLocatorHelper (const LOCATORTYPE &a)
TNLocatorHelper (IUnknown *p)
TNLocatorHelper (const TNLocatorHelper< LOCATORTYPE > &a)
TNLocatorHelper (ILocator *p)
TNLocatorHelper< LOCATORTYPE > & operator= (TNLocatorHelper< LOCATORTYPE > &rhs)
TNLocatorHelper< LOCATORTYPE > & operator= (LOCATORTYPE &rhs)
TNLocatorHelper< LOCATORTYPE > & operator= (ILocator *rhs)
TNLocatorHelper< LOCATORTYPE > & operator= (IUnknown *rhs)
void Clone ()
long CarrierFrequency ()
HRESULT CarrierFrequency (long f)
FECMethod InnerFEC ()
HRESULT InnerFEC (FECMethod f)
BinaryConvolutionCodeRate InnerFECRate ()
HRESULT InnerFECRate (BinaryConvolutionCodeRate f)
FECMethod OuterFEC ()
HRESULT OuterFEC (FECMethod f)
BinaryConvolutionCodeRate OuterFECRate ()
HRESULT OuterFECRate (BinaryConvolutionCodeRate f)
ModulationType Modulation ()
HRESULT Modulation (ModulationType f)
long SymbolRate ()
HRESULT SymbolRate (long f)
Constructor & Destructor Documentation
template<class LOCATORTYPE> BDATuningModel::TNLocatorHelper< LOCATORTYPE >::TNLocatorHelper () inline
template<class LOCATORTYPE> BDATuningModel::TNLocatorHelper< LOCATORTYPE >::TNLocatorHelper (const LOCATORTYPE & a) inline
template<class LOCATORTYPE> BDATuningModel::TNLocatorHelper< LOCATORTYPE >::TNLocatorHelper (IUnknown * p) inline
template<class LOCATORTYPE> BDATuningModel::TNLocatorHelper< LOCATORTYPE >::TNLocatorHelper (const TNLocatorHelper< LOCATORTYPE > & a) inline
template<class LOCATORTYPE> BDATuningModel::TNLocatorHelper< LOCATORTYPE >::TNLocatorHelper (ILocator * p) inline
Member Function Documentation
template<class LOCATORTYPE> long BDATuningModel::TNLocatorHelper< LOCATORTYPE >::CarrierFrequency () inline
template<class LOCATORTYPE> HRESULT BDATuningModel::TNLocatorHelper< LOCATORTYPE >::CarrierFrequency (long f) inline
template<class LOCATORTYPE> void BDATuningModel::TNLocatorHelper< LOCATORTYPE >::Clone () inline
template<class LOCATORTYPE> FECMethod BDATuningModel::TNLocatorHelper< LOCATORTYPE >::InnerFEC () inline
template<class LOCATORTYPE> HRESULT BDATuningModel::TNLocatorHelper< LOCATORTYPE >::InnerFEC (FECMethod f) inline
template<class LOCATORTYPE> BinaryConvolutionCodeRate BDATuningModel::TNLocatorHelper< LOCATORTYPE >::InnerFECRate () inline
template<class LOCATORTYPE> HRESULT BDATuningModel::TNLocatorHelper< LOCATORTYPE >::InnerFECRate (BinaryConvolutionCodeRate f) inline
template<class LOCATORTYPE> ModulationType BDATuningModel::TNLocatorHelper< LOCATORTYPE >::Modulation () inline
template<class LOCATORTYPE> HRESULT BDATuningModel::TNLocatorHelper< LOCATORTYPE >::Modulation (ModulationType f) inline
template<class LOCATORTYPE> TNLocatorHelper<LOCATORTYPE>& BDATuningModel::TNLocatorHelper< LOCATORTYPE >::operator= (TNLocatorHelper< LOCATORTYPE > & rhs) inline
Referenced by BDATuningModel::TNATSCLocatorHelper< LOCATORTYPE >::operator=(), BDATuningModel::TNDVBSLocatorHelper< LOCATORTYPE >::operator=(), BDATuningModel::TNDVBTLocatorHelper< LOCATORTYPE >::operator=(), and BDATuningModel::TNDVBCLocatorHelper< LOCATORTYPE >::operator=().
template<class LOCATORTYPE> TNLocatorHelper<LOCATORTYPE>& BDATuningModel::TNLocatorHelper< LOCATORTYPE >::operator= (LOCATORTYPE & rhs) inline
template<class LOCATORTYPE> TNLocatorHelper<LOCATORTYPE>& BDATuningModel::TNLocatorHelper< LOCATORTYPE >::operator= (ILocator * rhs) inline
template<class LOCATORTYPE> TNLocatorHelper<LOCATORTYPE>& BDATuningModel::TNLocatorHelper< LOCATORTYPE >::operator= (IUnknown * rhs) inline
template<class LOCATORTYPE> FECMethod BDATuningModel::TNLocatorHelper< LOCATORTYPE >::OuterFEC () inline
template<class LOCATORTYPE> HRESULT BDATuningModel::TNLocatorHelper< LOCATORTYPE >::OuterFEC (FECMethod f) inline
template<class LOCATORTYPE> BinaryConvolutionCodeRate BDATuningModel::TNLocatorHelper< LOCATORTYPE >::OuterFECRate () inline
template<class LOCATORTYPE> HRESULT BDATuningModel::TNLocatorHelper< LOCATORTYPE >::OuterFECRate (BinaryConvolutionCodeRate f) inline
template<class LOCATORTYPE> long BDATuningModel::TNLocatorHelper< LOCATORTYPE >::SymbolRate () inline
template<class LOCATORTYPE> HRESULT BDATuningModel::TNLocatorHelper< LOCATORTYPE >::SymbolRate (long f) inline
The documentation for this class was generated from the following file:
microsoft directx 9.0 sdk (summer 2004)/Include/tune.h