RigidChips: GParticle Class Reference
GParticle Class Reference
#include <GParticle.hpp>
Public Member Functions
GParticle (int n)
~GParticle ()
GParticleVertex * Add (GVector pos, GVector vec, GVector acc, GFloat sizeD, GFloat life, GFloat lifeSpan, GVector col)
GParticleVertex * Add (int type, GVector pos, GVector vec, GVector acc, GFloat sizeD, GFloat life, GFloat lifeSpan, GVector col, DWORD dpnid)
void Clear ()
void Move ()
Public Attributes
GParticleVertex * Vertex
int NextVertex
int MaxVertex
Constructor & Destructor Documentation
GParticle::GParticle (int n) inline
GParticle::~GParticle () inline
Member Function Documentation
GParticleVertex* GParticle::Add (GVector pos, GVector vec, GVector acc, GFloat sizeD, GFloat life, GFloat lifeSpan, GVector col) inline
Referenced by GRigid::ApplyExtForce(), CMyD3DApplication::FrameMove(), GRigid::Impulse(), GWorld::Move(), and MyReceiveFunc().
GParticleVertex* GParticle::Add (int type, GVector pos, GVector vec, GVector acc, GFloat sizeD, GFloat life, GFloat lifeSpan, GVector col, DWORD dpnid) inline
void GParticle::Clear () inline
Referenced by CMyD3DApplication::FrameMove(), GParticle(), CMyD3DApplication::InitChips(), and CMyD3DApplication::ResetChips().
void GParticle::Move () inline
Referenced by GWorld::Move().
Member Data Documentation
int GParticle::MaxVertex
Referenced by Clear(), CMyD3DApplication::FrameMove(), Move(), and CMyD3DApplication::Render().
int GParticle::NextVertex
Referenced by Add().
GParticleVertex* GParticle::Vertex
Referenced by CMyD3DApplication::FrameMove(), CMyD3DApplication::Render(), and ~GParticle().
The documentation for this class was generated from the following file:
GParticle.hpp