RigidChips: BDATuningModel::TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE > Class Template Reference
BDATuningModel::TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE > Class Template Reference
#include <tune.h>
Public Member Functions
TNTuningSpaceHelper ()
TNTuningSpaceHelper (const TUNINGSPACETYPE &a)
TNTuningSpaceHelper (ITuningSpace *p)
TNTuningSpaceHelper (IUnknown *p)
TNTuningSpaceHelper (const TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE > &a)
TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE > & operator= (TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE > &rhs)
TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE > & operator= (TUNINGSPACETYPE &rhs)
TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE > & operator= (IUnknown *rhs)
TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE > & operator= (ITuningSpace *rhs)
bool operator== (TUNINGSPACETYPE &rhs)
bool operator!= (TUNINGSPACETYPE &rhs)
PQTuneRequest CreateTuneRequest ()
PQLocator Locator ()
HRESULT Locator (PQLocator &l)
void Clone ()
Constructor & Destructor Documentation
template<class TUNINGSPACETYPE, class TUNEREQUESTTYPE> BDATuningModel::TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE >::TNTuningSpaceHelper () inline
template<class TUNINGSPACETYPE, class TUNEREQUESTTYPE> BDATuningModel::TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE >::TNTuningSpaceHelper (const TUNINGSPACETYPE & a) inline
template<class TUNINGSPACETYPE, class TUNEREQUESTTYPE> BDATuningModel::TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE >::TNTuningSpaceHelper (ITuningSpace * p) inline
template<class TUNINGSPACETYPE, class TUNEREQUESTTYPE> BDATuningModel::TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE >::TNTuningSpaceHelper (IUnknown * p) inline
template<class TUNINGSPACETYPE, class TUNEREQUESTTYPE> BDATuningModel::TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE >::TNTuningSpaceHelper (const TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE > & a) inline
Member Function Documentation
template<class TUNINGSPACETYPE, class TUNEREQUESTTYPE> void BDATuningModel::TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE >::Clone () inline
template<class TUNINGSPACETYPE, class TUNEREQUESTTYPE> PQTuneRequest BDATuningModel::TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE >::CreateTuneRequest () inline
template<class TUNINGSPACETYPE, class TUNEREQUESTTYPE> PQLocator BDATuningModel::TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE >::Locator () inline
template<class TUNINGSPACETYPE, class TUNEREQUESTTYPE> HRESULT BDATuningModel::TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE >::Locator (PQLocator & l) inline
template<class TUNINGSPACETYPE, class TUNEREQUESTTYPE> bool BDATuningModel::TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE >::operator!= (TUNINGSPACETYPE & rhs) inline
template<class TUNINGSPACETYPE, class TUNEREQUESTTYPE> TNTuningSpaceHelper<TUNINGSPACETYPE, TUNEREQUESTTYPE>& BDATuningModel::TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE >::operator= (TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE > & rhs) inline
Referenced by BDATuningModel::TNAnalogRadioTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE >::operator=(), BDATuningModel::TNAnalogTVTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE >::operator=(), BDATuningModel::TNAuxInTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE >::operator=(), and BDATuningModel::TNDVBTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE >::operator=().
template<class TUNINGSPACETYPE, class TUNEREQUESTTYPE> TNTuningSpaceHelper<TUNINGSPACETYPE, TUNEREQUESTTYPE>& BDATuningModel::TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE >::operator= (TUNINGSPACETYPE & rhs) inline
template<class TUNINGSPACETYPE, class TUNEREQUESTTYPE> TNTuningSpaceHelper<TUNINGSPACETYPE, TUNEREQUESTTYPE>& BDATuningModel::TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE >::operator= (IUnknown * rhs) inline
template<class TUNINGSPACETYPE, class TUNEREQUESTTYPE> TNTuningSpaceHelper<TUNINGSPACETYPE, TUNEREQUESTTYPE>& BDATuningModel::TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE >::operator= (ITuningSpace * rhs) inline
template<class TUNINGSPACETYPE, class TUNEREQUESTTYPE> bool BDATuningModel::TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE >::operator== (TUNINGSPACETYPE & rhs) inline
Referenced by BDATuningModel::TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE >::operator!=().
The documentation for this class was generated from the following file:
microsoft directx 9.0 sdk (summer 2004)/Include/tune.h