RigidChips: GLand Class Reference
GLand Class Reference
#include <GLand.hpp>
Public Member Functions
GLand (int v, int f)
~GLand ()
void Set ()
GFloat GetY (GFloat x, GFloat z)
GFloat GetY2 (GFloat x, GFloat y, GFloat z)
void List3Reset (void)
int List3up (GVector &p, GFloat r)
void List2Reset (void)
int List2up (GVector &p, GFloat r)
int List1up (GVector &p, GFloat r)
GFloat Check (const GVector &p, const GVector &v, GVector &n, GFloat &Ud, GFloat &Us)
int Check2 (GVector &p, GFloat r)
void ClipShadow (GVector shadow1[], int sn1, int FaceID, GVector shadow2[], int *sn2)
int CheckClip (GVector *A, GVector *P0, GVector *P1, GVector *P2, GVector *P)
void ClipFace (GVector *A, GVector *P0, GVector *Pt1, int n1, GVector *Pt2, int &n2)
GLand (int v, int f)
void Set ()
double Check (GVector *p)
Public Attributes
int VertexCount
int FaceCount
GLandVertex * Vertex
GLandFace * Face
int * List1
GVector List1P
float List1R
int List1Count
int * List2
int List2Count
int * List3
int List3Count
int * HitList
GFloat * HitD
unsigned long AttribTableSize
GVector * HitNormal
int HitListCount
Constructor & Destructor Documentation
GLand::GLand (int v, int f) inline
GLand::~GLand () inline
GLand::GLand (int v, int f) inline
Member Function Documentation
double GLand::Check (GVector * p) inline
GFloat GLand::Check (const GVector & p, const GVector & v, GVector & n, GFloat & Ud, GFloat & Us) inline
Referenced by GRigid::CollisionCheck().
int GLand::Check2 (GVector & p, GFloat r) inline
Referenced by GRigid::CollisionCheck().
int GLand::CheckClip (GVector * A, GVector * P0, GVector * P1, GVector * P2, GVector * P) inline
Referenced by ClipFace().
void GLand::ClipFace (GVector * A, GVector * P0, GVector * Pt1, int n1, GVector * Pt2, int & n2) inline
Referenced by ClipShadow().
void GLand::ClipShadow (GVector shadow1[], int sn1, int FaceID, GVector shadow2[], int * sn2) inline
Referenced by GRigid::DispShadow().
GFloat GLand::GetY (GFloat x, GFloat z) inline
Referenced by CMyD3DApplication::FrameMove(), CMyD3DApplication::InitChips(), CMyD3DApplication::InitDeviceObjects(), luaLoadLand(), and CMyD3DApplication::ResetChips().
GFloat GLand::GetY2 (GFloat x, GFloat y, GFloat z) inline
Referenced by getY(), and luaGetY().
int GLand::List1up (GVector & p, GFloat r) inline
Referenced by GWorld::Check(), and GRigid::DispShadow().
void GLand::List2Reset (void) inline
Referenced by GWorld::Move(), ResetRecVal(), and ResetVal().
int GLand::List2up (GVector & p, GFloat r) inline
Referenced by GWorld::Move(), ResetRecVal(), and ResetVal().
void GLand::List3Reset (void) inline
Referenced by GWorld::Move(), ResetRecVal(), and ResetVal().
int GLand::List3up (GVector & p, GFloat r) inline
Referenced by GWorld::Move(), ResetRecVal(), and ResetVal().
void GLand::Set () inline
void GLand::Set () inline
Referenced by LoadLand().
Member Data Documentation
unsigned long GLand::AttribTableSize
Referenced by LoadLand().
GLandFace * GLand::Face
Referenced by GRigid::CollisionCheck(), GRigid::DispShadow(), LoadLand(), and ~GLand().
int GLand::FaceCount
Referenced by Check(), GetY(), List2up(), List3Reset(), List3up(), and Set().
GFloat* GLand::HitD
Referenced by ~GLand().
int* GLand::HitList
Referenced by GRigid::CollisionCheck(), and ~GLand().
int GLand::HitListCount
Referenced by Check2(), and GRigid::CollisionCheck().
GVector* GLand::HitNormal
Referenced by ~GLand().
int* GLand::List1
Referenced by GRigid::DispShadow(), and ~GLand().
int GLand::List1Count
Referenced by Check(), Check2(), GRigid::DispShadow(), and List1up().
GVector GLand::List1P
float GLand::List1R
int* GLand::List2
Referenced by GRigid::DispShadow(), and ~GLand().
int GLand::List2Count
Referenced by GRigid::DispShadow(), GetY2(), List1up(), and List2up().
int* GLand::List3
Referenced by ~GLand().
int GLand::List3Count
Referenced by List2Reset(), List2up(), and List3up().
GLandVertex * GLand::Vertex
Referenced by LoadLand(), and ~GLand().
int GLand::VertexCount
Referenced by Set().
The documentation for this class was generated from the following files:
GLand.hpp
Land.h