RigidChips: microsoft directx 9.0 sdk (summer 2004)/Include/d3drmobj.h File Reference
d3drmobj.h File Reference
#include <objbase.h>
#include "d3drmdef.h"
#include "d3d.h"
Classes
struct _D3DRMPICKDESC
struct _D3DRMPICKDESC2
Macros
#define VIRTUAL
#define IUNKNOWN_METHODS(kind)
#define IDIRECT3DRMOBJECT_METHODS(kind)
#define WIN_TYPES(itype, ptype) typedef interface itype FAR *LP##ptype, FAR **LPLP##ptype
#define INTERFACE IDirect3DRMObject
#define INTERFACE IDirect3DRMObject2
#define INTERFACE IDirect3DRMVisual
#define INTERFACE IDirect3DRMDevice
#define INTERFACE IDirect3DRMDevice2
#define INTERFACE IDirect3DRMDevice3
#define INTERFACE IDirect3DRMViewport
#define INTERFACE IDirect3DRMViewport2
#define INTERFACE IDirect3DRMFrame
#define INTERFACE IDirect3DRMFrame2
#define INTERFACE IDirect3DRMFrame3
#define INTERFACE IDirect3DRMMesh
#define INTERFACE IDirect3DRMProgressiveMesh
#define INTERFACE IDirect3DRMShadow
#define INTERFACE IDirect3DRMShadow2
#define INTERFACE IDirect3DRMFace
#define INTERFACE IDirect3DRMFace2
#define INTERFACE IDirect3DRMMeshBuilder
#define INTERFACE IDirect3DRMMeshBuilder2
#define INTERFACE IDirect3DRMMeshBuilder3
#define INTERFACE IDirect3DRMLight
#define INTERFACE IDirect3DRMTexture
#define INTERFACE IDirect3DRMTexture2
#define INTERFACE IDirect3DRMTexture3
#define INTERFACE IDirect3DRMWrap
#define INTERFACE IDirect3DRMMaterial
#define INTERFACE IDirect3DRMMaterial2
#define INTERFACE IDirect3DRMAnimation
#define INTERFACE IDirect3DRMAnimation2
#define INTERFACE IDirect3DRMAnimationSet
#define INTERFACE IDirect3DRMAnimationSet2
#define INTERFACE IDirect3DRMUserVisual
#define INTERFACE IDirect3DRMArray
#define INTERFACE IDirect3DRMObjectArray
#define INTERFACE IDirect3DRMDeviceArray
#define INTERFACE IDirect3DRMFrameArray
#define INTERFACE IDirect3DRMViewportArray
#define INTERFACE IDirect3DRMVisualArray
#define INTERFACE IDirect3DRMAnimationArray
#define INTERFACE IDirect3DRMPickedArray
#define INTERFACE IDirect3DRMLightArray
#define INTERFACE IDirect3DRMFaceArray
#define INTERFACE IDirect3DRMPicked2Array
#define INTERFACE IDirect3DRMInterpolator
#define INTERFACE IDirect3DRMClippedVisual
Typedefs
typedef void(__cdecl * D3DRMOBJECTCALLBACK) (LPDIRECT3DRMOBJECT obj, LPVOID arg)
typedef void(__cdecl * D3DRMFRAMEMOVECALLBACK) (LPDIRECT3DRMFRAME obj, LPVOID arg, D3DVALUE delta)
typedef void(__cdecl * D3DRMFRAME3MOVECALLBACK) (LPDIRECT3DRMFRAME3 obj, LPVOID arg, D3DVALUE delta)
typedef void(__cdecl * D3DRMUPDATECALLBACK) (LPDIRECT3DRMDEVICE obj, LPVOID arg, int, LPD3DRECT)
typedef void(__cdecl * D3DRMDEVICE3UPDATECALLBACK) (LPDIRECT3DRMDEVICE3 obj, LPVOID arg, int, LPD3DRECT)
typedef LPVOID arg
typedef LPVOID D3DRMUSERVISUALREASON reason
typedef LPVOID D3DRMUSERVISUALREASON LPDIRECT3DRMDEVICE dev
typedef LPVOID D3DRMUSERVISUALREASON LPDIRECT3DRMDEVICE LPDIRECT3DRMVIEWPORT view
typedef void LPDIRECT3DRMTEXTURE *typedef HRESULT(__cdecl *D3DRMLOADTEXTURE3CALLBACK) (char *tex_name
typedef void LPDIRECT3DRMTEXTURE *typedef void LPDIRECT3DRMTEXTURE3 *typedef void(__cdecl *D3DRMLOADCALLBACK) (LPDIRECT3DRMOBJECT object
typedef void LPDIRECT3DRMTEXTURE *typedef void LPDIRECT3DRMTEXTURE3 *typedef REFIID objectguid
typedef LPVOID pArg
typedef LPVOID LPDIRECTDRAWSURFACE pDDSSrc
typedef LPVOID LPDIRECTDRAWSURFACE LPDIRECTDRAWSURFACE pDDSDst
typedef LPVOID DWORD dwFlags
typedef LPVOID DWORD DWORD dwcRects
typedef LPVOID DWORD DWORD LPRECT pRects
typedef struct _D3DRMPICKDESC D3DRMPICKDESC
typedef struct _D3DRMPICKDESC * LPD3DRMPICKDESC
typedef struct _D3DRMPICKDESC2 D3DRMPICKDESC2
typedef struct _D3DRMPICKDESC2 * LPD3DRMPICKDESC2
Functions
WIN_TYPES (IDirect3DRMObject, DIRECT3DRMOBJECT)
WIN_TYPES (IDirect3DRMObject2, DIRECT3DRMOBJECT2)
WIN_TYPES (IDirect3DRMDevice, DIRECT3DRMDEVICE)
WIN_TYPES (IDirect3DRMDevice2, DIRECT3DRMDEVICE2)
WIN_TYPES (IDirect3DRMDevice3, DIRECT3DRMDEVICE3)
WIN_TYPES (IDirect3DRMViewport, DIRECT3DRMVIEWPORT)
WIN_TYPES (IDirect3DRMViewport2, DIRECT3DRMVIEWPORT2)
WIN_TYPES (IDirect3DRMFrame, DIRECT3DRMFRAME)
WIN_TYPES (IDirect3DRMFrame2, DIRECT3DRMFRAME2)
WIN_TYPES (IDirect3DRMFrame3, DIRECT3DRMFRAME3)
WIN_TYPES (IDirect3DRMVisual, DIRECT3DRMVISUAL)
WIN_TYPES (IDirect3DRMMesh, DIRECT3DRMMESH)
WIN_TYPES (IDirect3DRMMeshBuilder, DIRECT3DRMMESHBUILDER)
WIN_TYPES (IDirect3DRMMeshBuilder2, DIRECT3DRMMESHBUILDER2)
WIN_TYPES (IDirect3DRMMeshBuilder3, DIRECT3DRMMESHBUILDER3)
WIN_TYPES (IDirect3DRMFace, DIRECT3DRMFACE)
WIN_TYPES (IDirect3DRMFace2, DIRECT3DRMFACE2)
WIN_TYPES (IDirect3DRMLight, DIRECT3DRMLIGHT)
WIN_TYPES (IDirect3DRMTexture, DIRECT3DRMTEXTURE)
WIN_TYPES (IDirect3DRMTexture2, DIRECT3DRMTEXTURE2)
WIN_TYPES (IDirect3DRMTexture3, DIRECT3DRMTEXTURE3)
WIN_TYPES (IDirect3DRMWrap, DIRECT3DRMWRAP)
WIN_TYPES (IDirect3DRMMaterial, DIRECT3DRMMATERIAL)
WIN_TYPES (IDirect3DRMMaterial2, DIRECT3DRMMATERIAL2)
WIN_TYPES (IDirect3DRMInterpolator, DIRECT3DRMINTERPOLATOR)
WIN_TYPES (IDirect3DRMAnimation, DIRECT3DRMANIMATION)
WIN_TYPES (IDirect3DRMAnimation2, DIRECT3DRMANIMATION2)
WIN_TYPES (IDirect3DRMAnimationSet, DIRECT3DRMANIMATIONSET)
WIN_TYPES (IDirect3DRMAnimationSet2, DIRECT3DRMANIMATIONSET2)
WIN_TYPES (IDirect3DRMUserVisual, DIRECT3DRMUSERVISUAL)
WIN_TYPES (IDirect3DRMShadow, DIRECT3DRMSHADOW)
WIN_TYPES (IDirect3DRMShadow2, DIRECT3DRMSHADOW2)
WIN_TYPES (IDirect3DRMArray, DIRECT3DRMARRAY)
WIN_TYPES (IDirect3DRMObjectArray, DIRECT3DRMOBJECTARRAY)
WIN_TYPES (IDirect3DRMDeviceArray, DIRECT3DRMDEVICEARRAY)
WIN_TYPES (IDirect3DRMFaceArray, DIRECT3DRMFACEARRAY)
WIN_TYPES (IDirect3DRMViewportArray, DIRECT3DRMVIEWPORTARRAY)
WIN_TYPES (IDirect3DRMFrameArray, DIRECT3DRMFRAMEARRAY)
WIN_TYPES (IDirect3DRMAnimationArray, DIRECT3DRMANIMATIONARRAY)
WIN_TYPES (IDirect3DRMVisualArray, DIRECT3DRMVISUALARRAY)
WIN_TYPES (IDirect3DRMPickedArray, DIRECT3DRMPICKEDARRAY)
WIN_TYPES (IDirect3DRMPicked2Array, DIRECT3DRMPICKED2ARRAY)
WIN_TYPES (IDirect3DRMLightArray, DIRECT3DRMLIGHTARRAY)
WIN_TYPES (IDirect3DRMProgressiveMesh, DIRECT3DRMPROGRESSIVEMESH)
WIN_TYPES (IDirect3DRMClippedVisual, DIRECT3DRMCLIPPEDVISUAL)
DEFINE_GUID (CLSID_CDirect3DRMDevice, 0x4fa3568e, 0x623f, 0x11cf, 0xac, 0x4a, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMViewport, 0x4fa3568f, 0x623f, 0x11cf, 0xac, 0x4a, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMFrame, 0x4fa35690, 0x623f, 0x11cf, 0xac, 0x4a, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMMesh, 0x4fa35691, 0x623f, 0x11cf, 0xac, 0x4a, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMMeshBuilder, 0x4fa35692, 0x623f, 0x11cf, 0xac, 0x4a, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMFace, 0x4fa35693, 0x623f, 0x11cf, 0xac, 0x4a, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMLight, 0x4fa35694, 0x623f, 0x11cf, 0xac, 0x4a, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMTexture, 0x4fa35695, 0x623f, 0x11cf, 0xac, 0x4a, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMWrap, 0x4fa35696, 0x623f, 0x11cf, 0xac, 0x4a, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMMaterial, 0x4fa35697, 0x623f, 0x11cf, 0xac, 0x4a, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMAnimation, 0x4fa35698, 0x623f, 0x11cf, 0xac, 0x4a, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMAnimationSet, 0x4fa35699, 0x623f, 0x11cf, 0xac, 0x4a, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMUserVisual, 0x4fa3569a, 0x623f, 0x11cf, 0xac, 0x4a, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMShadow, 0x4fa3569b, 0x623f, 0x11cf, 0xac, 0x4a, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMViewportInterpolator, 0xde9eaa1, 0x3b84, 0x11d0, 0x9b, 0x6d, 0x0, 0x0, 0xc0, 0x78, 0x1b, 0xc3)
DEFINE_GUID (CLSID_CDirect3DRMFrameInterpolator, 0xde9eaa2, 0x3b84, 0x11d0, 0x9b, 0x6d, 0x0, 0x0, 0xc0, 0x78, 0x1b, 0xc3)
DEFINE_GUID (CLSID_CDirect3DRMMeshInterpolator, 0xde9eaa3, 0x3b84, 0x11d0, 0x9b, 0x6d, 0x0, 0x0, 0xc0, 0x78, 0x1b, 0xc3)
DEFINE_GUID (CLSID_CDirect3DRMLightInterpolator, 0xde9eaa6, 0x3b84, 0x11d0, 0x9b, 0x6d, 0x0, 0x0, 0xc0, 0x78, 0x1b, 0xc3)
DEFINE_GUID (CLSID_CDirect3DRMMaterialInterpolator, 0xde9eaa7, 0x3b84, 0x11d0, 0x9b, 0x6d, 0x0, 0x0, 0xc0, 0x78, 0x1b, 0xc3)
DEFINE_GUID (CLSID_CDirect3DRMTextureInterpolator, 0xde9eaa8, 0x3b84, 0x11d0, 0x9b, 0x6d, 0x0, 0x0, 0xc0, 0x78, 0x1b, 0xc3)
DEFINE_GUID (CLSID_CDirect3DRMProgressiveMesh, 0x4516ec40, 0x8f20, 0x11d0, 0x9b, 0x6d, 0x00, 0x00, 0xc0, 0x78, 0x1b, 0xc3)
DEFINE_GUID (CLSID_CDirect3DRMClippedVisual, 0x5434e72d, 0x6d66, 0x11d1, 0xbb, 0xb, 0x0, 0x0, 0xf8, 0x75, 0x86, 0x5a)
DEFINE_GUID (IID_IDirect3DRMObject, 0xeb16cb00, 0xd271, 0x11ce, 0xac, 0x48, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMObject2, 0x4516ec7c, 0x8f20, 0x11d0, 0x9b, 0x6d, 0x00, 0x00, 0xc0, 0x78, 0x1b, 0xc3)
DEFINE_GUID (IID_IDirect3DRMDevice, 0xe9e19280, 0x6e05, 0x11cf, 0xac, 0x4a, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMDevice2, 0x4516ec78, 0x8f20, 0x11d0, 0x9b, 0x6d, 0x00, 0x00, 0xc0, 0x78, 0x1b, 0xc3)
DEFINE_GUID (IID_IDirect3DRMDevice3, 0x549f498b, 0xbfeb, 0x11d1, 0x8e, 0xd8, 0x0, 0xa0, 0xc9, 0x67, 0xa4, 0x82)
DEFINE_GUID (IID_IDirect3DRMViewport, 0xeb16cb02, 0xd271, 0x11ce, 0xac, 0x48, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMViewport2, 0x4a1b1be6, 0xbfed, 0x11d1, 0x8e, 0xd8, 0x0, 0xa0, 0xc9, 0x67, 0xa4, 0x82)
DEFINE_GUID (IID_IDirect3DRMFrame, 0xeb16cb03, 0xd271, 0x11ce, 0xac, 0x48, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMFrame2, 0xc3dfbd60, 0x3988, 0x11d0, 0x9e, 0xc2, 0x0, 0x0, 0xc0, 0x29, 0x1a, 0xc3)
DEFINE_GUID (IID_IDirect3DRMFrame3, 0xff6b7f70, 0xa40e, 0x11d1, 0x91, 0xf9, 0x0, 0x0, 0xf8, 0x75, 0x8e, 0x66)
DEFINE_GUID (IID_IDirect3DRMVisual, 0xeb16cb04, 0xd271, 0x11ce, 0xac, 0x48, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMMesh, 0xa3a80d01, 0x6e12, 0x11cf, 0xac, 0x4a, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMMeshBuilder, 0xa3a80d02, 0x6e12, 0x11cf, 0xac, 0x4a, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMMeshBuilder2, 0x4516ec77, 0x8f20, 0x11d0, 0x9b, 0x6d, 0x0, 0x0, 0xc0, 0x78, 0x1b, 0xc3)
DEFINE_GUID (IID_IDirect3DRMMeshBuilder3, 0x4516ec82, 0x8f20, 0x11d0, 0x9b, 0x6d, 0x00, 0x00, 0xc0, 0x78, 0x1b, 0xc3)
DEFINE_GUID (IID_IDirect3DRMFace, 0xeb16cb07, 0xd271, 0x11ce, 0xac, 0x48, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMFace2, 0x4516ec81, 0x8f20, 0x11d0, 0x9b, 0x6d, 0x00, 0x00, 0xc0, 0x78, 0x1b, 0xc3)
DEFINE_GUID (IID_IDirect3DRMLight, 0xeb16cb08, 0xd271, 0x11ce, 0xac, 0x48, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMTexture, 0xeb16cb09, 0xd271, 0x11ce, 0xac, 0x48, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMTexture2, 0x120f30c0, 0x1629, 0x11d0, 0x94, 0x1c, 0x0, 0x80, 0xc8, 0xc, 0xfa, 0x7b)
DEFINE_GUID (IID_IDirect3DRMTexture3, 0xff6b7f73, 0xa40e, 0x11d1, 0x91, 0xf9, 0x0, 0x0, 0xf8, 0x75, 0x8e, 0x66)
DEFINE_GUID (IID_IDirect3DRMWrap, 0xeb16cb0a, 0xd271, 0x11ce, 0xac, 0x48, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMMaterial, 0xeb16cb0b, 0xd271, 0x11ce, 0xac, 0x48, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMMaterial2, 0xff6b7f75, 0xa40e, 0x11d1, 0x91, 0xf9, 0x0, 0x0, 0xf8, 0x75, 0x8e, 0x66)
DEFINE_GUID (IID_IDirect3DRMAnimation, 0xeb16cb0d, 0xd271, 0x11ce, 0xac, 0x48, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMAnimation2, 0xff6b7f77, 0xa40e, 0x11d1, 0x91, 0xf9, 0x0, 0x0, 0xf8, 0x75, 0x8e, 0x66)
DEFINE_GUID (IID_IDirect3DRMAnimationSet, 0xeb16cb0e, 0xd271, 0x11ce, 0xac, 0x48, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMAnimationSet2, 0xff6b7f79, 0xa40e, 0x11d1, 0x91, 0xf9, 0x0, 0x0, 0xf8, 0x75, 0x8e, 0x66)
DEFINE_GUID (IID_IDirect3DRMObjectArray, 0x242f6bc2, 0x3849, 0x11d0, 0x9b, 0x6d, 0x0, 0x0, 0xc0, 0x78, 0x1b, 0xc3)
DEFINE_GUID (IID_IDirect3DRMDeviceArray, 0xeb16cb10, 0xd271, 0x11ce, 0xac, 0x48, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMViewportArray, 0xeb16cb11, 0xd271, 0x11ce, 0xac, 0x48, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMFrameArray, 0xeb16cb12, 0xd271, 0x11ce, 0xac, 0x48, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMVisualArray, 0xeb16cb13, 0xd271, 0x11ce, 0xac, 0x48, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMLightArray, 0xeb16cb14, 0xd271, 0x11ce, 0xac, 0x48, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMPickedArray, 0xeb16cb16, 0xd271, 0x11ce, 0xac, 0x48, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMFaceArray, 0xeb16cb17, 0xd271, 0x11ce, 0xac, 0x48, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMAnimationArray, 0xd5f1cae0, 0x4bd7, 0x11d1, 0xb9, 0x74, 0x0, 0x60, 0x8, 0x3e, 0x45, 0xf3)
DEFINE_GUID (IID_IDirect3DRMUserVisual, 0x59163de0, 0x6d43, 0x11cf, 0xac, 0x4a, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMShadow, 0xaf359780, 0x6ba3, 0x11cf, 0xac, 0x4a, 0x0, 0x0, 0xc0, 0x38, 0x25, 0xa1)
DEFINE_GUID (IID_IDirect3DRMShadow2, 0x86b44e25, 0x9c82, 0x11d1, 0xbb, 0xb, 0x0, 0xa0, 0xc9, 0x81, 0xa0, 0xa6)
DEFINE_GUID (IID_IDirect3DRMInterpolator, 0x242f6bc1, 0x3849, 0x11d0, 0x9b, 0x6d, 0x0, 0x0, 0xc0, 0x78, 0x1b, 0xc3)
DEFINE_GUID (IID_IDirect3DRMProgressiveMesh, 0x4516ec79, 0x8f20, 0x11d0, 0x9b, 0x6d, 0x0, 0x0, 0xc0, 0x78, 0x1b, 0xc3)
DEFINE_GUID (IID_IDirect3DRMPicked2Array, 0x4516ec7b, 0x8f20, 0x11d0, 0x9b, 0x6d, 0x0, 0x0, 0xc0, 0x78, 0x1b, 0xc3)
DEFINE_GUID (IID_IDirect3DRMClippedVisual, 0x5434e733, 0x6d66, 0x11d1, 0xbb, 0xb, 0x0, 0x0, 0xf8, 0x75, 0x86, 0x5a)
typedef int (__cdecl *D3DRMUSERVISUALCALLBACK)(LPDIRECT3DRMUSERVISUAL obj
typedef HRESULT (__cdecl *D3DRMLOADTEXTURECALLBACK)(char *tex_name
DECLARE_INTERFACE_ (IDirect3DRMObject, IUnknown)
DECLARE_INTERFACE_ (IDirect3DRMObject2, IUnknown)
DECLARE_INTERFACE_ (IDirect3DRMVisual, IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMDevice, IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMDevice2, IDirect3DRMDevice)
DECLARE_INTERFACE_ (IDirect3DRMDevice3, IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMViewport, IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMViewport2, IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMFrame, IDirect3DRMVisual)
DECLARE_INTERFACE_ (IDirect3DRMFrame2, IDirect3DRMFrame)
DECLARE_INTERFACE_ (IDirect3DRMFrame3, IDirect3DRMVisual)
DECLARE_INTERFACE_ (IDirect3DRMMesh, IDirect3DRMVisual)
DECLARE_INTERFACE_ (IDirect3DRMProgressiveMesh, IDirect3DRMVisual)
DECLARE_INTERFACE_ (IDirect3DRMShadow, IDirect3DRMVisual)
DECLARE_INTERFACE_ (IDirect3DRMShadow2, IDirect3DRMVisual)
DECLARE_INTERFACE_ (IDirect3DRMFace, IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMFace2, IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMMeshBuilder, IDirect3DRMVisual)
DECLARE_INTERFACE_ (IDirect3DRMMeshBuilder2, IDirect3DRMMeshBuilder)
DECLARE_INTERFACE_ (IDirect3DRMMeshBuilder3, IDirect3DRMVisual)
DECLARE_INTERFACE_ (IDirect3DRMLight, IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMTexture, IDirect3DRMVisual)
DECLARE_INTERFACE_ (IDirect3DRMTexture2, IDirect3DRMTexture)
DECLARE_INTERFACE_ (IDirect3DRMTexture3, IDirect3DRMVisual)
DECLARE_INTERFACE_ (IDirect3DRMWrap, IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMMaterial, IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMMaterial2, IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMAnimation, IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMAnimation2, IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMAnimationSet, IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMAnimationSet2, IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMUserVisual, IDirect3DRMVisual)
DECLARE_INTERFACE_ (IDirect3DRMArray, IUnknown)
DECLARE_INTERFACE_ (IDirect3DRMObjectArray, IDirect3DRMArray)
DECLARE_INTERFACE_ (IDirect3DRMDeviceArray, IDirect3DRMArray)
DECLARE_INTERFACE_ (IDirect3DRMFrameArray, IDirect3DRMArray)
DECLARE_INTERFACE_ (IDirect3DRMViewportArray, IDirect3DRMArray)
DECLARE_INTERFACE_ (IDirect3DRMVisualArray, IDirect3DRMArray)
DECLARE_INTERFACE_ (IDirect3DRMAnimationArray, IDirect3DRMArray)
DECLARE_INTERFACE_ (IDirect3DRMPickedArray, IDirect3DRMArray)
DECLARE_INTERFACE_ (IDirect3DRMLightArray, IDirect3DRMArray)
DECLARE_INTERFACE_ (IDirect3DRMFaceArray, IDirect3DRMArray)
DECLARE_INTERFACE_ (IDirect3DRMPicked2Array, IDirect3DRMArray)
DECLARE_INTERFACE_ (IDirect3DRMInterpolator, IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMClippedVisual, IDirect3DRMVisual)
Macro Definition Documentation
#define IDIRECT3DRMOBJECT_METHODS (kind)
Value:
STDMETHOD(Clone)                    (THIS_ LPUNKNOWN pUnkOuter, REFIID riid, LPVOID *ppvObj) kind; \
    STDMETHOD(AddDestroyCallback)       (THIS_ D3DRMOBJECTCALLBACK, LPVOID argument) kind; \
    STDMETHOD(DeleteDestroyCallback)    (THIS_ D3DRMOBJECTCALLBACK, LPVOID argument) kind; \
    STDMETHOD(SetAppData)               (THIS_ DWORD data) kind; \
    STDMETHOD_(DWORD, GetAppData)       (THIS) kind; \
    STDMETHOD(SetName)                  (THIS_ LPCSTR) kind; \
    STDMETHOD(GetName)                  (THIS_ LPDWORD lpdwSize, LPSTR lpName) kind; \
    STDMETHOD(GetClassName)             (THIS_ LPDWORD lpdwSize, LPSTR lpName) kind
Referenced by DECLARE_INTERFACE_().
#define INTERFACE IDirect3DRMObject
#define INTERFACE IDirect3DRMObject2
#define INTERFACE IDirect3DRMVisual
#define INTERFACE IDirect3DRMDevice
#define INTERFACE IDirect3DRMDevice2
#define INTERFACE IDirect3DRMDevice3
#define INTERFACE IDirect3DRMViewport
#define INTERFACE IDirect3DRMViewport2
#define INTERFACE IDirect3DRMFrame
#define INTERFACE IDirect3DRMFrame2
#define INTERFACE IDirect3DRMFrame3
#define INTERFACE IDirect3DRMMesh
#define INTERFACE IDirect3DRMProgressiveMesh
#define INTERFACE IDirect3DRMShadow
#define INTERFACE IDirect3DRMShadow2
#define INTERFACE IDirect3DRMFace
#define INTERFACE IDirect3DRMFace2
#define INTERFACE IDirect3DRMMeshBuilder
#define INTERFACE IDirect3DRMMeshBuilder2
#define INTERFACE IDirect3DRMMeshBuilder3
#define INTERFACE IDirect3DRMLight
#define INTERFACE IDirect3DRMTexture
#define INTERFACE IDirect3DRMTexture2
#define INTERFACE IDirect3DRMTexture3
#define INTERFACE IDirect3DRMWrap
#define INTERFACE IDirect3DRMMaterial
#define INTERFACE IDirect3DRMMaterial2
#define INTERFACE IDirect3DRMAnimation
#define INTERFACE IDirect3DRMAnimation2
#define INTERFACE IDirect3DRMAnimationSet
#define INTERFACE IDirect3DRMAnimationSet2
#define INTERFACE IDirect3DRMUserVisual
#define INTERFACE IDirect3DRMArray
#define INTERFACE IDirect3DRMObjectArray
#define INTERFACE IDirect3DRMDeviceArray
#define INTERFACE IDirect3DRMFrameArray
#define INTERFACE IDirect3DRMViewportArray
#define INTERFACE IDirect3DRMVisualArray
#define INTERFACE IDirect3DRMAnimationArray
#define INTERFACE IDirect3DRMPickedArray
#define INTERFACE IDirect3DRMLightArray
#define INTERFACE IDirect3DRMFaceArray
#define INTERFACE IDirect3DRMPicked2Array
#define INTERFACE IDirect3DRMInterpolator
#define INTERFACE IDirect3DRMClippedVisual
#define IUNKNOWN_METHODS (kind)
Value:
STDMETHOD(QueryInterface)           (THIS_ REFIID riid, LPVOID *ppvObj) kind; \
    STDMETHOD_(ULONG, AddRef)           (THIS) kind; \
    STDMETHOD_(ULONG, Release)          (THIS) kind
Referenced by DECLARE_INTERFACE_().
#define VIRTUAL
#define WIN_TYPES (itype, ptype) typedef interface itype FAR *LP##ptype, FAR **LPLP##ptype
Typedef Documentation
typedef void LPDIRECT3DRMTEXTURE *typedef void LPDIRECT3DRMTEXTURE3 *typedef REFIID LPVOID arg
typedef void(__cdecl * D3DRMDEVICE3UPDATECALLBACK) (LPDIRECT3DRMDEVICE3 obj, LPVOID arg, int, LPD3DRECT)
typedef void(__cdecl * D3DRMFRAME3MOVECALLBACK) (LPDIRECT3DRMFRAME3 obj, LPVOID arg, D3DVALUE delta)
typedef void(__cdecl * D3DRMFRAMEMOVECALLBACK) (LPDIRECT3DRMFRAME obj, LPVOID arg, D3DVALUE delta)
typedef void(__cdecl * D3DRMOBJECTCALLBACK) (LPDIRECT3DRMOBJECT obj, LPVOID arg)
typedef struct _D3DRMPICKDESC D3DRMPICKDESC
typedef struct _D3DRMPICKDESC2 D3DRMPICKDESC2
typedef void(__cdecl * D3DRMUPDATECALLBACK) (LPDIRECT3DRMDEVICE obj, LPVOID arg, int, LPD3DRECT)
typedef LPVOID D3DRMUSERVISUALREASON LPDIRECT3DRMDEVICE dev
typedef LPVOID DWORD DWORD dwcRects
typedef LPVOID DWORD dwFlags
typedef HRESULT
typedef struct _D3DRMPICKDESC * LPD3DRMPICKDESC
typedef struct _D3DRMPICKDESC2 * LPD3DRMPICKDESC2
typedef void LPDIRECT3DRMTEXTURE* typedef void LPDIRECT3DRMTEXTURE3* typedef REFIID objectguid
typedef LPVOID pArg
typedef LPVOID LPDIRECTDRAWSURFACE LPDIRECTDRAWSURFACE pDDSDst
typedef LPVOID LPDIRECTDRAWSURFACE pDDSSrc
typedef LPVOID DWORD DWORD LPRECT pRects
typedef LPVOID D3DRMUSERVISUALREASON reason
typedef LPVOID D3DRMUSERVISUALREASON LPDIRECT3DRMDEVICE LPDIRECT3DRMVIEWPORT view
typedef void (__cdecl * D3DRMLOADCALLBACK)
Function Documentation
DECLARE_INTERFACE_ (IDirect3DRMObject , IUnknown)
DECLARE_INTERFACE_ (IDirect3DRMObject2 , IUnknown)
DECLARE_INTERFACE_ (IDirect3DRMVisual , IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMDevice , IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMDevice2 , IDirect3DRMDevice)
DECLARE_INTERFACE_ (IDirect3DRMDevice3 , IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMViewport , IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMViewport2 , IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMFrame , IDirect3DRMVisual)
DECLARE_INTERFACE_ (IDirect3DRMFrame2 , IDirect3DRMFrame)
DECLARE_INTERFACE_ (IDirect3DRMFrame3 , IDirect3DRMVisual)
DECLARE_INTERFACE_ (IDirect3DRMMesh , IDirect3DRMVisual)
DECLARE_INTERFACE_ (IDirect3DRMProgressiveMesh , IDirect3DRMVisual)
DECLARE_INTERFACE_ (IDirect3DRMShadow , IDirect3DRMVisual)
DECLARE_INTERFACE_ (IDirect3DRMShadow2 , IDirect3DRMVisual)
DECLARE_INTERFACE_ (IDirect3DRMFace , IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMFace2 , IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMMeshBuilder , IDirect3DRMVisual)
DECLARE_INTERFACE_ (IDirect3DRMMeshBuilder2 , IDirect3DRMMeshBuilder)
DECLARE_INTERFACE_ (IDirect3DRMMeshBuilder3 , IDirect3DRMVisual)
DECLARE_INTERFACE_ (IDirect3DRMLight , IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMTexture , IDirect3DRMVisual)
DECLARE_INTERFACE_ (IDirect3DRMTexture2 , IDirect3DRMTexture)
DECLARE_INTERFACE_ (IDirect3DRMTexture3 , IDirect3DRMVisual)
DECLARE_INTERFACE_ (IDirect3DRMWrap , IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMMaterial , IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMMaterial2 , IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMAnimation , IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMAnimation2 , IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMAnimationSet , IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMAnimationSet2 , IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMUserVisual , IDirect3DRMVisual)
DECLARE_INTERFACE_ (IDirect3DRMArray , IUnknown)
DECLARE_INTERFACE_ (IDirect3DRMObjectArray , IDirect3DRMArray)
DECLARE_INTERFACE_ (IDirect3DRMDeviceArray , IDirect3DRMArray)
DECLARE_INTERFACE_ (IDirect3DRMFrameArray , IDirect3DRMArray)
DECLARE_INTERFACE_ (IDirect3DRMViewportArray , IDirect3DRMArray)
DECLARE_INTERFACE_ (IDirect3DRMVisualArray , IDirect3DRMArray)
DECLARE_INTERFACE_ (IDirect3DRMAnimationArray , IDirect3DRMArray)
DECLARE_INTERFACE_ (IDirect3DRMPickedArray , IDirect3DRMArray)
DECLARE_INTERFACE_ (IDirect3DRMLightArray , IDirect3DRMArray)
DECLARE_INTERFACE_ (IDirect3DRMFaceArray , IDirect3DRMArray)
DECLARE_INTERFACE_ (IDirect3DRMPicked2Array , IDirect3DRMArray)
DECLARE_INTERFACE_ (IDirect3DRMInterpolator , IDirect3DRMObject)
DECLARE_INTERFACE_ (IDirect3DRMClippedVisual , IDirect3DRMVisual)
DEFINE_GUID (CLSID_CDirect3DRMDevice , 0x4fa3568e , 0x623f , 0x11cf , 0xac , 0x4a , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMViewport , 0x4fa3568f , 0x623f , 0x11cf , 0xac , 0x4a , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMFrame , 0x4fa35690 , 0x623f , 0x11cf , 0xac , 0x4a , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMMesh , 0x4fa35691 , 0x623f , 0x11cf , 0xac , 0x4a , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMMeshBuilder , 0x4fa35692 , 0x623f , 0x11cf , 0xac , 0x4a , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMFace , 0x4fa35693 , 0x623f , 0x11cf , 0xac , 0x4a , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMLight , 0x4fa35694 , 0x623f , 0x11cf , 0xac , 0x4a , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMTexture , 0x4fa35695 , 0x623f , 0x11cf , 0xac , 0x4a , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMWrap , 0x4fa35696 , 0x623f , 0x11cf , 0xac , 0x4a , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMMaterial , 0x4fa35697 , 0x623f , 0x11cf , 0xac , 0x4a , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMAnimation , 0x4fa35698 , 0x623f , 0x11cf , 0xac , 0x4a , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMAnimationSet , 0x4fa35699 , 0x623f , 0x11cf , 0xac , 0x4a , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMUserVisual , 0x4fa3569a , 0x623f , 0x11cf , 0xac , 0x4a , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMShadow , 0x4fa3569b , 0x623f , 0x11cf , 0xac , 0x4a , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (CLSID_CDirect3DRMViewportInterpolator , 0xde9eaa1 , 0x3b84 , 0x11d0 , 0x9b , 0x6d , 0x0 , 0x0 , 0xc0 , 0x78 , 0x1b , 0xc3)
DEFINE_GUID (CLSID_CDirect3DRMFrameInterpolator , 0xde9eaa2 , 0x3b84 , 0x11d0 , 0x9b , 0x6d , 0x0 , 0x0 , 0xc0 , 0x78 , 0x1b , 0xc3)
DEFINE_GUID (CLSID_CDirect3DRMMeshInterpolator , 0xde9eaa3 , 0x3b84 , 0x11d0 , 0x9b , 0x6d , 0x0 , 0x0 , 0xc0 , 0x78 , 0x1b , 0xc3)
DEFINE_GUID (CLSID_CDirect3DRMLightInterpolator , 0xde9eaa6 , 0x3b84 , 0x11d0 , 0x9b , 0x6d , 0x0 , 0x0 , 0xc0 , 0x78 , 0x1b , 0xc3)
DEFINE_GUID (CLSID_CDirect3DRMMaterialInterpolator , 0xde9eaa7 , 0x3b84 , 0x11d0 , 0x9b , 0x6d , 0x0 , 0x0 , 0xc0 , 0x78 , 0x1b , 0xc3)
DEFINE_GUID (CLSID_CDirect3DRMTextureInterpolator , 0xde9eaa8 , 0x3b84 , 0x11d0 , 0x9b , 0x6d , 0x0 , 0x0 , 0xc0 , 0x78 , 0x1b , 0xc3)
DEFINE_GUID (CLSID_CDirect3DRMProgressiveMesh , 0x4516ec40 , 0x8f20 , 0x11d0 , 0x9b , 0x6d , 0x00 , 0x00 , 0xc0 , 0x78 , 0x1b , 0xc3)
DEFINE_GUID (CLSID_CDirect3DRMClippedVisual , 0x5434e72d , 0x6d66 , 0x11d1 , 0xbb , 0xb , 0x0 , 0x0 , 0xf8 , 0x75 , 0x86 , 0x5a)
DEFINE_GUID (IID_IDirect3DRMObject , 0xeb16cb00 , 0xd271 , 0x11ce , 0xac , 0x48 , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMObject2 , 0x4516ec7c , 0x8f20 , 0x11d0 , 0x9b , 0x6d , 0x00 , 0x00 , 0xc0 , 0x78 , 0x1b , 0xc3)
DEFINE_GUID (IID_IDirect3DRMDevice , 0xe9e19280 , 0x6e05 , 0x11cf , 0xac , 0x4a , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMDevice2 , 0x4516ec78 , 0x8f20 , 0x11d0 , 0x9b , 0x6d , 0x00 , 0x00 , 0xc0 , 0x78 , 0x1b , 0xc3)
DEFINE_GUID (IID_IDirect3DRMDevice3 , 0x549f498b , 0xbfeb , 0x11d1 , 0x8e , 0xd8 , 0x0 , 0xa0 , 0xc9 , 0x67 , 0xa4 , 0x82)
DEFINE_GUID (IID_IDirect3DRMViewport , 0xeb16cb02 , 0xd271 , 0x11ce , 0xac , 0x48 , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMViewport2 , 0x4a1b1be6 , 0xbfed , 0x11d1 , 0x8e , 0xd8 , 0x0 , 0xa0 , 0xc9 , 0x67 , 0xa4 , 0x82)
DEFINE_GUID (IID_IDirect3DRMFrame , 0xeb16cb03 , 0xd271 , 0x11ce , 0xac , 0x48 , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMFrame2 , 0xc3dfbd60 , 0x3988 , 0x11d0 , 0x9e , 0xc2 , 0x0 , 0x0 , 0xc0 , 0x29 , 0x1a , 0xc3)
DEFINE_GUID (IID_IDirect3DRMFrame3 , 0xff6b7f70 , 0xa40e , 0x11d1 , 0x91 , 0xf9 , 0x0 , 0x0 , 0xf8 , 0x75 , 0x8e , 0x66)
DEFINE_GUID (IID_IDirect3DRMVisual , 0xeb16cb04 , 0xd271 , 0x11ce , 0xac , 0x48 , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMMesh , 0xa3a80d01 , 0x6e12 , 0x11cf , 0xac , 0x4a , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMMeshBuilder , 0xa3a80d02 , 0x6e12 , 0x11cf , 0xac , 0x4a , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMMeshBuilder2 , 0x4516ec77 , 0x8f20 , 0x11d0 , 0x9b , 0x6d , 0x0 , 0x0 , 0xc0 , 0x78 , 0x1b , 0xc3)
DEFINE_GUID (IID_IDirect3DRMMeshBuilder3 , 0x4516ec82 , 0x8f20 , 0x11d0 , 0x9b , 0x6d , 0x00 , 0x00 , 0xc0 , 0x78 , 0x1b , 0xc3)
DEFINE_GUID (IID_IDirect3DRMFace , 0xeb16cb07 , 0xd271 , 0x11ce , 0xac , 0x48 , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMFace2 , 0x4516ec81 , 0x8f20 , 0x11d0 , 0x9b , 0x6d , 0x00 , 0x00 , 0xc0 , 0x78 , 0x1b , 0xc3)
DEFINE_GUID (IID_IDirect3DRMLight , 0xeb16cb08 , 0xd271 , 0x11ce , 0xac , 0x48 , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMTexture , 0xeb16cb09 , 0xd271 , 0x11ce , 0xac , 0x48 , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMTexture2 , 0x120f30c0 , 0x1629 , 0x11d0 , 0x94 , 0x1c , 0x0 , 0x80 , 0xc8 , 0xc , 0xfa , 0x7b)
DEFINE_GUID (IID_IDirect3DRMTexture3 , 0xff6b7f73 , 0xa40e , 0x11d1 , 0x91 , 0xf9 , 0x0 , 0x0 , 0xf8 , 0x75 , 0x8e , 0x66)
DEFINE_GUID (IID_IDirect3DRMWrap , 0xeb16cb0a , 0xd271 , 0x11ce , 0xac , 0x48 , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMMaterial , 0xeb16cb0b , 0xd271 , 0x11ce , 0xac , 0x48 , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMMaterial2 , 0xff6b7f75 , 0xa40e , 0x11d1 , 0x91 , 0xf9 , 0x0 , 0x0 , 0xf8 , 0x75 , 0x8e , 0x66)
DEFINE_GUID (IID_IDirect3DRMAnimation , 0xeb16cb0d , 0xd271 , 0x11ce , 0xac , 0x48 , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMAnimation2 , 0xff6b7f77 , 0xa40e , 0x11d1 , 0x91 , 0xf9 , 0x0 , 0x0 , 0xf8 , 0x75 , 0x8e , 0x66)
DEFINE_GUID (IID_IDirect3DRMAnimationSet , 0xeb16cb0e , 0xd271 , 0x11ce , 0xac , 0x48 , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMAnimationSet2 , 0xff6b7f79 , 0xa40e , 0x11d1 , 0x91 , 0xf9 , 0x0 , 0x0 , 0xf8 , 0x75 , 0x8e , 0x66)
DEFINE_GUID (IID_IDirect3DRMObjectArray , 0x242f6bc2 , 0x3849 , 0x11d0 , 0x9b , 0x6d , 0x0 , 0x0 , 0xc0 , 0x78 , 0x1b , 0xc3)
DEFINE_GUID (IID_IDirect3DRMDeviceArray , 0xeb16cb10 , 0xd271 , 0x11ce , 0xac , 0x48 , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMViewportArray , 0xeb16cb11 , 0xd271 , 0x11ce , 0xac , 0x48 , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMFrameArray , 0xeb16cb12 , 0xd271 , 0x11ce , 0xac , 0x48 , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMVisualArray , 0xeb16cb13 , 0xd271 , 0x11ce , 0xac , 0x48 , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMLightArray , 0xeb16cb14 , 0xd271 , 0x11ce , 0xac , 0x48 , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMPickedArray , 0xeb16cb16 , 0xd271 , 0x11ce , 0xac , 0x48 , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMFaceArray , 0xeb16cb17 , 0xd271 , 0x11ce , 0xac , 0x48 , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMAnimationArray , 0xd5f1cae0 , 0x4bd7 , 0x11d1 , 0xb9 , 0x74 , 0x0 , 0x60 , 0x8 , 0x3e , 0x45 , 0xf3)
DEFINE_GUID (IID_IDirect3DRMUserVisual , 0x59163de0 , 0x6d43 , 0x11cf , 0xac , 0x4a , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMShadow , 0xaf359780 , 0x6ba3 , 0x11cf , 0xac , 0x4a , 0x0 , 0x0 , 0xc0 , 0x38 , 0x25 , 0xa1)
DEFINE_GUID (IID_IDirect3DRMShadow2 , 0x86b44e25 , 0x9c82 , 0x11d1 , 0xbb , 0xb , 0x0 , 0xa0 , 0xc9 , 0x81 , 0xa0 , 0xa6)
DEFINE_GUID (IID_IDirect3DRMInterpolator , 0x242f6bc1 , 0x3849 , 0x11d0 , 0x9b , 0x6d , 0x0 , 0x0 , 0xc0 , 0x78 , 0x1b , 0xc3)
DEFINE_GUID (IID_IDirect3DRMProgressiveMesh , 0x4516ec79 , 0x8f20 , 0x11d0 , 0x9b , 0x6d , 0x0 , 0x0 , 0xc0 , 0x78 , 0x1b , 0xc3)
DEFINE_GUID (IID_IDirect3DRMPicked2Array , 0x4516ec7b , 0x8f20 , 0x11d0 , 0x9b , 0x6d , 0x0 , 0x0 , 0xc0 , 0x78 , 0x1b , 0xc3)
DEFINE_GUID (IID_IDirect3DRMClippedVisual , 0x5434e733 , 0x6d66 , 0x11d1 , 0xbb , 0xb , 0x0 , 0x0 , 0xf8 , 0x75 , 0x86 , 0x5a)
typedef HRESULT (__cdecl * D3DRMLOADTEXTURECALLBACK)
typedef int (__cdecl * D3DRMUSERVISUALCALLBACK)
Referenced by analog(), GRigid::ApplyExtForce(), ax(), ay(), az(), GRigid::Disp(), GWorld::DispNetChip(), GRigid::DispObject(), DlgExtraProc(), DlgNetworkProc(), DXUtil_ConvertAnsiStringToWide(), DXUtil_ConvertWideStringToAnsi(), ex(), ey(), ez(), CMyD3DApplication::FrameMove(), fx(), fy(), fz(), getAngle(), getBrake(), getCCD(), getColor(), getDamper(), getDir(), getEffect(), getEnergy(), getFuel(), getFuelMax(), GDPlay::GetHostName(), getOption(), getParent(), getPlayerArms(), getPlayerChips(), getPlayerColor(), getPlayerCrushes(), getPlayerID(), getPlayerInits(), getPlayerName(), getPlayerName2(), getPlayerResets(), getPlayerX(), getPlayerY(), getPlayerYForces(), getPlayerZ(), getPower(), getSpring(), CD3DFont::GetTextExtent(), getTolerant(), getTop(), getType(), getY(), gx(), gy(), gz(), hat(), CD3DFont::InitDeviceObjects(), integer(), key(), keyDown(), keyUp(), LoadLand(), luaAddChip(), luaAnalog(), luaApplyForce(), luaApplyForceObj(), luaApplyTorque(), luaApplyTorqueObj(), luaAx(), luaAy(), luaAz(), luaCheckObjRingArea(), luaCheckRingArea(), luaCollisionObjRingArea(), luaCollisionRingArea(), luaControlKeyLock(), luaDirect(), luaDirectObj(), luaEnervate(), luaEnervateObj(), luaEx(), luaEy(), luaEz(), luaFileClose(), luaFileGets(), luaFilePuts(), luaFx(), luaFy(), luaFz(), luaGetAngle(), luaGetBrake(), luaGetChild(), luaGetChip(), luaGetColor(), luaGetDamper(), luaGetDir(), luaGetEffect(), luaGetEnergy(), luaGetFuel(), luaGetFuelMax(), luaGetI(), luaGetM(), luaGetObjI(), luaGetObjM(), luaGetOption(), luaGetParent(), luaGetPlayerArms(), luaGetPlayerChips(), luaGetPlayerColor(), luaGetPlayerCrushes(), luaGetPlayerID(), luaGetPlayerInits(), luaGetPlayerName(), luaGetPlayerResets(), luaGetPlayerX(), luaGetPlayerY(), luaGetPlayerYForces(), luaGetPlayerZ(), luaGetPower(), luaGetRing(), luaGetRingState(), luaGetSpring(), luaGetSystemKey(), luaGetSystemKeyDown(), luaGetSystemKeyUp(), luaGetTolerant(), luaGetTop(), luaGetType(), luaGetUserEffect(), luaGetUserOption(), luaGetY(), luaGx(), luaGy(), luaGz(), luaHat(), luaHitCount(), luaHitCountObj(), luaKey(), luaKey2(), luaKeyDown(), luaKeyDown2(), luaKeyLock(), luaKeyUp(), luaKeyUp2(), luaLx(), luaLy(), luaLz(), luaObjPosx(), luaObjPosy(), luaObjPosz(), luaPosx(), luaPosy(), luaPosz(), luaPrint(), luaQw(), luaQx(), luaQy(), luaQz(), luaReceiveMessage(), luaReceiveMessageClear(), luaReset(), luaRotate(), luaRotateObj(), luaRx(), luaRy(), luaRz(), luaSetChip(), luaSetColor(), luaSetObjColor(), luaSetObjFix(), luaSetRing(), luaSetRingColor(), luaSetRingState(), luaSetTicks(), luaSetViewType(), luaSystemPrint(), luaUnLink(), luaUnLinkBye(), luaVel(), luaVx(), luaVy(), luaVz(), luaWarp(), luaWarpObj(), luaWx(), luaWy(), luaWz(), luaXx(), luaXy(), luaXz(), luaYx(), luaYy(), luaYz(), luaZx(), luaZy(), luaZz(), lx(), ly(), lz(), CMyD3DApplication::MsgProc(), ObjPosx(), ObjPosy(), ObjPosz(), posx(), posy(), posz(), qw(), qx(), qy(), qz(), readChildData(), CMyD3DApplication::Render(), CMyD3DApplication::RenderText(), round(), rx(), ry(), rz(), setColor(), setOption(), setTicks(), statement(), unLink(), unLinkBye(), vel(), vx(), vy(), vz(), wx(), wy(), wz(), xx(), xy(), xz(), yx(), yy(), yz(), zx(), zy(), and zz().
WIN_TYPES (IDirect3DRMObject , DIRECT3DRMOBJECT)
WIN_TYPES (IDirect3DRMObject2 , DIRECT3DRMOBJECT2)
WIN_TYPES (IDirect3DRMDevice , DIRECT3DRMDEVICE)
WIN_TYPES (IDirect3DRMDevice2 , DIRECT3DRMDEVICE2)
WIN_TYPES (IDirect3DRMDevice3 , DIRECT3DRMDEVICE3)
WIN_TYPES (IDirect3DRMViewport , DIRECT3DRMVIEWPORT)
WIN_TYPES (IDirect3DRMViewport2 , DIRECT3DRMVIEWPORT2)
WIN_TYPES (IDirect3DRMFrame , DIRECT3DRMFRAME)
WIN_TYPES (IDirect3DRMFrame2 , DIRECT3DRMFRAME2)
WIN_TYPES (IDirect3DRMFrame3 , DIRECT3DRMFRAME3)
WIN_TYPES (IDirect3DRMVisual , DIRECT3DRMVISUAL)
WIN_TYPES (IDirect3DRMMesh , DIRECT3DRMMESH)
WIN_TYPES (IDirect3DRMMeshBuilder , DIRECT3DRMMESHBUILDER)
WIN_TYPES (IDirect3DRMMeshBuilder2 , DIRECT3DRMMESHBUILDER2)
WIN_TYPES (IDirect3DRMMeshBuilder3 , DIRECT3DRMMESHBUILDER3)
WIN_TYPES (IDirect3DRMFace , DIRECT3DRMFACE)
WIN_TYPES (IDirect3DRMFace2 , DIRECT3DRMFACE2)
WIN_TYPES (IDirect3DRMLight , DIRECT3DRMLIGHT)
WIN_TYPES (IDirect3DRMTexture , DIRECT3DRMTEXTURE)
WIN_TYPES (IDirect3DRMTexture2 , DIRECT3DRMTEXTURE2)
WIN_TYPES (IDirect3DRMTexture3 , DIRECT3DRMTEXTURE3)
WIN_TYPES (IDirect3DRMWrap , DIRECT3DRMWRAP)
WIN_TYPES (IDirect3DRMMaterial , DIRECT3DRMMATERIAL)
WIN_TYPES (IDirect3DRMMaterial2 , DIRECT3DRMMATERIAL2)
WIN_TYPES (IDirect3DRMInterpolator , DIRECT3DRMINTERPOLATOR)
WIN_TYPES (IDirect3DRMAnimation , DIRECT3DRMANIMATION)
WIN_TYPES (IDirect3DRMAnimation2 , DIRECT3DRMANIMATION2)
WIN_TYPES (IDirect3DRMAnimationSet , DIRECT3DRMANIMATIONSET)
WIN_TYPES (IDirect3DRMAnimationSet2 , DIRECT3DRMANIMATIONSET2)
WIN_TYPES (IDirect3DRMUserVisual , DIRECT3DRMUSERVISUAL)
WIN_TYPES (IDirect3DRMShadow , DIRECT3DRMSHADOW)
WIN_TYPES (IDirect3DRMShadow2 , DIRECT3DRMSHADOW2)
WIN_TYPES (IDirect3DRMArray , DIRECT3DRMARRAY)
WIN_TYPES (IDirect3DRMObjectArray , DIRECT3DRMOBJECTARRAY)
WIN_TYPES (IDirect3DRMDeviceArray , DIRECT3DRMDEVICEARRAY)
WIN_TYPES (IDirect3DRMFaceArray , DIRECT3DRMFACEARRAY)
WIN_TYPES (IDirect3DRMViewportArray , DIRECT3DRMVIEWPORTARRAY)
WIN_TYPES (IDirect3DRMFrameArray , DIRECT3DRMFRAMEARRAY)
WIN_TYPES (IDirect3DRMAnimationArray , DIRECT3DRMANIMATIONARRAY)
WIN_TYPES (IDirect3DRMVisualArray , DIRECT3DRMVISUALARRAY)
WIN_TYPES (IDirect3DRMPickedArray , DIRECT3DRMPICKEDARRAY)
WIN_TYPES (IDirect3DRMPicked2Array , DIRECT3DRMPICKED2ARRAY)
WIN_TYPES (IDirect3DRMLightArray , DIRECT3DRMLIGHTARRAY)
WIN_TYPES (IDirect3DRMProgressiveMesh , DIRECT3DRMPROGRESSIVEMESH)
WIN_TYPES (IDirect3DRMClippedVisual , DIRECT3DRMCLIPPEDVISUAL)