RigidChips: d3dutil.cpp File Reference
d3dutil.cpp File Reference
#include <tchar.h>
#include <stdio.h>
#include "D3DUtil.h"
#include "DXUtil.h"
#include "D3DX8.h"
Macros
#define STRICT
Functions
VOID D3DUtil_InitMaterial (D3DMATERIAL8 &mtrl, FLOAT r, FLOAT g, FLOAT b, FLOAT a)
VOID D3DUtil_InitLight (D3DLIGHT8 &light, D3DLIGHTTYPE ltType, FLOAT x, FLOAT y, FLOAT z)
HRESULT D3DUtil_CreateTexture (LPDIRECT3DDEVICE8 pd3dDevice, TCHAR *strTexture, LPDIRECT3DTEXTURE8 *ppTexture, D3DFORMAT d3dFormat)
HRESULT D3DUtil_SetColorKey (LPDIRECT3DTEXTURE8 pTexture, DWORD dwColorKey)
HRESULT D3DUtil_CreateVertexShader (LPDIRECT3DDEVICE8 pd3dDevice, TCHAR *strFilename, DWORD *pdwVertexDecl, DWORD *pdwVertexShader)
D3DXMATRIX D3DUtil_GetCubeMapViewMatrix (DWORD dwFace)
D3DXQUATERNION D3DUtil_GetRotationFromCursor (HWND hWnd, FLOAT fTrackBallRadius)
HRESULT D3DUtil_SetDeviceCursor (LPDIRECT3DDEVICE8 pd3dDevice, HCURSOR hCursor, BOOL bAddWatermark)
D3DXQUATERNION *WINAPI D3DXQuaternionUnitAxisToUnitAxis2 (D3DXQUATERNION *pOut, const D3DXVECTOR3 *pvFrom, const D3DXVECTOR3 *pvTo)
D3DXQUATERNION *WINAPI D3DXQuaternionAxisToAxis (D3DXQUATERNION *pOut, const D3DXVECTOR3 *pvFrom, const D3DXVECTOR3 *pvTo)
Macro Definition Documentation
#define STRICT
Function Documentation
HRESULT D3DUtil_CreateTexture (LPDIRECT3DDEVICE8 pd3dDevice, TCHAR * strTexture, LPDIRECT3DTEXTURE8 * ppTexture, D3DFORMAT d3dFormat)
HRESULT D3DUtil_CreateVertexShader (LPDIRECT3DDEVICE8 pd3dDevice, TCHAR * strFilename, DWORD * pdwVertexDecl, DWORD * pdwVertexShader)
D3DXMATRIX D3DUtil_GetCubeMapViewMatrix (DWORD dwFace)
D3DXQUATERNION D3DUtil_GetRotationFromCursor (HWND hWnd, FLOAT fTrackBallRadius)
VOID D3DUtil_InitLight (D3DLIGHT8 & light, D3DLIGHTTYPE ltType, FLOAT x, FLOAT y, FLOAT z)
Referenced by CMyD3DApplication::RestoreDeviceObjects().
VOID D3DUtil_InitMaterial (D3DMATERIAL8 & mtrl, FLOAT r, FLOAT g, FLOAT b, FLOAT a)
Referenced by CMyD3DApplication::RestoreDeviceObjects(), Text3D(), and Text3Dm().
HRESULT D3DUtil_SetColorKey (LPDIRECT3DTEXTURE8 pTexture, DWORD dwColorKey)
HRESULT D3DUtil_SetDeviceCursor (LPDIRECT3DDEVICE8 pd3dDevice, HCURSOR hCursor, BOOL bAddWatermark)
Referenced by CD3DApplication::Initialize3DEnvironment(), and CD3DApplication::Resize3DEnvironment().
D3DXQUATERNION* WINAPI D3DXQuaternionAxisToAxis (D3DXQUATERNION * pOut, const D3DXVECTOR3 * pvFrom, const D3DXVECTOR3 * pvTo) inline
Referenced by CD3DArcBall::HandleMouseMessages().
D3DXQUATERNION* WINAPI D3DXQuaternionUnitAxisToUnitAxis2 (D3DXQUATERNION * pOut, const D3DXVECTOR3 * pvFrom, const D3DXVECTOR3 * pvTo) inline
Referenced by D3DXQuaternionAxisToAxis().