RigidChips: microsoft directx 9.0 sdk (summer 2004)/Include/d3dvec.inl File Reference
d3dvec.inl File Reference
#include <math.h>
Functions
_D3DVECTOR operator+ (const _D3DVECTOR &v)
_D3DVECTOR operator- (const _D3DVECTOR &v)
_D3DVECTOR operator+ (const _D3DVECTOR &v1, const _D3DVECTOR &v2)
_D3DVECTOR operator- (const _D3DVECTOR &v1, const _D3DVECTOR &v2)
_D3DVECTOR operator* (const _D3DVECTOR &v1, const _D3DVECTOR &v2)
_D3DVECTOR operator/ (const _D3DVECTOR &v1, const _D3DVECTOR &v2)
int operator< (const _D3DVECTOR &v1, const _D3DVECTOR &v2)
int operator<= (const _D3DVECTOR &v1, const _D3DVECTOR &v2)
_D3DVECTOR operator* (const _D3DVECTOR &v, D3DVALUE s)
_D3DVECTOR operator* (D3DVALUE s, const _D3DVECTOR &v)
_D3DVECTOR operator/ (const _D3DVECTOR &v, D3DVALUE s)
int operator== (const _D3DVECTOR &v1, const _D3DVECTOR &v2)
D3DVALUE Magnitude (const _D3DVECTOR &v)
D3DVALUE SquareMagnitude (const _D3DVECTOR &v)
_D3DVECTOR Normalize (const _D3DVECTOR &v)
D3DVALUE Min (const _D3DVECTOR &v)
D3DVALUE Max (const _D3DVECTOR &v)
_D3DVECTOR Minimize (const _D3DVECTOR &v1, const _D3DVECTOR &v2)
_D3DVECTOR Maximize (const _D3DVECTOR &v1, const _D3DVECTOR &v2)
D3DVALUE DotProduct (const _D3DVECTOR &v1, const _D3DVECTOR &v2)
_D3DVECTOR CrossProduct (const _D3DVECTOR &v1, const _D3DVECTOR &v2)
_D3DMATRIX operator* (const _D3DMATRIX &a, const _D3DMATRIX &b)
Function Documentation
_D3DVECTOR CrossProduct (const _D3DVECTOR & v1, const _D3DVECTOR & v2) inline
D3DVALUE DotProduct (const _D3DVECTOR & v1, const _D3DVECTOR & v2) inline
D3DVALUE Magnitude (const _D3DVECTOR & v) inline
Referenced by Normalize().
D3DVALUE Max (const _D3DVECTOR & v) inline
Referenced by CMyD3DApplication::FrameMove(), CMyD3DApplication::InitDeviceObjects(), luaScriptRun(), luaSetChip(), luaSystemRun(), CMyD3DApplication::OneTimeSceneInit(), readData2(), ResetChip3(), saveData(), and statement().
_D3DVECTOR Maximize (const _D3DVECTOR & v1, const _D3DVECTOR & v2) inline
D3DVALUE Min (const _D3DVECTOR & v) inline
Referenced by CMyD3DApplication::FrameMove(), CMyD3DApplication::InitDeviceObjects(), luaScriptRun(), luaSetChip(), luaSystemRun(), CMyD3DApplication::OneTimeSceneInit(), readData2(), ResetChip3(), saveData(), and statement().
_D3DVECTOR Minimize (const _D3DVECTOR & v1, const _D3DVECTOR & v2) inline
_D3DVECTOR Normalize (const _D3DVECTOR & v) inline
_D3DVECTOR operator* (const _D3DVECTOR & v1, const _D3DVECTOR & v2) inline
_D3DVECTOR operator* (const _D3DVECTOR & v, D3DVALUE s) inline
_D3DVECTOR operator* (D3DVALUE s, const _D3DVECTOR & v) inline
_D3DMATRIX operator* (const _D3DMATRIX & a, const _D3DMATRIX & b) inline
_D3DVECTOR operator+ (const _D3DVECTOR & v) inline
_D3DVECTOR operator+ (const _D3DVECTOR & v1, const _D3DVECTOR & v2) inline
_D3DVECTOR operator- (const _D3DVECTOR & v) inline
_D3DVECTOR operator- (const _D3DVECTOR & v1, const _D3DVECTOR & v2) inline
_D3DVECTOR operator/ (const _D3DVECTOR & v1, const _D3DVECTOR & v2) inline
_D3DVECTOR operator/ (const _D3DVECTOR & v, D3DVALUE s) inline
int operator< (const _D3DVECTOR & v1, const _D3DVECTOR & v2) inline
int operator<= (const _D3DVECTOR & v1, const _D3DVECTOR & v2) inline
int operator== (const _D3DVECTOR & v1, const _D3DVECTOR & v2) inline
D3DVALUE SquareMagnitude (const _D3DVECTOR & v) inline
Referenced by Magnitude().