RigidChips: microsoft directx 9.0 sdk (summer 2004)/Include/d3dx9math.inl File Reference
d3dx9math.inl File Reference
Macros
#define __D3DX9MATH_INL__
Functions
D3DXINLINE FLOAT D3DXVec2Length (CONST D3DXVECTOR2 *pV)
D3DXINLINE FLOAT D3DXVec2LengthSq (CONST D3DXVECTOR2 *pV)
D3DXINLINE FLOAT D3DXVec2Dot (CONST D3DXVECTOR2 *pV1, CONST D3DXVECTOR2 *pV2)
D3DXINLINE FLOAT D3DXVec2CCW (CONST D3DXVECTOR2 *pV1, CONST D3DXVECTOR2 *pV2)
D3DXINLINE D3DXVECTOR2 * D3DXVec2Add (D3DXVECTOR2 *pOut, CONST D3DXVECTOR2 *pV1, CONST D3DXVECTOR2 *pV2)
D3DXINLINE D3DXVECTOR2 * D3DXVec2Subtract (D3DXVECTOR2 *pOut, CONST D3DXVECTOR2 *pV1, CONST D3DXVECTOR2 *pV2)
D3DXINLINE D3DXVECTOR2 * D3DXVec2Minimize (D3DXVECTOR2 *pOut, CONST D3DXVECTOR2 *pV1, CONST D3DXVECTOR2 *pV2)
D3DXINLINE D3DXVECTOR2 * D3DXVec2Maximize (D3DXVECTOR2 *pOut, CONST D3DXVECTOR2 *pV1, CONST D3DXVECTOR2 *pV2)
D3DXINLINE D3DXVECTOR2 * D3DXVec2Scale (D3DXVECTOR2 *pOut, CONST D3DXVECTOR2 *pV, FLOAT s)
D3DXINLINE D3DXVECTOR2 * D3DXVec2Lerp (D3DXVECTOR2 *pOut, CONST D3DXVECTOR2 *pV1, CONST D3DXVECTOR2 *pV2, FLOAT s)
D3DXINLINE FLOAT D3DXVec3Length (CONST D3DXVECTOR3 *pV)
D3DXINLINE FLOAT D3DXVec3LengthSq (CONST D3DXVECTOR3 *pV)
D3DXINLINE FLOAT D3DXVec3Dot (CONST D3DXVECTOR3 *pV1, CONST D3DXVECTOR3 *pV2)
D3DXINLINE D3DXVECTOR3 * D3DXVec3Cross (D3DXVECTOR3 *pOut, CONST D3DXVECTOR3 *pV1, CONST D3DXVECTOR3 *pV2)
D3DXINLINE D3DXVECTOR3 * D3DXVec3Add (D3DXVECTOR3 *pOut, CONST D3DXVECTOR3 *pV1, CONST D3DXVECTOR3 *pV2)
D3DXINLINE D3DXVECTOR3 * D3DXVec3Subtract (D3DXVECTOR3 *pOut, CONST D3DXVECTOR3 *pV1, CONST D3DXVECTOR3 *pV2)
D3DXINLINE D3DXVECTOR3 * D3DXVec3Minimize (D3DXVECTOR3 *pOut, CONST D3DXVECTOR3 *pV1, CONST D3DXVECTOR3 *pV2)
D3DXINLINE D3DXVECTOR3 * D3DXVec3Maximize (D3DXVECTOR3 *pOut, CONST D3DXVECTOR3 *pV1, CONST D3DXVECTOR3 *pV2)
D3DXINLINE D3DXVECTOR3 * D3DXVec3Scale (D3DXVECTOR3 *pOut, CONST D3DXVECTOR3 *pV, FLOAT s)
D3DXINLINE D3DXVECTOR3 * D3DXVec3Lerp (D3DXVECTOR3 *pOut, CONST D3DXVECTOR3 *pV1, CONST D3DXVECTOR3 *pV2, FLOAT s)
D3DXINLINE FLOAT D3DXVec4Length (CONST D3DXVECTOR4 *pV)
D3DXINLINE FLOAT D3DXVec4LengthSq (CONST D3DXVECTOR4 *pV)
D3DXINLINE FLOAT D3DXVec4Dot (CONST D3DXVECTOR4 *pV1, CONST D3DXVECTOR4 *pV2)
D3DXINLINE D3DXVECTOR4 * D3DXVec4Add (D3DXVECTOR4 *pOut, CONST D3DXVECTOR4 *pV1, CONST D3DXVECTOR4 *pV2)
D3DXINLINE D3DXVECTOR4 * D3DXVec4Subtract (D3DXVECTOR4 *pOut, CONST D3DXVECTOR4 *pV1, CONST D3DXVECTOR4 *pV2)
D3DXINLINE D3DXVECTOR4 * D3DXVec4Minimize (D3DXVECTOR4 *pOut, CONST D3DXVECTOR4 *pV1, CONST D3DXVECTOR4 *pV2)
D3DXINLINE D3DXVECTOR4 * D3DXVec4Maximize (D3DXVECTOR4 *pOut, CONST D3DXVECTOR4 *pV1, CONST D3DXVECTOR4 *pV2)
D3DXINLINE D3DXVECTOR4 * D3DXVec4Scale (D3DXVECTOR4 *pOut, CONST D3DXVECTOR4 *pV, FLOAT s)
D3DXINLINE D3DXVECTOR4 * D3DXVec4Lerp (D3DXVECTOR4 *pOut, CONST D3DXVECTOR4 *pV1, CONST D3DXVECTOR4 *pV2, FLOAT s)
D3DXINLINE D3DXMATRIX * D3DXMatrixIdentity (D3DXMATRIX *pOut)
D3DXINLINE BOOL D3DXMatrixIsIdentity (CONST D3DXMATRIX *pM)
D3DXINLINE FLOAT D3DXQuaternionLength (CONST D3DXQUATERNION *pQ)
D3DXINLINE FLOAT D3DXQuaternionLengthSq (CONST D3DXQUATERNION *pQ)
D3DXINLINE FLOAT D3DXQuaternionDot (CONST D3DXQUATERNION *pQ1, CONST D3DXQUATERNION *pQ2)
D3DXINLINE D3DXQUATERNION * D3DXQuaternionIdentity (D3DXQUATERNION *pOut)
D3DXINLINE BOOL D3DXQuaternionIsIdentity (CONST D3DXQUATERNION *pQ)
D3DXINLINE D3DXQUATERNION * D3DXQuaternionConjugate (D3DXQUATERNION *pOut, CONST D3DXQUATERNION *pQ)
D3DXINLINE FLOAT D3DXPlaneDot (CONST D3DXPLANE *pP, CONST D3DXVECTOR4 *pV)
D3DXINLINE FLOAT D3DXPlaneDotCoord (CONST D3DXPLANE *pP, CONST D3DXVECTOR3 *pV)
D3DXINLINE FLOAT D3DXPlaneDotNormal (CONST D3DXPLANE *pP, CONST D3DXVECTOR3 *pV)
D3DXINLINE D3DXPLANE * D3DXPlaneScale (D3DXPLANE *pOut, CONST D3DXPLANE *pP, FLOAT s)
D3DXINLINE D3DXCOLOR * D3DXColorNegative (D3DXCOLOR *pOut, CONST D3DXCOLOR *pC)
D3DXINLINE D3DXCOLOR * D3DXColorAdd (D3DXCOLOR *pOut, CONST D3DXCOLOR *pC1, CONST D3DXCOLOR *pC2)
D3DXINLINE D3DXCOLOR * D3DXColorSubtract (D3DXCOLOR *pOut, CONST D3DXCOLOR *pC1, CONST D3DXCOLOR *pC2)
D3DXINLINE D3DXCOLOR * D3DXColorScale (D3DXCOLOR *pOut, CONST D3DXCOLOR *pC, FLOAT s)
D3DXINLINE D3DXCOLOR * D3DXColorModulate (D3DXCOLOR *pOut, CONST D3DXCOLOR *pC1, CONST D3DXCOLOR *pC2)
D3DXINLINE D3DXCOLOR * D3DXColorLerp (D3DXCOLOR *pOut, CONST D3DXCOLOR *pC1, CONST D3DXCOLOR *pC2, FLOAT s)
Macro Definition Documentation
#define __D3DX9MATH_INL__
Function Documentation
D3DXINLINE D3DXCOLOR* D3DXColorAdd (D3DXCOLOR * pOut, CONST D3DXCOLOR * pC1, CONST D3DXCOLOR * pC2)
D3DXINLINE D3DXCOLOR* D3DXColorLerp (D3DXCOLOR * pOut, CONST D3DXCOLOR * pC1, CONST D3DXCOLOR * pC2, FLOAT s)
D3DXINLINE D3DXCOLOR* D3DXColorModulate (D3DXCOLOR * pOut, CONST D3DXCOLOR * pC1, CONST D3DXCOLOR * pC2)
D3DXINLINE D3DXCOLOR* D3DXColorNegative (D3DXCOLOR * pOut, CONST D3DXCOLOR * pC)
D3DXINLINE D3DXCOLOR* D3DXColorScale (D3DXCOLOR * pOut, CONST D3DXCOLOR * pC, FLOAT s)
D3DXINLINE D3DXCOLOR* D3DXColorSubtract (D3DXCOLOR * pOut, CONST D3DXCOLOR * pC1, CONST D3DXCOLOR * pC2)
D3DXINLINE D3DXMATRIX* D3DXMatrixIdentity (D3DXMATRIX * pOut)
D3DXINLINE BOOL D3DXMatrixIsIdentity (CONST D3DXMATRIX * pM)
D3DXINLINE FLOAT D3DXPlaneDot (CONST D3DXPLANE * pP, CONST D3DXVECTOR4 * pV)
D3DXINLINE FLOAT D3DXPlaneDotCoord (CONST D3DXPLANE * pP, CONST D3DXVECTOR3 * pV)
D3DXINLINE FLOAT D3DXPlaneDotNormal (CONST D3DXPLANE * pP, CONST D3DXVECTOR3 * pV)
D3DXINLINE D3DXPLANE* D3DXPlaneScale (D3DXPLANE * pOut, CONST D3DXPLANE * pP, FLOAT s)
D3DXINLINE D3DXQUATERNION* D3DXQuaternionConjugate (D3DXQUATERNION * pOut, CONST D3DXQUATERNION * pQ)
D3DXINLINE FLOAT D3DXQuaternionDot (CONST D3DXQUATERNION * pQ1, CONST D3DXQUATERNION * pQ2)
D3DXINLINE D3DXQUATERNION* D3DXQuaternionIdentity (D3DXQUATERNION * pOut)
D3DXINLINE BOOL D3DXQuaternionIsIdentity (CONST D3DXQUATERNION * pQ)
D3DXINLINE FLOAT D3DXQuaternionLength (CONST D3DXQUATERNION * pQ)
D3DXINLINE FLOAT D3DXQuaternionLengthSq (CONST D3DXQUATERNION * pQ)
D3DXINLINE D3DXVECTOR2* D3DXVec2Add (D3DXVECTOR2 * pOut, CONST D3DXVECTOR2 * pV1, CONST D3DXVECTOR2 * pV2)
D3DXINLINE FLOAT D3DXVec2CCW (CONST D3DXVECTOR2 * pV1, CONST D3DXVECTOR2 * pV2)
D3DXINLINE FLOAT D3DXVec2Dot (CONST D3DXVECTOR2 * pV1, CONST D3DXVECTOR2 * pV2)
D3DXINLINE FLOAT D3DXVec2Length (CONST D3DXVECTOR2 * pV)
D3DXINLINE FLOAT D3DXVec2LengthSq (CONST D3DXVECTOR2 * pV)
D3DXINLINE D3DXVECTOR2* D3DXVec2Lerp (D3DXVECTOR2 * pOut, CONST D3DXVECTOR2 * pV1, CONST D3DXVECTOR2 * pV2, FLOAT s)
D3DXINLINE D3DXVECTOR2* D3DXVec2Maximize (D3DXVECTOR2 * pOut, CONST D3DXVECTOR2 * pV1, CONST D3DXVECTOR2 * pV2)
D3DXINLINE D3DXVECTOR2* D3DXVec2Minimize (D3DXVECTOR2 * pOut, CONST D3DXVECTOR2 * pV1, CONST D3DXVECTOR2 * pV2)
D3DXINLINE D3DXVECTOR2* D3DXVec2Scale (D3DXVECTOR2 * pOut, CONST D3DXVECTOR2 * pV, FLOAT s)
D3DXINLINE D3DXVECTOR2* D3DXVec2Subtract (D3DXVECTOR2 * pOut, CONST D3DXVECTOR2 * pV1, CONST D3DXVECTOR2 * pV2)
D3DXINLINE D3DXVECTOR3* D3DXVec3Add (D3DXVECTOR3 * pOut, CONST D3DXVECTOR3 * pV1, CONST D3DXVECTOR3 * pV2)
D3DXINLINE D3DXVECTOR3* D3DXVec3Cross (D3DXVECTOR3 * pOut, CONST D3DXVECTOR3 * pV1, CONST D3DXVECTOR3 * pV2)
Referenced by D3DUtil_GetRotationFromCursor(), D3DXQuaternionUnitAxisToUnitAxis2(), and CD3DCamera::SetViewParams().
D3DXINLINE FLOAT D3DXVec3Dot (CONST D3DXVECTOR3 * pV1, CONST D3DXVECTOR3 * pV2)
Referenced by D3DXQuaternionUnitAxisToUnitAxis2().
D3DXINLINE FLOAT D3DXVec3Length (CONST D3DXVECTOR3 * pV)
Referenced by D3DUtil_GetRotationFromCursor().
D3DXINLINE FLOAT D3DXVec3LengthSq (CONST D3DXVECTOR3 * pV)
D3DXINLINE D3DXVECTOR3* D3DXVec3Lerp (D3DXVECTOR3 * pOut, CONST D3DXVECTOR3 * pV1, CONST D3DXVECTOR3 * pV2, FLOAT s)
D3DXINLINE D3DXVECTOR3* D3DXVec3Maximize (D3DXVECTOR3 * pOut, CONST D3DXVECTOR3 * pV1, CONST D3DXVECTOR3 * pV2)
D3DXINLINE D3DXVECTOR3* D3DXVec3Minimize (D3DXVECTOR3 * pOut, CONST D3DXVECTOR3 * pV1, CONST D3DXVECTOR3 * pV2)
D3DXINLINE D3DXVECTOR3* D3DXVec3Scale (D3DXVECTOR3 * pOut, CONST D3DXVECTOR3 * pV, FLOAT s)
D3DXINLINE D3DXVECTOR3* D3DXVec3Subtract (D3DXVECTOR3 * pOut, CONST D3DXVECTOR3 * pV1, CONST D3DXVECTOR3 * pV2)
D3DXINLINE D3DXVECTOR4* D3DXVec4Add (D3DXVECTOR4 * pOut, CONST D3DXVECTOR4 * pV1, CONST D3DXVECTOR4 * pV2)
D3DXINLINE FLOAT D3DXVec4Dot (CONST D3DXVECTOR4 * pV1, CONST D3DXVECTOR4 * pV2)
D3DXINLINE FLOAT D3DXVec4Length (CONST D3DXVECTOR4 * pV)
D3DXINLINE FLOAT D3DXVec4LengthSq (CONST D3DXVECTOR4 * pV)
D3DXINLINE D3DXVECTOR4* D3DXVec4Lerp (D3DXVECTOR4 * pOut, CONST D3DXVECTOR4 * pV1, CONST D3DXVECTOR4 * pV2, FLOAT s)
D3DXINLINE D3DXVECTOR4* D3DXVec4Maximize (D3DXVECTOR4 * pOut, CONST D3DXVECTOR4 * pV1, CONST D3DXVECTOR4 * pV2)
D3DXINLINE D3DXVECTOR4* D3DXVec4Minimize (D3DXVECTOR4 * pOut, CONST D3DXVECTOR4 * pV1, CONST D3DXVECTOR4 * pV2)
D3DXINLINE D3DXVECTOR4* D3DXVec4Scale (D3DXVECTOR4 * pOut, CONST D3DXVECTOR4 * pV, FLOAT s)
D3DXINLINE D3DXVECTOR4* D3DXVec4Subtract (D3DXVECTOR4 * pOut, CONST D3DXVECTOR4 * pV1, CONST D3DXVECTOR4 * pV2)