RigidChips: microsoft directx 9.0 sdk (summer 2004)/Include/d3dxmath.inl File Reference
d3dxmath.inl File Reference
Macros
#define __D3DXMATH_INL__
Functions
D3DXINLINE float D3DXVec2Length (const D3DXVECTOR2 *pV)
D3DXINLINE float D3DXVec2LengthSq (const D3DXVECTOR2 *pV)
D3DXINLINE float D3DXVec2Dot (const D3DXVECTOR2 *pV1, const D3DXVECTOR2 *pV2)
D3DXINLINE float D3DXVec2CCW (const D3DXVECTOR2 *pV1, const D3DXVECTOR2 *pV2)
D3DXINLINE D3DXVECTOR2 * D3DXVec2Add (D3DXVECTOR2 *pOut, const D3DXVECTOR2 *pV1, const D3DXVECTOR2 *pV2)
D3DXINLINE D3DXVECTOR2 * D3DXVec2Subtract (D3DXVECTOR2 *pOut, const D3DXVECTOR2 *pV1, const D3DXVECTOR2 *pV2)
D3DXINLINE D3DXVECTOR2 * D3DXVec2Minimize (D3DXVECTOR2 *pOut, const D3DXVECTOR2 *pV1, const D3DXVECTOR2 *pV2)
D3DXINLINE D3DXVECTOR2 * D3DXVec2Maximize (D3DXVECTOR2 *pOut, const D3DXVECTOR2 *pV1, const D3DXVECTOR2 *pV2)
D3DXINLINE D3DXVECTOR2 * D3DXVec2Scale (D3DXVECTOR2 *pOut, const D3DXVECTOR2 *pV, float s)
D3DXINLINE D3DXVECTOR2 * D3DXVec2Lerp (D3DXVECTOR2 *pOut, const D3DXVECTOR2 *pV1, const D3DXVECTOR2 *pV2, float s)
D3DXINLINE float D3DXVec3Length (const D3DXVECTOR3 *pV)
D3DXINLINE float D3DXVec3LengthSq (const D3DXVECTOR3 *pV)
D3DXINLINE float D3DXVec3Dot (const D3DXVECTOR3 *pV1, const D3DXVECTOR3 *pV2)
D3DXINLINE D3DXVECTOR3 * D3DXVec3Cross (D3DXVECTOR3 *pOut, const D3DXVECTOR3 *pV1, const D3DXVECTOR3 *pV2)
D3DXINLINE D3DXVECTOR3 * D3DXVec3Add (D3DXVECTOR3 *pOut, const D3DXVECTOR3 *pV1, const D3DXVECTOR3 *pV2)
D3DXINLINE D3DXVECTOR3 * D3DXVec3Subtract (D3DXVECTOR3 *pOut, const D3DXVECTOR3 *pV1, const D3DXVECTOR3 *pV2)
D3DXINLINE D3DXVECTOR3 * D3DXVec3Minimize (D3DXVECTOR3 *pOut, const D3DXVECTOR3 *pV1, const D3DXVECTOR3 *pV2)
D3DXINLINE D3DXVECTOR3 * D3DXVec3Maximize (D3DXVECTOR3 *pOut, const D3DXVECTOR3 *pV1, const D3DXVECTOR3 *pV2)
D3DXINLINE D3DXVECTOR3 * D3DXVec3Scale (D3DXVECTOR3 *pOut, const D3DXVECTOR3 *pV, float s)
D3DXINLINE D3DXVECTOR3 * D3DXVec3Lerp (D3DXVECTOR3 *pOut, const D3DXVECTOR3 *pV1, const D3DXVECTOR3 *pV2, float s)
D3DXINLINE float D3DXVec4Length (const D3DXVECTOR4 *pV)
D3DXINLINE float D3DXVec4LengthSq (const D3DXVECTOR4 *pV)
D3DXINLINE float D3DXVec4Dot (const D3DXVECTOR4 *pV1, const D3DXVECTOR4 *pV2)
D3DXINLINE D3DXVECTOR4 * D3DXVec4Add (D3DXVECTOR4 *pOut, const D3DXVECTOR4 *pV1, const D3DXVECTOR4 *pV2)
D3DXINLINE D3DXVECTOR4 * D3DXVec4Subtract (D3DXVECTOR4 *pOut, const D3DXVECTOR4 *pV1, const D3DXVECTOR4 *pV2)
D3DXINLINE D3DXVECTOR4 * D3DXVec4Minimize (D3DXVECTOR4 *pOut, const D3DXVECTOR4 *pV1, const D3DXVECTOR4 *pV2)
D3DXINLINE D3DXVECTOR4 * D3DXVec4Maximize (D3DXVECTOR4 *pOut, const D3DXVECTOR4 *pV1, const D3DXVECTOR4 *pV2)
D3DXINLINE D3DXVECTOR4 * D3DXVec4Scale (D3DXVECTOR4 *pOut, const D3DXVECTOR4 *pV, float s)
D3DXINLINE D3DXVECTOR4 * D3DXVec4Lerp (D3DXVECTOR4 *pOut, const D3DXVECTOR4 *pV1, const D3DXVECTOR4 *pV2, float s)
D3DXINLINE D3DXMATRIX * D3DXMatrixIdentity (D3DXMATRIX *pOut)
D3DXINLINE BOOL D3DXMatrixIsIdentity (const D3DXMATRIX *pM)
D3DXINLINE float D3DXQuaternionLength (const D3DXQUATERNION *pQ)
D3DXINLINE float D3DXQuaternionLengthSq (const D3DXQUATERNION *pQ)
D3DXINLINE float D3DXQuaternionDot (const D3DXQUATERNION *pQ1, const D3DXQUATERNION *pQ2)
D3DXINLINE D3DXQUATERNION * D3DXQuaternionIdentity (D3DXQUATERNION *pOut)
D3DXINLINE BOOL D3DXQuaternionIsIdentity (const D3DXQUATERNION *pQ)
D3DXINLINE D3DXQUATERNION * D3DXQuaternionConjugate (D3DXQUATERNION *pOut, const D3DXQUATERNION *pQ)
D3DXINLINE float D3DXPlaneDot (const D3DXPLANE *pP, const D3DXVECTOR4 *pV)
D3DXINLINE float D3DXPlaneDotCoord (const D3DXPLANE *pP, const D3DXVECTOR3 *pV)
D3DXINLINE float D3DXPlaneDotNormal (const D3DXPLANE *pP, const D3DXVECTOR3 *pV)
D3DXINLINE D3DXCOLOR * D3DXColorNegative (D3DXCOLOR *pOut, const D3DXCOLOR *pC)
D3DXINLINE D3DXCOLOR * D3DXColorAdd (D3DXCOLOR *pOut, const D3DXCOLOR *pC1, const D3DXCOLOR *pC2)
D3DXINLINE D3DXCOLOR * D3DXColorSubtract (D3DXCOLOR *pOut, const D3DXCOLOR *pC1, const D3DXCOLOR *pC2)
D3DXINLINE D3DXCOLOR * D3DXColorScale (D3DXCOLOR *pOut, const D3DXCOLOR *pC, float s)
D3DXINLINE D3DXCOLOR * D3DXColorModulate (D3DXCOLOR *pOut, const D3DXCOLOR *pC1, const D3DXCOLOR *pC2)
D3DXINLINE D3DXCOLOR * D3DXColorLerp (D3DXCOLOR *pOut, const D3DXCOLOR *pC1, const D3DXCOLOR *pC2, float s)
Macro Definition Documentation
#define __D3DXMATH_INL__
Function Documentation
D3DXINLINE D3DXCOLOR* D3DXColorAdd (D3DXCOLOR * pOut, const D3DXCOLOR * pC1, const D3DXCOLOR * pC2)
D3DXINLINE D3DXCOLOR* D3DXColorLerp (D3DXCOLOR * pOut, const D3DXCOLOR * pC1, const D3DXCOLOR * pC2, float s)
D3DXINLINE D3DXCOLOR* D3DXColorModulate (D3DXCOLOR * pOut, const D3DXCOLOR * pC1, const D3DXCOLOR * pC2)
D3DXINLINE D3DXCOLOR* D3DXColorNegative (D3DXCOLOR * pOut, const D3DXCOLOR * pC)
D3DXINLINE D3DXCOLOR* D3DXColorScale (D3DXCOLOR * pOut, const D3DXCOLOR * pC, float s)
D3DXINLINE D3DXCOLOR* D3DXColorSubtract (D3DXCOLOR * pOut, const D3DXCOLOR * pC1, const D3DXCOLOR * pC2)
D3DXINLINE D3DXMATRIX* D3DXMatrixIdentity (D3DXMATRIX * pOut)
Referenced by CD3DArcBall::CD3DArcBall(), CD3DFrame::CD3DFrame(), GRigid::Disp(), GRigid::DispJet(), GWorld::DispNetJet(), GRigid::DispObject(), CD3DArcBall::HandleMouseMessages(), CMyD3DApplication::RestoreDeviceObjects(), Text3D(), and CMyD3DApplication::ViewSet().
D3DXINLINE BOOL D3DXMatrixIsIdentity (const D3DXMATRIX * pM)
D3DXINLINE float D3DXPlaneDot (const D3DXPLANE * pP, const D3DXVECTOR4 * pV)
D3DXINLINE float D3DXPlaneDotCoord (const D3DXPLANE * pP, const D3DXVECTOR3 * pV)
D3DXINLINE float D3DXPlaneDotNormal (const D3DXPLANE * pP, const D3DXVECTOR3 * pV)
D3DXINLINE D3DXQUATERNION* D3DXQuaternionConjugate (D3DXQUATERNION * pOut, const D3DXQUATERNION * pQ)
D3DXINLINE float D3DXQuaternionDot (const D3DXQUATERNION * pQ1, const D3DXQUATERNION * pQ2)
D3DXINLINE D3DXQUATERNION* D3DXQuaternionIdentity (D3DXQUATERNION * pOut)
Referenced by CD3DArcBall::CD3DArcBall().
D3DXINLINE BOOL D3DXQuaternionIsIdentity (const D3DXQUATERNION * pQ)
D3DXINLINE float D3DXQuaternionLength (const D3DXQUATERNION * pQ)
D3DXINLINE float D3DXQuaternionLengthSq (const D3DXQUATERNION * pQ)
D3DXINLINE D3DXVECTOR2* D3DXVec2Add (D3DXVECTOR2 * pOut, const D3DXVECTOR2 * pV1, const D3DXVECTOR2 * pV2)
D3DXINLINE float D3DXVec2CCW (const D3DXVECTOR2 * pV1, const D3DXVECTOR2 * pV2)
D3DXINLINE float D3DXVec2Dot (const D3DXVECTOR2 * pV1, const D3DXVECTOR2 * pV2)
D3DXINLINE float D3DXVec2Length (const D3DXVECTOR2 * pV)
D3DXINLINE float D3DXVec2LengthSq (const D3DXVECTOR2 * pV)
D3DXINLINE D3DXVECTOR2* D3DXVec2Lerp (D3DXVECTOR2 * pOut, const D3DXVECTOR2 * pV1, const D3DXVECTOR2 * pV2, float s)
D3DXINLINE D3DXVECTOR2* D3DXVec2Maximize (D3DXVECTOR2 * pOut, const D3DXVECTOR2 * pV1, const D3DXVECTOR2 * pV2)
D3DXINLINE D3DXVECTOR2* D3DXVec2Minimize (D3DXVECTOR2 * pOut, const D3DXVECTOR2 * pV1, const D3DXVECTOR2 * pV2)
D3DXINLINE D3DXVECTOR2* D3DXVec2Scale (D3DXVECTOR2 * pOut, const D3DXVECTOR2 * pV, float s)
D3DXINLINE D3DXVECTOR2* D3DXVec2Subtract (D3DXVECTOR2 * pOut, const D3DXVECTOR2 * pV1, const D3DXVECTOR2 * pV2)
D3DXINLINE D3DXVECTOR3* D3DXVec3Add (D3DXVECTOR3 * pOut, const D3DXVECTOR3 * pV1, const D3DXVECTOR3 * pV2)
D3DXINLINE D3DXVECTOR3* D3DXVec3Cross (D3DXVECTOR3 * pOut, const D3DXVECTOR3 * pV1, const D3DXVECTOR3 * pV2)
D3DXINLINE float D3DXVec3Dot (const D3DXVECTOR3 * pV1, const D3DXVECTOR3 * pV2)
D3DXINLINE float D3DXVec3Length (const D3DXVECTOR3 * pV)
D3DXINLINE float D3DXVec3LengthSq (const D3DXVECTOR3 * pV)
D3DXINLINE D3DXVECTOR3* D3DXVec3Lerp (D3DXVECTOR3 * pOut, const D3DXVECTOR3 * pV1, const D3DXVECTOR3 * pV2, float s)
D3DXINLINE D3DXVECTOR3* D3DXVec3Maximize (D3DXVECTOR3 * pOut, const D3DXVECTOR3 * pV1, const D3DXVECTOR3 * pV2)
D3DXINLINE D3DXVECTOR3* D3DXVec3Minimize (D3DXVECTOR3 * pOut, const D3DXVECTOR3 * pV1, const D3DXVECTOR3 * pV2)
D3DXINLINE D3DXVECTOR3* D3DXVec3Scale (D3DXVECTOR3 * pOut, const D3DXVECTOR3 * pV, float s)
D3DXINLINE D3DXVECTOR3* D3DXVec3Subtract (D3DXVECTOR3 * pOut, const D3DXVECTOR3 * pV1, const D3DXVECTOR3 * pV2)
D3DXINLINE D3DXVECTOR4* D3DXVec4Add (D3DXVECTOR4 * pOut, const D3DXVECTOR4 * pV1, const D3DXVECTOR4 * pV2)
D3DXINLINE float D3DXVec4Dot (const D3DXVECTOR4 * pV1, const D3DXVECTOR4 * pV2)
D3DXINLINE float D3DXVec4Length (const D3DXVECTOR4 * pV)
D3DXINLINE float D3DXVec4LengthSq (const D3DXVECTOR4 * pV)
D3DXINLINE D3DXVECTOR4* D3DXVec4Lerp (D3DXVECTOR4 * pOut, const D3DXVECTOR4 * pV1, const D3DXVECTOR4 * pV2, float s)
D3DXINLINE D3DXVECTOR4* D3DXVec4Maximize (D3DXVECTOR4 * pOut, const D3DXVECTOR4 * pV1, const D3DXVECTOR4 * pV2)
D3DXINLINE D3DXVECTOR4* D3DXVec4Minimize (D3DXVECTOR4 * pOut, const D3DXVECTOR4 * pV1, const D3DXVECTOR4 * pV2)
D3DXINLINE D3DXVECTOR4* D3DXVec4Scale (D3DXVECTOR4 * pOut, const D3DXVECTOR4 * pV, float s)
D3DXINLINE D3DXVECTOR4* D3DXVec4Subtract (D3DXVECTOR4 * pOut, const D3DXVECTOR4 * pV1, const D3DXVECTOR4 * pV2)