RigidChips: microsoft directx 9.0 sdk (summer 2004)/Include/d3dx8math.h File Reference
d3dx8math.h File Reference
#include "d3dx8.h"
#include <math.h>
#include "d3dx8math.inl"
Classes
struct D3DXVECTOR2
struct D3DXVECTOR4
__cplusplus
struct D3DXQUATERNION
struct D3DXPLANE
struct D3DXCOLOR
Macros
#define D3DX_PI ((FLOAT) 3.141592654f)
#define D3DX_1BYPI ((FLOAT) 0.318309886f)
#define D3DXToRadian(degree) ((degree) * (D3DX_PI / 180.0f))
#define D3DXToDegree(radian) ((radian) * (180.0f / D3DX_PI))
#define _ALIGN_16
__cplusplus
#define D3DXMATRIXA16 _ALIGN_16 _D3DXMATRIXA16
#define INTERFACE ID3DXMatrixStack
Typedefs
typedef struct D3DXVECTOR2 D3DXVECTOR2
typedef struct D3DXVECTOR2 * LPD3DXVECTOR2
typedef struct _D3DVECTOR D3DXVECTOR3
__cplusplus
typedef struct _D3DVECTOR * LPD3DXVECTOR3
typedef struct D3DXVECTOR4 D3DXVECTOR4
__cplusplus
typedef struct D3DXVECTOR4 * LPD3DXVECTOR4
typedef struct _D3DMATRIX D3DXMATRIX
__cplusplus
typedef struct _D3DMATRIX * LPD3DXMATRIX
typedef D3DXMATRIX _D3DXMATRIXA16
__cplusplus
typedef D3DXMATRIXA16 * LPD3DXMATRIXA16
typedef struct D3DXQUATERNION D3DXQUATERNION
typedef struct D3DXQUATERNION * LPD3DXQUATERNION
typedef struct D3DXPLANE D3DXPLANE
typedef struct D3DXPLANE * LPD3DXPLANE
typedef struct D3DXCOLOR D3DXCOLOR
typedef struct D3DXCOLOR * LPD3DXCOLOR
typedef interface ID3DXMatrixStack ID3DXMatrixStack
typedef interface ID3DXMatrixStack * LPD3DXMATRIXSTACK
Functions
FLOAT D3DXVec2Length (CONST D3DXVECTOR2 *pV)
FLOAT D3DXVec2LengthSq (CONST D3DXVECTOR2 *pV)
FLOAT D3DXVec2Dot (CONST D3DXVECTOR2 *pV1, CONST D3DXVECTOR2 *pV2)
FLOAT D3DXVec2CCW (CONST D3DXVECTOR2 *pV1, CONST D3DXVECTOR2 *pV2)
D3DXVECTOR2 * D3DXVec2Add (D3DXVECTOR2 *pOut, CONST D3DXVECTOR2 *pV1, CONST D3DXVECTOR2 *pV2)
D3DXVECTOR2 * D3DXVec2Subtract (D3DXVECTOR2 *pOut, CONST D3DXVECTOR2 *pV1, CONST D3DXVECTOR2 *pV2)
D3DXVECTOR2 * D3DXVec2Minimize (D3DXVECTOR2 *pOut, CONST D3DXVECTOR2 *pV1, CONST D3DXVECTOR2 *pV2)
D3DXVECTOR2 * D3DXVec2Maximize (D3DXVECTOR2 *pOut, CONST D3DXVECTOR2 *pV1, CONST D3DXVECTOR2 *pV2)
D3DXVECTOR2 * D3DXVec2Scale (D3DXVECTOR2 *pOut, CONST D3DXVECTOR2 *pV, FLOAT s)
D3DXVECTOR2 * D3DXVec2Lerp (D3DXVECTOR2 *pOut, CONST D3DXVECTOR2 *pV1, CONST D3DXVECTOR2 *pV2, FLOAT s)
D3DXVECTOR2 *WINAPI D3DXVec2Normalize (D3DXVECTOR2 *pOut, CONST D3DXVECTOR2 *pV)
D3DXVECTOR2 *WINAPI D3DXVec2Hermite (D3DXVECTOR2 *pOut, CONST D3DXVECTOR2 *pV1, CONST D3DXVECTOR2 *pT1, CONST D3DXVECTOR2 *pV2, CONST D3DXVECTOR2 *pT2, FLOAT s)
D3DXVECTOR2 *WINAPI D3DXVec2CatmullRom (D3DXVECTOR2 *pOut, CONST D3DXVECTOR2 *pV0, CONST D3DXVECTOR2 *pV1, CONST D3DXVECTOR2 *pV2, CONST D3DXVECTOR2 *pV3, FLOAT s)
D3DXVECTOR2 *WINAPI D3DXVec2BaryCentric (D3DXVECTOR2 *pOut, CONST D3DXVECTOR2 *pV1, CONST D3DXVECTOR2 *pV2, CONST D3DXVECTOR2 *pV3, FLOAT f, FLOAT g)
D3DXVECTOR4 *WINAPI D3DXVec2Transform (D3DXVECTOR4 *pOut, CONST D3DXVECTOR2 *pV, CONST D3DXMATRIX *pM)
D3DXVECTOR2 *WINAPI D3DXVec2TransformCoord (D3DXVECTOR2 *pOut, CONST D3DXVECTOR2 *pV, CONST D3DXMATRIX *pM)
D3DXVECTOR2 *WINAPI D3DXVec2TransformNormal (D3DXVECTOR2 *pOut, CONST D3DXVECTOR2 *pV, CONST D3DXMATRIX *pM)
FLOAT D3DXVec3Length (CONST D3DXVECTOR3 *pV)
FLOAT D3DXVec3LengthSq (CONST D3DXVECTOR3 *pV)
FLOAT D3DXVec3Dot (CONST D3DXVECTOR3 *pV1, CONST D3DXVECTOR3 *pV2)
D3DXVECTOR3 * D3DXVec3Cross (D3DXVECTOR3 *pOut, CONST D3DXVECTOR3 *pV1, CONST D3DXVECTOR3 *pV2)
D3DXVECTOR3 * D3DXVec3Add (D3DXVECTOR3 *pOut, CONST D3DXVECTOR3 *pV1, CONST D3DXVECTOR3 *pV2)
D3DXVECTOR3 * D3DXVec3Subtract (D3DXVECTOR3 *pOut, CONST D3DXVECTOR3 *pV1, CONST D3DXVECTOR3 *pV2)
D3DXVECTOR3 * D3DXVec3Minimize (D3DXVECTOR3 *pOut, CONST D3DXVECTOR3 *pV1, CONST D3DXVECTOR3 *pV2)
D3DXVECTOR3 * D3DXVec3Maximize (D3DXVECTOR3 *pOut, CONST D3DXVECTOR3 *pV1, CONST D3DXVECTOR3 *pV2)
D3DXVECTOR3 * D3DXVec3Scale (D3DXVECTOR3 *pOut, CONST D3DXVECTOR3 *pV, FLOAT s)
D3DXVECTOR3 * D3DXVec3Lerp (D3DXVECTOR3 *pOut, CONST D3DXVECTOR3 *pV1, CONST D3DXVECTOR3 *pV2, FLOAT s)
D3DXVECTOR3 *WINAPI D3DXVec3Normalize (D3DXVECTOR3 *pOut, CONST D3DXVECTOR3 *pV)
D3DXVECTOR3 *WINAPI D3DXVec3Hermite (D3DXVECTOR3 *pOut, CONST D3DXVECTOR3 *pV1, CONST D3DXVECTOR3 *pT1, CONST D3DXVECTOR3 *pV2, CONST D3DXVECTOR3 *pT2, FLOAT s)
D3DXVECTOR3 *WINAPI D3DXVec3CatmullRom (D3DXVECTOR3 *pOut, CONST D3DXVECTOR3 *pV0, CONST D3DXVECTOR3 *pV1, CONST D3DXVECTOR3 *pV2, CONST D3DXVECTOR3 *pV3, FLOAT s)
D3DXVECTOR3 *WINAPI D3DXVec3BaryCentric (D3DXVECTOR3 *pOut, CONST D3DXVECTOR3 *pV1, CONST D3DXVECTOR3 *pV2, CONST D3DXVECTOR3 *pV3, FLOAT f, FLOAT g)
D3DXVECTOR4 *WINAPI D3DXVec3Transform (D3DXVECTOR4 *pOut, CONST D3DXVECTOR3 *pV, CONST D3DXMATRIX *pM)
D3DXVECTOR3 *WINAPI D3DXVec3TransformCoord (D3DXVECTOR3 *pOut, CONST D3DXVECTOR3 *pV, CONST D3DXMATRIX *pM)
D3DXVECTOR3 *WINAPI D3DXVec3TransformNormal (D3DXVECTOR3 *pOut, CONST D3DXVECTOR3 *pV, CONST D3DXMATRIX *pM)
D3DXVECTOR3 *WINAPI D3DXVec3Project (D3DXVECTOR3 *pOut, CONST D3DXVECTOR3 *pV, CONST D3DVIEWPORT8 *pViewport, CONST D3DXMATRIX *pProjection, CONST D3DXMATRIX *pView, CONST D3DXMATRIX *pWorld)
D3DXVECTOR3 *WINAPI D3DXVec3Unproject (D3DXVECTOR3 *pOut, CONST D3DXVECTOR3 *pV, CONST D3DVIEWPORT8 *pViewport, CONST D3DXMATRIX *pProjection, CONST D3DXMATRIX *pView, CONST D3DXMATRIX *pWorld)
FLOAT D3DXVec4Length (CONST D3DXVECTOR4 *pV)
FLOAT D3DXVec4LengthSq (CONST D3DXVECTOR4 *pV)
FLOAT D3DXVec4Dot (CONST D3DXVECTOR4 *pV1, CONST D3DXVECTOR4 *pV2)
D3DXVECTOR4 * D3DXVec4Add (D3DXVECTOR4 *pOut, CONST D3DXVECTOR4 *pV1, CONST D3DXVECTOR4 *pV2)
D3DXVECTOR4 * D3DXVec4Subtract (D3DXVECTOR4 *pOut, CONST D3DXVECTOR4 *pV1, CONST D3DXVECTOR4 *pV2)
D3DXVECTOR4 * D3DXVec4Minimize (D3DXVECTOR4 *pOut, CONST D3DXVECTOR4 *pV1, CONST D3DXVECTOR4 *pV2)
D3DXVECTOR4 * D3DXVec4Maximize (D3DXVECTOR4 *pOut, CONST D3DXVECTOR4 *pV1, CONST D3DXVECTOR4 *pV2)
D3DXVECTOR4 * D3DXVec4Scale (D3DXVECTOR4 *pOut, CONST D3DXVECTOR4 *pV, FLOAT s)
D3DXVECTOR4 * D3DXVec4Lerp (D3DXVECTOR4 *pOut, CONST D3DXVECTOR4 *pV1, CONST D3DXVECTOR4 *pV2, FLOAT s)
D3DXVECTOR4 *WINAPI D3DXVec4Cross (D3DXVECTOR4 *pOut, CONST D3DXVECTOR4 *pV1, CONST D3DXVECTOR4 *pV2, CONST D3DXVECTOR4 *pV3)
D3DXVECTOR4 *WINAPI D3DXVec4Normalize (D3DXVECTOR4 *pOut, CONST D3DXVECTOR4 *pV)
D3DXVECTOR4 *WINAPI D3DXVec4Hermite (D3DXVECTOR4 *pOut, CONST D3DXVECTOR4 *pV1, CONST D3DXVECTOR4 *pT1, CONST D3DXVECTOR4 *pV2, CONST D3DXVECTOR4 *pT2, FLOAT s)
D3DXVECTOR4 *WINAPI D3DXVec4CatmullRom (D3DXVECTOR4 *pOut, CONST D3DXVECTOR4 *pV0, CONST D3DXVECTOR4 *pV1, CONST D3DXVECTOR4 *pV2, CONST D3DXVECTOR4 *pV3, FLOAT s)
D3DXVECTOR4 *WINAPI D3DXVec4BaryCentric (D3DXVECTOR4 *pOut, CONST D3DXVECTOR4 *pV1, CONST D3DXVECTOR4 *pV2, CONST D3DXVECTOR4 *pV3, FLOAT f, FLOAT g)
D3DXVECTOR4 *WINAPI D3DXVec4Transform (D3DXVECTOR4 *pOut, CONST D3DXVECTOR4 *pV, CONST D3DXMATRIX *pM)
D3DXMATRIX * D3DXMatrixIdentity (D3DXMATRIX *pOut)
BOOL D3DXMatrixIsIdentity (CONST D3DXMATRIX *pM)
FLOAT WINAPI D3DXMatrixfDeterminant (CONST D3DXMATRIX *pM)
D3DXMATRIX *WINAPI D3DXMatrixTranspose (D3DXMATRIX *pOut, CONST D3DXMATRIX *pM)
D3DXMATRIX *WINAPI D3DXMatrixMultiply (D3DXMATRIX *pOut, CONST D3DXMATRIX *pM1, CONST D3DXMATRIX *pM2)
D3DXMATRIX *WINAPI D3DXMatrixMultiplyTranspose (D3DXMATRIX *pOut, CONST D3DXMATRIX *pM1, CONST D3DXMATRIX *pM2)
D3DXMATRIX *WINAPI D3DXMatrixInverse (D3DXMATRIX *pOut, FLOAT *pDeterminant, CONST D3DXMATRIX *pM)
D3DXMATRIX *WINAPI D3DXMatrixScaling (D3DXMATRIX *pOut, FLOAT sx, FLOAT sy, FLOAT sz)
D3DXMATRIX *WINAPI D3DXMatrixTranslation (D3DXMATRIX *pOut, FLOAT x, FLOAT y, FLOAT z)
D3DXMATRIX *WINAPI D3DXMatrixRotationX (D3DXMATRIX *pOut, FLOAT Angle)
D3DXMATRIX *WINAPI D3DXMatrixRotationY (D3DXMATRIX *pOut, FLOAT Angle)
D3DXMATRIX *WINAPI D3DXMatrixRotationZ (D3DXMATRIX *pOut, FLOAT Angle)
D3DXMATRIX *WINAPI D3DXMatrixRotationAxis (D3DXMATRIX *pOut, CONST D3DXVECTOR3 *pV, FLOAT Angle)
D3DXMATRIX *WINAPI D3DXMatrixRotationQuaternion (D3DXMATRIX *pOut, CONST D3DXQUATERNION *pQ)
D3DXMATRIX *WINAPI D3DXMatrixRotationYawPitchRoll (D3DXMATRIX *pOut, FLOAT Yaw, FLOAT Pitch, FLOAT Roll)
D3DXMATRIX *WINAPI D3DXMatrixTransformation (D3DXMATRIX *pOut, CONST D3DXVECTOR3 *pScalingCenter, CONST D3DXQUATERNION *pScalingRotation, CONST D3DXVECTOR3 *pScaling, CONST D3DXVECTOR3 *pRotationCenter, CONST D3DXQUATERNION *pRotation, CONST D3DXVECTOR3 *pTranslation)
D3DXMATRIX *WINAPI D3DXMatrixAffineTransformation (D3DXMATRIX *pOut, FLOAT Scaling, CONST D3DXVECTOR3 *pRotationCenter, CONST D3DXQUATERNION *pRotation, CONST D3DXVECTOR3 *pTranslation)
D3DXMATRIX *WINAPI D3DXMatrixLookAtRH (D3DXMATRIX *pOut, CONST D3DXVECTOR3 *pEye, CONST D3DXVECTOR3 *pAt, CONST D3DXVECTOR3 *pUp)
D3DXMATRIX *WINAPI D3DXMatrixLookAtLH (D3DXMATRIX *pOut, CONST D3DXVECTOR3 *pEye, CONST D3DXVECTOR3 *pAt, CONST D3DXVECTOR3 *pUp)
D3DXMATRIX *WINAPI D3DXMatrixPerspectiveRH (D3DXMATRIX *pOut, FLOAT w, FLOAT h, FLOAT zn, FLOAT zf)
D3DXMATRIX *WINAPI D3DXMatrixPerspectiveLH (D3DXMATRIX *pOut, FLOAT w, FLOAT h, FLOAT zn, FLOAT zf)
D3DXMATRIX *WINAPI D3DXMatrixPerspectiveFovRH (D3DXMATRIX *pOut, FLOAT fovy, FLOAT Aspect, FLOAT zn, FLOAT zf)
D3DXMATRIX *WINAPI D3DXMatrixPerspectiveFovLH (D3DXMATRIX *pOut, FLOAT fovy, FLOAT Aspect, FLOAT zn, FLOAT zf)
D3DXMATRIX *WINAPI D3DXMatrixPerspectiveOffCenterRH (D3DXMATRIX *pOut, FLOAT l, FLOAT r, FLOAT b, FLOAT t, FLOAT zn, FLOAT zf)
D3DXMATRIX *WINAPI D3DXMatrixPerspectiveOffCenterLH (D3DXMATRIX *pOut, FLOAT l, FLOAT r, FLOAT b, FLOAT t, FLOAT zn, FLOAT zf)
D3DXMATRIX *WINAPI D3DXMatrixOrthoRH (D3DXMATRIX *pOut, FLOAT w, FLOAT h, FLOAT zn, FLOAT zf)
D3DXMATRIX *WINAPI D3DXMatrixOrthoLH (D3DXMATRIX *pOut, FLOAT w, FLOAT h, FLOAT zn, FLOAT zf)
D3DXMATRIX *WINAPI D3DXMatrixOrthoOffCenterRH (D3DXMATRIX *pOut, FLOAT l, FLOAT r, FLOAT b, FLOAT t, FLOAT zn, FLOAT zf)
D3DXMATRIX *WINAPI D3DXMatrixOrthoOffCenterLH (D3DXMATRIX *pOut, FLOAT l, FLOAT r, FLOAT b, FLOAT t, FLOAT zn, FLOAT zf)
D3DXMATRIX *WINAPI D3DXMatrixShadow (D3DXMATRIX *pOut, CONST D3DXVECTOR4 *pLight, CONST D3DXPLANE *pPlane)
D3DXMATRIX *WINAPI D3DXMatrixReflect (D3DXMATRIX *pOut, CONST D3DXPLANE *pPlane)
FLOAT D3DXQuaternionLength (CONST D3DXQUATERNION *pQ)
FLOAT D3DXQuaternionLengthSq (CONST D3DXQUATERNION *pQ)
FLOAT D3DXQuaternionDot (CONST D3DXQUATERNION *pQ1, CONST D3DXQUATERNION *pQ2)
D3DXQUATERNION * D3DXQuaternionIdentity (D3DXQUATERNION *pOut)
BOOL D3DXQuaternionIsIdentity (CONST D3DXQUATERNION *pQ)
D3DXQUATERNION * D3DXQuaternionConjugate (D3DXQUATERNION *pOut, CONST D3DXQUATERNION *pQ)
void WINAPI D3DXQuaternionToAxisAngle (CONST D3DXQUATERNION *pQ, D3DXVECTOR3 *pAxis, FLOAT *pAngle)
D3DXQUATERNION *WINAPI D3DXQuaternionRotationMatrix (D3DXQUATERNION *pOut, CONST D3DXMATRIX *pM)
D3DXQUATERNION *WINAPI D3DXQuaternionRotationAxis (D3DXQUATERNION *pOut, CONST D3DXVECTOR3 *pV, FLOAT Angle)
D3DXQUATERNION *WINAPI D3DXQuaternionRotationYawPitchRoll (D3DXQUATERNION *pOut, FLOAT Yaw, FLOAT Pitch, FLOAT Roll)
D3DXQUATERNION *WINAPI D3DXQuaternionMultiply (D3DXQUATERNION *pOut, CONST D3DXQUATERNION *pQ1, CONST D3DXQUATERNION *pQ2)
D3DXQUATERNION *WINAPI D3DXQuaternionNormalize (D3DXQUATERNION *pOut, CONST D3DXQUATERNION *pQ)
D3DXQUATERNION *WINAPI D3DXQuaternionInverse (D3DXQUATERNION *pOut, CONST D3DXQUATERNION *pQ)
D3DXQUATERNION *WINAPI D3DXQuaternionLn (D3DXQUATERNION *pOut, CONST D3DXQUATERNION *pQ)
D3DXQUATERNION *WINAPI D3DXQuaternionExp (D3DXQUATERNION *pOut, CONST D3DXQUATERNION *pQ)
D3DXQUATERNION *WINAPI D3DXQuaternionSlerp (D3DXQUATERNION *pOut, CONST D3DXQUATERNION *pQ1, CONST D3DXQUATERNION *pQ2, FLOAT t)
D3DXQUATERNION *WINAPI D3DXQuaternionSquad (D3DXQUATERNION *pOut, CONST D3DXQUATERNION *pQ1, CONST D3DXQUATERNION *pA, CONST D3DXQUATERNION *pB, CONST D3DXQUATERNION *pC, FLOAT t)
void WINAPI D3DXQuaternionSquadSetup (D3DXQUATERNION *pAOut, D3DXQUATERNION *pBOut, D3DXQUATERNION *pCOut, CONST D3DXQUATERNION *pQ0, CONST D3DXQUATERNION *pQ1, CONST D3DXQUATERNION *pQ2, CONST D3DXQUATERNION *pQ3)
D3DXQUATERNION *WINAPI D3DXQuaternionBaryCentric (D3DXQUATERNION *pOut, CONST D3DXQUATERNION *pQ1, CONST D3DXQUATERNION *pQ2, CONST D3DXQUATERNION *pQ3, FLOAT f, FLOAT g)
FLOAT D3DXPlaneDot (CONST D3DXPLANE *pP, CONST D3DXVECTOR4 *pV)
FLOAT D3DXPlaneDotCoord (CONST D3DXPLANE *pP, CONST D3DXVECTOR3 *pV)
FLOAT D3DXPlaneDotNormal (CONST D3DXPLANE *pP, CONST D3DXVECTOR3 *pV)
D3DXPLANE *WINAPI D3DXPlaneNormalize (D3DXPLANE *pOut, CONST D3DXPLANE *pP)
D3DXVECTOR3 *WINAPI D3DXPlaneIntersectLine (D3DXVECTOR3 *pOut, CONST D3DXPLANE *pP, CONST D3DXVECTOR3 *pV1, CONST D3DXVECTOR3 *pV2)
D3DXPLANE *WINAPI D3DXPlaneFromPointNormal (D3DXPLANE *pOut, CONST D3DXVECTOR3 *pPoint, CONST D3DXVECTOR3 *pNormal)
D3DXPLANE *WINAPI D3DXPlaneFromPoints (D3DXPLANE *pOut, CONST D3DXVECTOR3 *pV1, CONST D3DXVECTOR3 *pV2, CONST D3DXVECTOR3 *pV3)
D3DXPLANE *WINAPI D3DXPlaneTransform (D3DXPLANE *pOut, CONST D3DXPLANE *pP, CONST D3DXMATRIX *pM)
D3DXCOLOR * D3DXColorNegative (D3DXCOLOR *pOut, CONST D3DXCOLOR *pC)
D3DXCOLOR * D3DXColorAdd (D3DXCOLOR *pOut, CONST D3DXCOLOR *pC1, CONST D3DXCOLOR *pC2)
D3DXCOLOR * D3DXColorSubtract (D3DXCOLOR *pOut, CONST D3DXCOLOR *pC1, CONST D3DXCOLOR *pC2)
D3DXCOLOR * D3DXColorScale (D3DXCOLOR *pOut, CONST D3DXCOLOR *pC, FLOAT s)
D3DXCOLOR * D3DXColorModulate (D3DXCOLOR *pOut, CONST D3DXCOLOR *pC1, CONST D3DXCOLOR *pC2)
D3DXCOLOR * D3DXColorLerp (D3DXCOLOR *pOut, CONST D3DXCOLOR *pC1, CONST D3DXCOLOR *pC2, FLOAT s)
D3DXCOLOR *WINAPI D3DXColorAdjustSaturation (D3DXCOLOR *pOut, CONST D3DXCOLOR *pC, FLOAT s)
D3DXCOLOR *WINAPI D3DXColorAdjustContrast (D3DXCOLOR *pOut, CONST D3DXCOLOR *pC, FLOAT c)
FLOAT WINAPI D3DXFresnelTerm (FLOAT CosTheta, FLOAT RefractionIndex)
DEFINE_GUID (IID_ID3DXMatrixStack, 0xe3357330, 0xcc5e, 0x11d2, 0xa4, 0x34, 0x0, 0xa0, 0xc9, 0x6, 0x29, 0xa8)
DECLARE_INTERFACE_ (ID3DXMatrixStack, IUnknown)
HRESULT WINAPI D3DXCreateMatrixStack (DWORD Flags, LPD3DXMATRIXSTACK *ppStack)
Macro Definition Documentation
#define _ALIGN_16
__cplusplus
#define D3DX_1BYPI ((FLOAT) 0.318309886f)
#define D3DX_PI ((FLOAT) 3.141592654f)
Referenced by CD3DCamera::CD3DCamera().
#define D3DXMATRIXA16 _ALIGN_16 _D3DXMATRIXA16
#define D3DXToDegree (radian) ((radian) * (180.0f / D3DX_PI))
#define D3DXToRadian (degree) ((degree) * (D3DX_PI / 180.0f))
Referenced by CMyD3DApplication::Render().
#define INTERFACE ID3DXMatrixStack
Typedef Documentation
typedef D3DXMATRIX _D3DXMATRIXA16
__cplusplus
__cplusplus
typedef struct D3DXCOLOR D3DXCOLOR
typedef struct _D3DMATRIX D3DXMATRIX
__cplusplus
typedef struct D3DXPLANE D3DXPLANE
typedef struct D3DXQUATERNION D3DXQUATERNION
typedef struct D3DXVECTOR2 D3DXVECTOR2
typedef struct _D3DVECTOR D3DXVECTOR3
__cplusplus
typedef struct D3DXVECTOR4 D3DXVECTOR4
__cplusplus
typedef interface ID3DXMatrixStack ID3DXMatrixStack
typedef struct D3DXCOLOR * LPD3DXCOLOR
typedef struct _D3DMATRIX * LPD3DXMATRIX
typedef D3DXMATRIXA16* LPD3DXMATRIXA16
typedef interface ID3DXMatrixStack* LPD3DXMATRIXSTACK
typedef struct D3DXPLANE * LPD3DXPLANE
typedef struct D3DXQUATERNION * LPD3DXQUATERNION
typedef struct D3DXVECTOR2 * LPD3DXVECTOR2
typedef struct _D3DVECTOR * LPD3DXVECTOR3
typedef struct D3DXVECTOR4 * LPD3DXVECTOR4
Function Documentation
D3DXCOLOR* D3DXColorAdd (D3DXCOLOR * pOut, CONST D3DXCOLOR * pC1, CONST D3DXCOLOR * pC2)
D3DXCOLOR* WINAPI D3DXColorAdjustContrast (D3DXCOLOR * pOut, CONST D3DXCOLOR * pC, FLOAT c)
D3DXCOLOR* WINAPI D3DXColorAdjustSaturation (D3DXCOLOR * pOut, CONST D3DXCOLOR * pC, FLOAT s)
D3DXCOLOR* D3DXColorLerp (D3DXCOLOR * pOut, CONST D3DXCOLOR * pC1, CONST D3DXCOLOR * pC2, FLOAT s)
D3DXCOLOR* D3DXColorModulate (D3DXCOLOR * pOut, CONST D3DXCOLOR * pC1, CONST D3DXCOLOR * pC2)
D3DXCOLOR* D3DXColorNegative (D3DXCOLOR * pOut, CONST D3DXCOLOR * pC)
D3DXCOLOR* D3DXColorScale (D3DXCOLOR * pOut, CONST D3DXCOLOR * pC, FLOAT s)
D3DXCOLOR* D3DXColorSubtract (D3DXCOLOR * pOut, CONST D3DXCOLOR * pC1, CONST D3DXCOLOR * pC2)
HRESULT WINAPI D3DXCreateMatrixStack (DWORD Flags, LPD3DXMATRIXSTACK * ppStack)
FLOAT WINAPI D3DXFresnelTerm (FLOAT CosTheta, FLOAT RefractionIndex)
D3DXMATRIX* WINAPI D3DXMatrixAffineTransformation (D3DXMATRIX * pOut, FLOAT Scaling, CONST D3DXVECTOR3 * pRotationCenter, CONST D3DXQUATERNION * pRotation, CONST D3DXVECTOR3 * pTranslation)
FLOAT WINAPI D3DXMatrixfDeterminant (CONST D3DXMATRIX * pM)
D3DXMATRIX* D3DXMatrixIdentity (D3DXMATRIX * pOut)
Referenced by CD3DArcBall::CD3DArcBall(), CD3DFrame::CD3DFrame(), GRigid::Disp(), GRigid::DispJet(), GWorld::DispNetJet(), GRigid::DispObject(), CD3DArcBall::HandleMouseMessages(), CMyD3DApplication::RestoreDeviceObjects(), Text3D(), and CMyD3DApplication::ViewSet().
D3DXMATRIX* WINAPI D3DXMatrixInverse (D3DXMATRIX * pOut, FLOAT * pDeterminant, CONST D3DXMATRIX * pM)
Referenced by GWorld::DispNetChipInfo(), Line2D(), CMyD3DApplication::Render(), and CD3DCamera::SetViewParams().
BOOL D3DXMatrixIsIdentity (CONST D3DXMATRIX * pM)
D3DXMATRIX* WINAPI D3DXMatrixLookAtLH (D3DXMATRIX * pOut, CONST D3DXVECTOR3 * pEye, CONST D3DXVECTOR3 * pAt, CONST D3DXVECTOR3 * pUp)
Referenced by D3DUtil_GetCubeMapViewMatrix(), CMyD3DApplication::Render(), CMyD3DApplication::RestoreDeviceObjects(), CD3DCamera::SetViewParams(), and CMyD3DApplication::ViewSet().
D3DXMATRIX* WINAPI D3DXMatrixLookAtRH (D3DXMATRIX * pOut, CONST D3DXVECTOR3 * pEye, CONST D3DXVECTOR3 * pAt, CONST D3DXVECTOR3 * pUp)
D3DXMATRIX* WINAPI D3DXMatrixMultiply (D3DXMATRIX * pOut, CONST D3DXMATRIX * pM1, CONST D3DXMATRIX * pM2)
Referenced by GRigid::Disp(), GRigid::DispJet(), GWorld::DispNetChip(), GWorld::DispNetChipInfo(), GWorld::DispNetJet(), GRigid::DispObject(), CD3DArcBall::HandleMouseMessages(), CD3DFrame::Render(), CD3DFile::Render(), and CMyD3DApplication::Render().
D3DXMATRIX* WINAPI D3DXMatrixMultiplyTranspose (D3DXMATRIX * pOut, CONST D3DXMATRIX * pM1, CONST D3DXMATRIX * pM2)
D3DXMATRIX* WINAPI D3DXMatrixOrthoLH (D3DXMATRIX * pOut, FLOAT w, FLOAT h, FLOAT zn, FLOAT zf)
D3DXMATRIX* WINAPI D3DXMatrixOrthoOffCenterLH (D3DXMATRIX * pOut, FLOAT l, FLOAT r, FLOAT b, FLOAT t, FLOAT zn, FLOAT zf)
D3DXMATRIX* WINAPI D3DXMatrixOrthoOffCenterRH (D3DXMATRIX * pOut, FLOAT l, FLOAT r, FLOAT b, FLOAT t, FLOAT zn, FLOAT zf)
D3DXMATRIX* WINAPI D3DXMatrixOrthoRH (D3DXMATRIX * pOut, FLOAT w, FLOAT h, FLOAT zn, FLOAT zf)
D3DXMATRIX* WINAPI D3DXMatrixPerspectiveFovLH (D3DXMATRIX * pOut, FLOAT fovy, FLOAT Aspect, FLOAT zn, FLOAT zf)
Referenced by CMyD3DApplication::Render(), CMyD3DApplication::RestoreDeviceObjects(), CD3DCamera::SetProjParams(), and CMyD3DApplication::ViewSet().
D3DXMATRIX* WINAPI D3DXMatrixPerspectiveFovRH (D3DXMATRIX * pOut, FLOAT fovy, FLOAT Aspect, FLOAT zn, FLOAT zf)
D3DXMATRIX* WINAPI D3DXMatrixPerspectiveLH (D3DXMATRIX * pOut, FLOAT w, FLOAT h, FLOAT zn, FLOAT zf)
D3DXMATRIX* WINAPI D3DXMatrixPerspectiveOffCenterLH (D3DXMATRIX * pOut, FLOAT l, FLOAT r, FLOAT b, FLOAT t, FLOAT zn, FLOAT zf)
D3DXMATRIX* WINAPI D3DXMatrixPerspectiveOffCenterRH (D3DXMATRIX * pOut, FLOAT l, FLOAT r, FLOAT b, FLOAT t, FLOAT zn, FLOAT zf)
D3DXMATRIX* WINAPI D3DXMatrixPerspectiveRH (D3DXMATRIX * pOut, FLOAT w, FLOAT h, FLOAT zn, FLOAT zf)
D3DXMATRIX* WINAPI D3DXMatrixReflect (D3DXMATRIX * pOut, CONST D3DXPLANE * pPlane)
D3DXMATRIX* WINAPI D3DXMatrixRotationAxis (D3DXMATRIX * pOut, CONST D3DXVECTOR3 * pV, FLOAT Angle)
D3DXMATRIX* WINAPI D3DXMatrixRotationQuaternion (D3DXMATRIX * pOut, CONST D3DXQUATERNION * pQ)
Referenced by CD3DArcBall::HandleMouseMessages().
D3DXMATRIX* WINAPI D3DXMatrixRotationX (D3DXMATRIX * pOut, FLOAT Angle)
Referenced by GRigid::DispJet(), and CMyD3DApplication::Render().
D3DXMATRIX* WINAPI D3DXMatrixRotationY (D3DXMATRIX * pOut, FLOAT Angle)
Referenced by GRigid::Disp(), GRigid::DispJet(), GWorld::DispNetChip(), GWorld::DispNetJet(), and CMyD3DApplication::Render().
D3DXMATRIX* WINAPI D3DXMatrixRotationYawPitchRoll (D3DXMATRIX * pOut, FLOAT Yaw, FLOAT Pitch, FLOAT Roll)
D3DXMATRIX* WINAPI D3DXMatrixRotationZ (D3DXMATRIX * pOut, FLOAT Angle)
Referenced by GRigid::DispJet(), GWorld::DispNetJet(), and CMyD3DApplication::Render().
D3DXMATRIX* WINAPI D3DXMatrixScaling (D3DXMATRIX * pOut, FLOAT sx, FLOAT sy, FLOAT sz)
Referenced by GRigid::Disp(), GRigid::DispJet(), GWorld::DispNetChip(), GWorld::DispNetChipInfo(), GWorld::DispNetJet(), GRigid::DispObject(), Line2D(), and CMyD3DApplication::Render().
D3DXMATRIX* WINAPI D3DXMatrixShadow (D3DXMATRIX * pOut, CONST D3DXVECTOR4 * pLight, CONST D3DXPLANE * pPlane)
D3DXMATRIX* WINAPI D3DXMatrixTransformation (D3DXMATRIX * pOut, CONST D3DXVECTOR3 * pScalingCenter, CONST D3DXQUATERNION * pScalingRotation, CONST D3DXVECTOR3 * pScaling, CONST D3DXVECTOR3 * pRotationCenter, CONST D3DXQUATERNION * pRotation, CONST D3DXVECTOR3 * pTranslation)
D3DXMATRIX* WINAPI D3DXMatrixTranslation (D3DXMATRIX * pOut, FLOAT x, FLOAT y, FLOAT z)
Referenced by GRigid::Disp(), GRigid::DispJet(), GWorld::DispNetChipInfo(), GWorld::DispNetJet(), CD3DArcBall::HandleMouseMessages(), CMyD3DApplication::Render(), and Text3D().
D3DXMATRIX* WINAPI D3DXMatrixTranspose (D3DXMATRIX * pOut, CONST D3DXMATRIX * pM)
FLOAT D3DXPlaneDot (CONST D3DXPLANE * pP, CONST D3DXVECTOR4 * pV)
FLOAT D3DXPlaneDotCoord (CONST D3DXPLANE * pP, CONST D3DXVECTOR3 * pV)
FLOAT D3DXPlaneDotNormal (CONST D3DXPLANE * pP, CONST D3DXVECTOR3 * pV)
D3DXPLANE* WINAPI D3DXPlaneFromPointNormal (D3DXPLANE * pOut, CONST D3DXVECTOR3 * pPoint, CONST D3DXVECTOR3 * pNormal)
D3DXPLANE* WINAPI D3DXPlaneFromPoints (D3DXPLANE * pOut, CONST D3DXVECTOR3 * pV1, CONST D3DXVECTOR3 * pV2, CONST D3DXVECTOR3 * pV3)
D3DXVECTOR3* WINAPI D3DXPlaneIntersectLine (D3DXVECTOR3 * pOut, CONST D3DXPLANE * pP, CONST D3DXVECTOR3 * pV1, CONST D3DXVECTOR3 * pV2)
D3DXPLANE* WINAPI D3DXPlaneNormalize (D3DXPLANE * pOut, CONST D3DXPLANE * pP)
D3DXPLANE* WINAPI D3DXPlaneTransform (D3DXPLANE * pOut, CONST D3DXPLANE * pP, CONST D3DXMATRIX * pM)
D3DXQUATERNION* WINAPI D3DXQuaternionBaryCentric (D3DXQUATERNION * pOut, CONST D3DXQUATERNION * pQ1, CONST D3DXQUATERNION * pQ2, CONST D3DXQUATERNION * pQ3, FLOAT f, FLOAT g)
D3DXQUATERNION* D3DXQuaternionConjugate (D3DXQUATERNION * pOut, CONST D3DXQUATERNION * pQ)
FLOAT D3DXQuaternionDot (CONST D3DXQUATERNION * pQ1, CONST D3DXQUATERNION * pQ2)
D3DXQUATERNION* WINAPI D3DXQuaternionExp (D3DXQUATERNION * pOut, CONST D3DXQUATERNION * pQ)
D3DXQUATERNION* D3DXQuaternionIdentity (D3DXQUATERNION * pOut)
Referenced by CD3DArcBall::CD3DArcBall().
D3DXQUATERNION* WINAPI D3DXQuaternionInverse (D3DXQUATERNION * pOut, CONST D3DXQUATERNION * pQ)
BOOL D3DXQuaternionIsIdentity (CONST D3DXQUATERNION * pQ)
FLOAT D3DXQuaternionLength (CONST D3DXQUATERNION * pQ)
FLOAT D3DXQuaternionLengthSq (CONST D3DXQUATERNION * pQ)
D3DXQUATERNION* WINAPI D3DXQuaternionLn (D3DXQUATERNION * pOut, CONST D3DXQUATERNION * pQ)
D3DXQUATERNION* WINAPI D3DXQuaternionMultiply (D3DXQUATERNION * pOut, CONST D3DXQUATERNION * pQ1, CONST D3DXQUATERNION * pQ2)
D3DXQUATERNION* WINAPI D3DXQuaternionNormalize (D3DXQUATERNION * pOut, CONST D3DXQUATERNION * pQ)
D3DXQUATERNION* WINAPI D3DXQuaternionRotationAxis (D3DXQUATERNION * pOut, CONST D3DXVECTOR3 * pV, FLOAT Angle)
Referenced by D3DUtil_GetRotationFromCursor().
D3DXQUATERNION* WINAPI D3DXQuaternionRotationMatrix (D3DXQUATERNION * pOut, CONST D3DXMATRIX * pM)
D3DXQUATERNION* WINAPI D3DXQuaternionRotationYawPitchRoll (D3DXQUATERNION * pOut, FLOAT Yaw, FLOAT Pitch, FLOAT Roll)
D3DXQUATERNION* WINAPI D3DXQuaternionSlerp (D3DXQUATERNION * pOut, CONST D3DXQUATERNION * pQ1, CONST D3DXQUATERNION * pQ2, FLOAT t)
D3DXQUATERNION* WINAPI D3DXQuaternionSquad (D3DXQUATERNION * pOut, CONST D3DXQUATERNION * pQ1, CONST D3DXQUATERNION * pA, CONST D3DXQUATERNION * pB, CONST D3DXQUATERNION * pC, FLOAT t)
void WINAPI D3DXQuaternionSquadSetup (D3DXQUATERNION * pAOut, D3DXQUATERNION * pBOut, D3DXQUATERNION * pCOut, CONST D3DXQUATERNION * pQ0, CONST D3DXQUATERNION * pQ1, CONST D3DXQUATERNION * pQ2, CONST D3DXQUATERNION * pQ3)
void WINAPI D3DXQuaternionToAxisAngle (CONST D3DXQUATERNION * pQ, D3DXVECTOR3 * pAxis, FLOAT * pAngle)
D3DXVECTOR2* D3DXVec2Add (D3DXVECTOR2 * pOut, CONST D3DXVECTOR2 * pV1, CONST D3DXVECTOR2 * pV2)
D3DXVECTOR2* WINAPI D3DXVec2BaryCentric (D3DXVECTOR2 * pOut, CONST D3DXVECTOR2 * pV1, CONST D3DXVECTOR2 * pV2, CONST D3DXVECTOR2 * pV3, FLOAT f, FLOAT g)
D3DXVECTOR2* WINAPI D3DXVec2CatmullRom (D3DXVECTOR2 * pOut, CONST D3DXVECTOR2 * pV0, CONST D3DXVECTOR2 * pV1, CONST D3DXVECTOR2 * pV2, CONST D3DXVECTOR2 * pV3, FLOAT s)
FLOAT D3DXVec2CCW (CONST D3DXVECTOR2 * pV1, CONST D3DXVECTOR2 * pV2)
FLOAT D3DXVec2Dot (CONST D3DXVECTOR2 * pV1, CONST D3DXVECTOR2 * pV2)
D3DXVECTOR2* WINAPI D3DXVec2Hermite (D3DXVECTOR2 * pOut, CONST D3DXVECTOR2 * pV1, CONST D3DXVECTOR2 * pT1, CONST D3DXVECTOR2 * pV2, CONST D3DXVECTOR2 * pT2, FLOAT s)
FLOAT D3DXVec2Length (CONST D3DXVECTOR2 * pV)
FLOAT D3DXVec2LengthSq (CONST D3DXVECTOR2 * pV)
D3DXVECTOR2* D3DXVec2Lerp (D3DXVECTOR2 * pOut, CONST D3DXVECTOR2 * pV1, CONST D3DXVECTOR2 * pV2, FLOAT s)
D3DXVECTOR2* D3DXVec2Maximize (D3DXVECTOR2 * pOut, CONST D3DXVECTOR2 * pV1, CONST D3DXVECTOR2 * pV2)
D3DXVECTOR2* D3DXVec2Minimize (D3DXVECTOR2 * pOut, CONST D3DXVECTOR2 * pV1, CONST D3DXVECTOR2 * pV2)
D3DXVECTOR2* WINAPI D3DXVec2Normalize (D3DXVECTOR2 * pOut, CONST D3DXVECTOR2 * pV)
D3DXVECTOR2* D3DXVec2Scale (D3DXVECTOR2 * pOut, CONST D3DXVECTOR2 * pV, FLOAT s)
D3DXVECTOR2* D3DXVec2Subtract (D3DXVECTOR2 * pOut, CONST D3DXVECTOR2 * pV1, CONST D3DXVECTOR2 * pV2)
D3DXVECTOR4* WINAPI D3DXVec2Transform (D3DXVECTOR4 * pOut, CONST D3DXVECTOR2 * pV, CONST D3DXMATRIX * pM)
D3DXVECTOR2* WINAPI D3DXVec2TransformCoord (D3DXVECTOR2 * pOut, CONST D3DXVECTOR2 * pV, CONST D3DXMATRIX * pM)
D3DXVECTOR2* WINAPI D3DXVec2TransformNormal (D3DXVECTOR2 * pOut, CONST D3DXVECTOR2 * pV, CONST D3DXMATRIX * pM)
D3DXVECTOR3* D3DXVec3Add (D3DXVECTOR3 * pOut, CONST D3DXVECTOR3 * pV1, CONST D3DXVECTOR3 * pV2)
D3DXVECTOR3* WINAPI D3DXVec3BaryCentric (D3DXVECTOR3 * pOut, CONST D3DXVECTOR3 * pV1, CONST D3DXVECTOR3 * pV2, CONST D3DXVECTOR3 * pV3, FLOAT f, FLOAT g)
D3DXVECTOR3* WINAPI D3DXVec3CatmullRom (D3DXVECTOR3 * pOut, CONST D3DXVECTOR3 * pV0, CONST D3DXVECTOR3 * pV1, CONST D3DXVECTOR3 * pV2, CONST D3DXVECTOR3 * pV3, FLOAT s)
D3DXVECTOR3* D3DXVec3Cross (D3DXVECTOR3 * pOut, CONST D3DXVECTOR3 * pV1, CONST D3DXVECTOR3 * pV2)
Referenced by D3DUtil_GetRotationFromCursor(), D3DXQuaternionUnitAxisToUnitAxis2(), and CD3DCamera::SetViewParams().
FLOAT D3DXVec3Dot (CONST D3DXVECTOR3 * pV1, CONST D3DXVECTOR3 * pV2)
Referenced by D3DXQuaternionUnitAxisToUnitAxis2().
D3DXVECTOR3* WINAPI D3DXVec3Hermite (D3DXVECTOR3 * pOut, CONST D3DXVECTOR3 * pV1, CONST D3DXVECTOR3 * pT1, CONST D3DXVECTOR3 * pV2, CONST D3DXVECTOR3 * pT2, FLOAT s)
FLOAT D3DXVec3Length (CONST D3DXVECTOR3 * pV)
Referenced by D3DUtil_GetRotationFromCursor().
FLOAT D3DXVec3LengthSq (CONST D3DXVECTOR3 * pV)
D3DXVECTOR3* D3DXVec3Lerp (D3DXVECTOR3 * pOut, CONST D3DXVECTOR3 * pV1, CONST D3DXVECTOR3 * pV2, FLOAT s)
D3DXVECTOR3* D3DXVec3Maximize (D3DXVECTOR3 * pOut, CONST D3DXVECTOR3 * pV1, CONST D3DXVECTOR3 * pV2)
D3DXVECTOR3* D3DXVec3Minimize (D3DXVECTOR3 * pOut, CONST D3DXVECTOR3 * pV1, CONST D3DXVECTOR3 * pV2)
D3DXVECTOR3* WINAPI D3DXVec3Normalize (D3DXVECTOR3 * pOut, CONST D3DXVECTOR3 * pV)
Referenced by D3DUtil_InitLight(), D3DXQuaternionAxisToAxis(), and CD3DCamera::SetViewParams().
D3DXVECTOR3* WINAPI D3DXVec3Project (D3DXVECTOR3 * pOut, CONST D3DXVECTOR3 * pV, CONST D3DVIEWPORT8 * pViewport, CONST D3DXMATRIX * pProjection, CONST D3DXMATRIX * pView, CONST D3DXMATRIX * pWorld)
D3DXVECTOR3* D3DXVec3Scale (D3DXVECTOR3 * pOut, CONST D3DXVECTOR3 * pV, FLOAT s)
D3DXVECTOR3* D3DXVec3Subtract (D3DXVECTOR3 * pOut, CONST D3DXVECTOR3 * pV1, CONST D3DXVECTOR3 * pV2)
D3DXVECTOR4* WINAPI D3DXVec3Transform (D3DXVECTOR4 * pOut, CONST D3DXVECTOR3 * pV, CONST D3DXMATRIX * pM)
D3DXVECTOR3* WINAPI D3DXVec3TransformCoord (D3DXVECTOR3 * pOut, CONST D3DXVECTOR3 * pV, CONST D3DXMATRIX * pM)
D3DXVECTOR3* WINAPI D3DXVec3TransformNormal (D3DXVECTOR3 * pOut, CONST D3DXVECTOR3 * pV, CONST D3DXMATRIX * pM)
D3DXVECTOR3* WINAPI D3DXVec3Unproject (D3DXVECTOR3 * pOut, CONST D3DXVECTOR3 * pV, CONST D3DVIEWPORT8 * pViewport, CONST D3DXMATRIX * pProjection, CONST D3DXMATRIX * pView, CONST D3DXMATRIX * pWorld)
D3DXVECTOR4* D3DXVec4Add (D3DXVECTOR4 * pOut, CONST D3DXVECTOR4 * pV1, CONST D3DXVECTOR4 * pV2)
D3DXVECTOR4* WINAPI D3DXVec4BaryCentric (D3DXVECTOR4 * pOut, CONST D3DXVECTOR4 * pV1, CONST D3DXVECTOR4 * pV2, CONST D3DXVECTOR4 * pV3, FLOAT f, FLOAT g)
D3DXVECTOR4* WINAPI D3DXVec4CatmullRom (D3DXVECTOR4 * pOut, CONST D3DXVECTOR4 * pV0, CONST D3DXVECTOR4 * pV1, CONST D3DXVECTOR4 * pV2, CONST D3DXVECTOR4 * pV3, FLOAT s)
D3DXVECTOR4* WINAPI D3DXVec4Cross (D3DXVECTOR4 * pOut, CONST D3DXVECTOR4 * pV1, CONST D3DXVECTOR4 * pV2, CONST D3DXVECTOR4 * pV3)
FLOAT D3DXVec4Dot (CONST D3DXVECTOR4 * pV1, CONST D3DXVECTOR4 * pV2)
D3DXVECTOR4* WINAPI D3DXVec4Hermite (D3DXVECTOR4 * pOut, CONST D3DXVECTOR4 * pV1, CONST D3DXVECTOR4 * pT1, CONST D3DXVECTOR4 * pV2, CONST D3DXVECTOR4 * pT2, FLOAT s)
FLOAT D3DXVec4Length (CONST D3DXVECTOR4 * pV)
FLOAT D3DXVec4LengthSq (CONST D3DXVECTOR4 * pV)
D3DXVECTOR4* D3DXVec4Lerp (D3DXVECTOR4 * pOut, CONST D3DXVECTOR4 * pV1, CONST D3DXVECTOR4 * pV2, FLOAT s)
D3DXVECTOR4* D3DXVec4Maximize (D3DXVECTOR4 * pOut, CONST D3DXVECTOR4 * pV1, CONST D3DXVECTOR4 * pV2)
D3DXVECTOR4* D3DXVec4Minimize (D3DXVECTOR4 * pOut, CONST D3DXVECTOR4 * pV1, CONST D3DXVECTOR4 * pV2)
D3DXVECTOR4* WINAPI D3DXVec4Normalize (D3DXVECTOR4 * pOut, CONST D3DXVECTOR4 * pV)
D3DXVECTOR4* D3DXVec4Scale (D3DXVECTOR4 * pOut, CONST D3DXVECTOR4 * pV, FLOAT s)
D3DXVECTOR4* D3DXVec4Subtract (D3DXVECTOR4 * pOut, CONST D3DXVECTOR4 * pV1, CONST D3DXVECTOR4 * pV2)
D3DXVECTOR4* WINAPI D3DXVec4Transform (D3DXVECTOR4 * pOut, CONST D3DXVECTOR4 * pV, CONST D3DXMATRIX * pM)
DECLARE_INTERFACE_ (ID3DXMatrixStack , IUnknown)
DEFINE_GUID (IID_ID3DXMatrixStack , 0xe3357330 , 0xcc5e , 0x11d2 , 0xa4 , 0x34 , 0x0 , 0xa0 , 0xc9 , 0x6 , 0x29 , 0xa8)