RigidChips: microsoft directx 9.0 sdk (summer 2004)/Include/dmort.h File Reference
dmort.h File Reference
Functions
STDAPI MoInitMediaType (DMO_MEDIA_TYPE *pmt, DWORD cbFormat)
STDAPI MoFreeMediaType (DMO_MEDIA_TYPE *pmt)
STDAPI MoCopyMediaType (DMO_MEDIA_TYPE *pmtDest, const DMO_MEDIA_TYPE *pmtSrc)
STDAPI MoCreateMediaType (DMO_MEDIA_TYPE **ppmt, DWORD cbFormat)
STDAPI MoDeleteMediaType (DMO_MEDIA_TYPE *pmt)
STDAPI MoDuplicateMediaType (DMO_MEDIA_TYPE **ppmtDest, const DMO_MEDIA_TYPE *pmtSrc)
Function Documentation
STDAPI MoCopyMediaType (DMO_MEDIA_TYPE * pmtDest, const DMO_MEDIA_TYPE * pmtSrc)
Referenced by IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::GetInputCurrentType(), IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::GetOutputCurrentType(), IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::SetInputType(), and IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::SetOutputType().
STDAPI MoCreateMediaType (DMO_MEDIA_TYPE ** ppmt, DWORD cbFormat)
STDAPI MoDeleteMediaType (DMO_MEDIA_TYPE * pmt)
STDAPI MoDuplicateMediaType (DMO_MEDIA_TYPE ** ppmtDest, const DMO_MEDIA_TYPE * pmtSrc)
STDAPI MoFreeMediaType (DMO_MEDIA_TYPE * pmt)
Referenced by IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::SetInputType(), IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::SetOutputType(), and IMediaObjectImpl< _DERIVED_, NUMBEROFINPUTS, NUMBEROFOUTPUTS >::~IMediaObjectImpl().
STDAPI MoInitMediaType (DMO_MEDIA_TYPE * pmt, DWORD cbFormat)