RigidChips: microsoft directx 9.0 sdk (summer 2004)/Include/DShowIDL/dxtrans.idl File Reference
dxtrans.idl File Reference
Classes
interface IDXBaseObject
struct DXDBND
struct DXDBND64
struct DXCBND
struct DXCBND64
union u
union u
interface IDXTransformFactory
interface IDXTransform
interface IDXSurfacePick
interface IDXTBindHost
struct DXTMTASKINFO
interface IDXTaskManager
struct DXBASESAMPLE
struct DXSAMPLE
struct DXPMSAMPLE
struct DXRUNINFO
interface IDXSurfaceFactory
interface IDXSurfaceModifier
interface IDXSurface
interface IDXSurfaceInit
interface IDXARGBSurfaceInit
struct tagDXNATIVETYPEINFO
struct tagDXPACKEDRECTDESC
struct tagDXOVERSAMPLEDESC
interface IDXARGBReadPtr
interface IDXARGBReadWritePtr
interface IDXDCLock
interface IDXTScaleOutput
interface IDXGradient
interface IDXTScale
interface IDXEffect
interface IDXLookupTable
struct DXRAWSURFACEINFO
interface IDXRawSurface
interface IHTMLDXTransform
interface ICSSFilterDispatch
class DXTRANSLib::DXTransformFactory
class DXTRANSLib::DXTaskManager
class DXTRANSLib::DXTScale
class DXTRANSLib::DXSurface
class DXTRANSLib::DXSurfaceModifier
class DXTRANSLib::DXGradient
class DXTRANSLib::DXTFilter
Modules
library DXTRANSLib
Typedefs
typedef void DDSURFACEDESC
typedef void D3DRMBOX
typedef void D3DVECTOR
typedef void D3DRMMATRIX4D
typedef void * LPSECURITY_ATTRIBUTES
typedef enum DXBNDID DXBNDID
typedef enum DXBNDTYPE DXBNDTYPE
typedef struct DXDBND DXDBND
typedef DXDBND DXDBNDS[4]
typedef struct DXDBND64 DXDBND64
typedef DXDBND64 DXDBNDS64[4]
typedef struct DXCBND DXCBND
typedef DXCBND DXCBNDS[4]
typedef struct DXCBND64 DXCBND64
typedef DXCBND64 DXCBNDS64[4]
typedef union DXBNDS u DXBNDS
typedef long DXDVEC[4]
typedef LONGLONG DXDVEC64[4]
typedef float DXCVEC[4]
typedef double DXCVEC64[4]
typedef union DXVEC u DXVEC
typedef enum DXTMISCFLAGS DXTMISCFLAGS
typedef enum DXINOUTINFOFLAGS DXINOUTINFOFLAGS
typedef BOOL * pbContinueProcessing
typedef DXTASKPROC * PFNDXTASKPROC
typedef DXAPCPROC * PFNDXAPCPROC
typedef struct DXTMTASKINFO PFNDXTASKPROC pfnTaskProc {
typedef struct DXTMTASKINFO DXTMTASKINFO
typedef struct DXBASESAMPLE DXBASESAMPLE
typedef struct DXSAMPLE DXSAMPLE
typedef struct DXPMSAMPLE DXPMSAMPLE
typedef enum DXRUNTYPE DXRUNTYPE
typedef struct DXRUNINFO DXRUNINFO
typedef struct DXRUNINFO ULONG Type {
typedef enum DXSFCREATE DXSFCREATE
typedef enum DXBLTOPTIONS DXBLTOPTIONS
typedef enum DXSURFMODCOMPOP DXSURFMODCOMPOP
typedef enum DXSAMPLEFORMATENUM DXSAMPLEFORMATENUM
typedef enum DXLOCKSURF DXLOCKSURF
typedef enum DXSURFSTATUS DXSURFSTATUS
typedef struct tagDXNATIVETYPEINFO DXNATIVETYPEINFO
typedef struct tagDXPACKEDRECTDESC DXPACKEDRECTDESC
typedef struct tagDXOVERSAMPLEDESC DXOVERSAMPLEDESC
typedef enum DISPIDDXEFFECT DISPIDDXBOUNDEDEFFECT
typedef enum DXEFFECTTYPE DXEFFECTTYPE
typedef struct DXRAWSURFACEINFO DXRAWSURFACEINFO
typedef enum DXTFILTER_STATUS DXTFILTER_STATUS
typedef enum DXTFILTER_DISPID DXTFILTER_DISPID
Enumerations
enum DXBNDID {
DXB_X = 0, DXB_Y = 1, DXB_Z = 2, DXB_T = 3,
DXB_X = 0, DXB_Y = 1, DXB_Z = 2, DXB_T = 3
}
enum DXBNDTYPE {
DXBT_DISCRETE, DXBT_DISCRETE64, DXBT_CONTINUOUS, DXBT_CONTINUOUS64,
DXBT_DISCRETE = 0, DXBT_DISCRETE64 = DXBT_DISCRETE + 1, DXBT_CONTINUOUS = DXBT_DISCRETE64 + 1, DXBT_CONTINUOUS64 = DXBT_CONTINUOUS + 1
}
enum DXTMISCFLAGS {
DXTMF_BLEND_WITH_OUTPUT = (1L << 0), DXTMF_DITHER_OUTPUT = (1L << 1), DXTMF_OPTION_MASK = (0x0000FFFF), DXTMF_VALID_OPTIONS = (DXTMF_BLEND_WITH_OUTPUT | DXTMF_DITHER_OUTPUT),
DXTMF_BLEND_SUPPORTED = (1L << 16), DXTMF_DITHER_SUPPORTED = (1L << 17), DXTMF_INPLACE_OPERATION = (1L << 24), DXTMF_BOUNDS_SUPPORTED = (1L << 25),
DXTMF_PLACEMENT_SUPPORTED = (1L << 26), DXTMF_QUALITY_SUPPORTED = (1L << 27), DXTMF_OPAQUE_RESULT = (1L << 28), DXTMF_BLEND_WITH_OUTPUT = 1L << 0,
DXTMF_DITHER_OUTPUT = 1L << 1, DXTMF_OPTION_MASK = 0xffff, DXTMF_VALID_OPTIONS = DXTMF_BLEND_WITH_OUTPUT | DXTMF_DITHER_OUTPUT, DXTMF_BLEND_SUPPORTED = 1L << 16,
DXTMF_DITHER_SUPPORTED = 1L << 17, DXTMF_INPLACE_OPERATION = 1L << 24, DXTMF_BOUNDS_SUPPORTED = 1L << 25, DXTMF_PLACEMENT_SUPPORTED = 1L << 26,
DXTMF_QUALITY_SUPPORTED = 1L << 27, DXTMF_OPAQUE_RESULT = 1L << 28
}
enum DXINOUTINFOFLAGS { DXINOUTF_OPTIONAL = (1L << 0), DXINOUTF_OPTIONAL = 1L << 0 }
enum DXRUNTYPE {
DXRUNTYPE_CLEAR = 0, DXRUNTYPE_OPAQUE = 1, DXRUNTYPE_TRANS = 2, DXRUNTYPE_UNKNOWN = 3,
DXRUNTYPE_CLEAR = 0, DXRUNTYPE_OPAQUE = 1, DXRUNTYPE_TRANS = 2, DXRUNTYPE_UNKNOWN = 3
}
enum DXSFCREATE { DXSF_FORMAT_IS_CLSID = (1L << 0), DXSF_NO_LAZY_DDRAW_LOCK = (1L << 1), DXSF_FORMAT_IS_CLSID = 1L << 0, DXSF_NO_LAZY_DDRAW_LOCK = 1L << 1 }
enum DXBLTOPTIONS { DXBOF_DO_OVER = (1L << 0), DXBOF_DITHER = (1L << 1), DXBOF_DO_OVER = 1L << 0, DXBOF_DITHER = 1L << 1 }
enum DXSURFMODCOMPOP {
DXSURFMOD_COMP_OVER = 0, DXSURFMOD_COMP_ALPHA_MASK = 1, DXSURFMOD_COMP_MAX_VALID = 1, DXSURFMOD_COMP_OVER = 0,
DXSURFMOD_COMP_ALPHA_MASK = 1, DXSURFMOD_COMP_MAX_VALID = 1
}
enum DXSAMPLEFORMATENUM {
DXPF_FLAGSMASK = (0xFFFF0000), DXPF_NONPREMULT = (0x00010000), DXPF_TRANSPARENCY = (0x00020000), DXPF_TRANSLUCENCY = (0x00040000),
DXPF_2BITERROR = (0x00200000), DXPF_3BITERROR = (0x00300000), DXPF_4BITERROR = (0x00400000), DXPF_5BITERROR = (0x00500000),
DXPF_ERRORMASK = (0x00700000), DXPF_NONSTANDARD = (0), DXPF_PMARGB32 = (1 | DXPF_TRANSPARENCY | DXPF_TRANSLUCENCY), DXPF_ARGB32 = (2 | DXPF_NONPREMULT | DXPF_TRANSPARENCY | DXPF_TRANSLUCENCY),
DXPF_ARGB4444 = (3 | DXPF_NONPREMULT | DXPF_TRANSPARENCY | DXPF_TRANSLUCENCY | DXPF_4BITERROR), DXPF_A8 = (4 | DXPF_TRANSPARENCY | DXPF_TRANSLUCENCY), DXPF_RGB32 = (5), DXPF_RGB24 = (6),
DXPF_RGB565 = (7 | DXPF_3BITERROR), DXPF_RGB555 = (8 | DXPF_3BITERROR), DXPF_RGB8 = (9 | DXPF_5BITERROR), DXPF_ARGB1555 = (10 | DXPF_TRANSPARENCY | DXPF_3BITERROR),
DXPF_RGB32_CK = (DXPF_RGB32 | DXPF_TRANSPARENCY), DXPF_RGB24_CK = (DXPF_RGB24 | DXPF_TRANSPARENCY), DXPF_RGB555_CK = (DXPF_RGB555 | DXPF_TRANSPARENCY), DXPF_RGB565_CK = (DXPF_RGB565 | DXPF_TRANSPARENCY),
DXPF_RGB8_CK = (DXPF_RGB8 | DXPF_TRANSPARENCY), DXPF_FLAGSMASK = 0xffff0000, DXPF_NONPREMULT = 0x10000, DXPF_TRANSPARENCY = 0x20000,
DXPF_TRANSLUCENCY = 0x40000, DXPF_2BITERROR = 0x200000, DXPF_3BITERROR = 0x300000, DXPF_4BITERROR = 0x400000,
DXPF_5BITERROR = 0x500000, DXPF_ERRORMASK = 0x700000, DXPF_NONSTANDARD = 0, DXPF_PMARGB32 = 1 | DXPF_TRANSPARENCY | DXPF_TRANSLUCENCY,
DXPF_ARGB32 = 2 | DXPF_NONPREMULT | DXPF_TRANSPARENCY | DXPF_TRANSLUCENCY, DXPF_ARGB4444 = 3 | DXPF_NONPREMULT | DXPF_TRANSPARENCY | DXPF_TRANSLUCENCY | DXPF_4BITERROR, DXPF_A8 = 4 | DXPF_TRANSPARENCY | DXPF_TRANSLUCENCY, DXPF_RGB32 = 5,
DXPF_RGB24 = 6, DXPF_RGB565 = 7 | DXPF_3BITERROR, DXPF_RGB555 = 8 | DXPF_3BITERROR, DXPF_RGB8 = 9 | DXPF_5BITERROR,
DXPF_ARGB1555 = 10 | DXPF_TRANSPARENCY | DXPF_3BITERROR, DXPF_RGB32_CK = DXPF_RGB32 | DXPF_TRANSPARENCY, DXPF_RGB24_CK = DXPF_RGB24 | DXPF_TRANSPARENCY, DXPF_RGB555_CK = DXPF_RGB555 | DXPF_TRANSPARENCY,
DXPF_RGB565_CK = DXPF_RGB565 | DXPF_TRANSPARENCY, DXPF_RGB8_CK = DXPF_RGB8 | DXPF_TRANSPARENCY
}
enum DXLOCKSURF {
DXLOCKF_READ = 0, DXLOCKF_READWRITE = (1 << 0), DXLOCKF_EXISTINGINFOONLY = (1 << 1), DXLOCKF_WANTRUNINFO = (1 << 2),
DXLOCKF_NONPREMULT = (1 << 16), DXLOCKF_VALIDFLAGS = (DXLOCKF_READWRITE | DXLOCKF_EXISTINGINFOONLY | DXLOCKF_WANTRUNINFO | DXLOCKF_NONPREMULT), DXLOCKF_READ = 0, DXLOCKF_READWRITE = 1 << 0,
DXLOCKF_EXISTINGINFOONLY = 1 << 1, DXLOCKF_WANTRUNINFO = 1 << 2, DXLOCKF_NONPREMULT = 1 << 16, DXLOCKF_VALIDFLAGS = DXLOCKF_READWRITE | DXLOCKF_EXISTINGINFOONLY | DXLOCKF_WANTRUNINFO | DXLOCKF_NONPREMULT
}
enum DXSURFSTATUS {
DXSURF_TRANSIENT = (1 << 0), DXSURF_READONLY = (1 << 1), DXSURF_VALIDFLAGS = (DXSURF_TRANSIENT | DXSURF_READONLY), DXSURF_TRANSIENT = 1 << 0,
DXSURF_READONLY = 1 << 1, DXSURF_VALIDFLAGS = DXSURF_TRANSIENT | DXSURF_READONLY
}
enum DISPIDDXEFFECT {
DISPID_DXECAPABILITIES = 10000, DISPID_DXEPROGRESS, DISPID_DXESTEP, DISPID_DXEDURATION,
DISPID_DXE_NEXT_ID, DISPID_DXECAPABILITIES = 10000, DISPID_DXEPROGRESS = DISPID_DXECAPABILITIES + 1, DISPID_DXESTEP = DISPID_DXEPROGRESS + 1,
DISPID_DXEDURATION = DISPID_DXESTEP + 1, DISPID_DXE_NEXT_ID = DISPID_DXEDURATION + 1
}
enum DXEFFECTTYPE { DXTET_PERIODIC = (1 << 0), DXTET_MORPH = (1 << 1), DXTET_PERIODIC = 1 << 0, DXTET_MORPH = 1 << 1 }
enum DXTFILTER_STATUS {
DXTFILTER_STATUS_Stopped = 0, DXTFILTER_STATUS_Applied, DXTFILTER_STATUS_Playing, DXTFILTER_STATUS_MAX,
DXTFILTER_STATUS_Stopped = 0, DXTFILTER_STATUS_Applied = DXTFILTER_STATUS_Stopped + 1, DXTFILTER_STATUS_Playing = DXTFILTER_STATUS_Applied + 1, DXTFILTER_STATUS_MAX = DXTFILTER_STATUS_Playing + 1
}
enum DXTFILTER_DISPID {
DISPID_DXTFilter_Percent = 1, DISPID_DXTFilter_Duration, DISPID_DXTFilter_Enabled, DISPID_DXTFilter_Status,
DISPID_DXTFilter_Apply, DISPID_DXTFilter_Play, DISPID_DXTFilter_Stop, DISPID_DXTFilter_MAX,
DISPID_DXTFilter_Percent = 1, DISPID_DXTFilter_Duration = DISPID_DXTFilter_Percent + 1, DISPID_DXTFilter_Enabled = DISPID_DXTFilter_Duration + 1, DISPID_DXTFilter_Status = DISPID_DXTFilter_Enabled + 1,
DISPID_DXTFilter_Apply = DISPID_DXTFilter_Status + 1, DISPID_DXTFilter_Play = DISPID_DXTFilter_Apply + 1, DISPID_DXTFilter_Stop = DISPID_DXTFilter_Play + 1, DISPID_DXTFilter_MAX = DISPID_DXTFilter_Stop + 1
}
Functions
typedef void (__stdcall DXTASKPROC)(void *pTaskData
DXBASESAMPLE ()
DXBASESAMPLE (const BYTE alpha, const BYTE red, const BYTE green, const BYTE blue)
DXBASESAMPLE (const DWORD val)
operator DWORD () const
DWORD operator= (const DWORD val)
DXSAMPLE ()
DXSAMPLE (const BYTE alpha, const BYTE red, const BYTE green, const BYTE blue)
DXSAMPLE (const DWORD val)
operator DXPMSAMPLE () const
DXPMSAMPLE ()
DXPMSAMPLE (const BYTE alpha, const BYTE red, const BYTE green, const BYTE blue)
DXPMSAMPLE (const DWORD val)
operator DXSAMPLE () const
DXTRANSLib::importlib ("stdole2.tlb")
Variables
EXTERN_C const GUID DDPF_RGB1
EXTERN_C const GUID DDPF_RGB2
EXTERN_C const GUID DDPF_RGB4
EXTERN_C const GUID DDPF_RGB8
EXTERN_C const GUID DDPF_RGB332
EXTERN_C const GUID DDPF_ARGB4444
EXTERN_C const GUID DDPF_RGB565
EXTERN_C const GUID DDPF_BGR565
EXTERN_C const GUID DDPF_RGB555
EXTERN_C const GUID DDPF_ARGB1555
EXTERN_C const GUID DDPF_RGB24
EXTERN_C const GUID DDPF_BGR24
EXTERN_C const GUID DDPF_RGB32
EXTERN_C const GUID DDPF_BGR32
EXTERN_C const GUID DDPF_ABGR32
EXTERN_C const GUID DDPF_ARGB32
EXTERN_C const GUID DDPF_PMARGB32
EXTERN_C const GUID DDPF_A1
EXTERN_C const GUID DDPF_A2
EXTERN_C const GUID DDPF_A4
EXTERN_C const GUID DDPF_A8
EXTERN_C const GUID DDPF_Z8
EXTERN_C const GUID DDPF_Z16
EXTERN_C const GUID DDPF_Z24
EXTERN_C const GUID DDPF_Z32
EXTERN_C const GUID CATID_DXImageTransform
EXTERN_C const GUID CATID_DX3DTransform
EXTERN_C const GUID CATID_DXAuthoringTransform
EXTERN_C const GUID CATID_DXSurface
EXTERN_C const GUID SID_SDirectDraw
EXTERN_C const GUID SID_SDirect3DRM
PVOID pTaskData
PFNDXAPCPROC pfnCompletionAPC
DWORD dwCompletionData
const GUID * pRequestID
BYTE Blue {
BYTE Green
BYTE Red
BYTE Alpha
const ULONG DX_MAX_RUN_INFO_COUNT = 128
ULONG Count
Typedef Documentation
typedef void D3DRMBOX
typedef void D3DRMMATRIX4D
typedef void D3DVECTOR
typedef void DDSURFACEDESC
typedef enum DISPIDDXEFFECT DISPIDDXBOUNDEDEFFECT
typedef struct DXBASESAMPLE DXBASESAMPLE
typedef enum DXBLTOPTIONS DXBLTOPTIONS
typedef enum DXBNDID DXBNDID
typedef union DXBNDS u DXBNDS
typedef enum DXBNDTYPE DXBNDTYPE
typedef struct DXCBND DXCBND
typedef struct DXCBND64 DXCBND64
typedef DXCBND DXCBNDS[4]
typedef DXCBND64 DXCBNDS64[4]
typedef float DXCVEC[4]
typedef double DXCVEC64[4]
typedef struct DXDBND DXDBND
typedef struct DXDBND64 DXDBND64
typedef DXDBND DXDBNDS[4]
typedef DXDBND64 DXDBNDS64[4]
typedef long DXDVEC[4]
typedef LONGLONG DXDVEC64[4]
typedef enum DXEFFECTTYPE DXEFFECTTYPE
typedef enum DXINOUTINFOFLAGS DXINOUTINFOFLAGS
typedef enum DXLOCKSURF DXLOCKSURF
typedef struct tagDXNATIVETYPEINFO DXNATIVETYPEINFO
typedef struct tagDXOVERSAMPLEDESC DXOVERSAMPLEDESC
typedef struct tagDXPACKEDRECTDESC DXPACKEDRECTDESC
typedef struct DXPMSAMPLE DXPMSAMPLE
typedef struct DXRAWSURFACEINFO DXRAWSURFACEINFO
DXRUNINFO
typedef enum DXRUNTYPE DXRUNTYPE
typedef struct DXSAMPLE DXSAMPLE
typedef enum DXSAMPLEFORMATENUM DXSAMPLEFORMATENUM
typedef enum DXSFCREATE DXSFCREATE
typedef enum DXSURFMODCOMPOP DXSURFMODCOMPOP
typedef enum DXSURFSTATUS DXSURFSTATUS
typedef enum DXTFILTER_DISPID DXTFILTER_DISPID
typedef enum DXTFILTER_STATUS DXTFILTER_STATUS
typedef enum DXTMISCFLAGS DXTMISCFLAGS
DXTMTASKINFO
typedef union DXVEC u DXVEC
typedef void* LPSECURITY_ATTRIBUTES
typedef BOOL* pbContinueProcessing
typedef DXAPCPROC* PFNDXAPCPROC
typedef DXTASKPROC* PFNDXTASKPROC
typedef struct DXTMTASKINFO PFNDXTASKPROC pfnTaskProc {
typedef struct DXRUNINFO ULONG Type {
Enumeration Type Documentation
enum DISPIDDXEFFECT
Enumerator
DISPID_DXECAPABILITIES
DISPID_DXEPROGRESS
DISPID_DXESTEP
DISPID_DXEDURATION
DISPID_DXE_NEXT_ID
DISPID_DXECAPABILITIES
DISPID_DXEPROGRESS
DISPID_DXESTEP
DISPID_DXEDURATION
DISPID_DXE_NEXT_ID
enum DXBLTOPTIONS
Enumerator
DXBOF_DO_OVER
DXBOF_DITHER
DXBOF_DO_OVER
DXBOF_DITHER
enum DXBNDID
Enumerator
DXB_X
DXB_Y
DXB_Z
DXB_T
DXB_X
DXB_Y
DXB_Z
DXB_T
enum DXBNDTYPE
Enumerator
DXBT_DISCRETE
DXBT_DISCRETE64
DXBT_CONTINUOUS
DXBT_CONTINUOUS64
DXBT_DISCRETE
DXBT_DISCRETE64
DXBT_CONTINUOUS
DXBT_CONTINUOUS64
enum DXEFFECTTYPE
Enumerator
DXTET_PERIODIC
DXTET_MORPH
DXTET_PERIODIC
DXTET_MORPH
enum DXINOUTINFOFLAGS
Enumerator
DXINOUTF_OPTIONAL
DXINOUTF_OPTIONAL
enum DXLOCKSURF
Enumerator
DXLOCKF_READ
DXLOCKF_READWRITE
DXLOCKF_EXISTINGINFOONLY
DXLOCKF_WANTRUNINFO
DXLOCKF_NONPREMULT
DXLOCKF_VALIDFLAGS
DXLOCKF_READ
DXLOCKF_READWRITE
DXLOCKF_EXISTINGINFOONLY
DXLOCKF_WANTRUNINFO
DXLOCKF_NONPREMULT
DXLOCKF_VALIDFLAGS
enum DXRUNTYPE
Enumerator
DXRUNTYPE_CLEAR
DXRUNTYPE_OPAQUE
DXRUNTYPE_TRANS
DXRUNTYPE_UNKNOWN
DXRUNTYPE_CLEAR
DXRUNTYPE_OPAQUE
DXRUNTYPE_TRANS
DXRUNTYPE_UNKNOWN
enum DXSAMPLEFORMATENUM
Enumerator
DXPF_FLAGSMASK
DXPF_NONPREMULT
DXPF_TRANSPARENCY
DXPF_TRANSLUCENCY
DXPF_2BITERROR
DXPF_3BITERROR
DXPF_4BITERROR
DXPF_5BITERROR
DXPF_ERRORMASK
DXPF_NONSTANDARD
DXPF_PMARGB32
DXPF_ARGB32
DXPF_ARGB4444
DXPF_A8
DXPF_RGB32
DXPF_RGB24
DXPF_RGB565
DXPF_RGB555
DXPF_RGB8
DXPF_ARGB1555
DXPF_RGB32_CK
DXPF_RGB24_CK
DXPF_RGB555_CK
DXPF_RGB565_CK
DXPF_RGB8_CK
DXPF_FLAGSMASK
DXPF_NONPREMULT
DXPF_TRANSPARENCY
DXPF_TRANSLUCENCY
DXPF_2BITERROR
DXPF_3BITERROR
DXPF_4BITERROR
DXPF_5BITERROR
DXPF_ERRORMASK
DXPF_NONSTANDARD
DXPF_PMARGB32
DXPF_ARGB32
DXPF_ARGB4444
DXPF_A8
DXPF_RGB32
DXPF_RGB24
DXPF_RGB565
DXPF_RGB555
DXPF_RGB8
DXPF_ARGB1555
DXPF_RGB32_CK
DXPF_RGB24_CK
DXPF_RGB555_CK
DXPF_RGB565_CK
DXPF_RGB8_CK
enum DXSFCREATE
Enumerator
DXSF_FORMAT_IS_CLSID
DXSF_NO_LAZY_DDRAW_LOCK
DXSF_FORMAT_IS_CLSID
DXSF_NO_LAZY_DDRAW_LOCK
enum DXSURFMODCOMPOP
Enumerator
DXSURFMOD_COMP_OVER
DXSURFMOD_COMP_ALPHA_MASK
DXSURFMOD_COMP_MAX_VALID
DXSURFMOD_COMP_OVER
DXSURFMOD_COMP_ALPHA_MASK
DXSURFMOD_COMP_MAX_VALID
enum DXSURFSTATUS
Enumerator
DXSURF_TRANSIENT
DXSURF_READONLY
DXSURF_VALIDFLAGS
DXSURF_TRANSIENT
DXSURF_READONLY
DXSURF_VALIDFLAGS
enum DXTFILTER_DISPID
Enumerator
DISPID_DXTFilter_Percent
DISPID_DXTFilter_Duration
DISPID_DXTFilter_Enabled
DISPID_DXTFilter_Status
DISPID_DXTFilter_Apply
DISPID_DXTFilter_Play
DISPID_DXTFilter_Stop
DISPID_DXTFilter_MAX
DISPID_DXTFilter_Percent
DISPID_DXTFilter_Duration
DISPID_DXTFilter_Enabled
DISPID_DXTFilter_Status
DISPID_DXTFilter_Apply
DISPID_DXTFilter_Play
DISPID_DXTFilter_Stop
DISPID_DXTFilter_MAX
enum DXTFILTER_STATUS
Enumerator
DXTFILTER_STATUS_Stopped
DXTFILTER_STATUS_Applied
DXTFILTER_STATUS_Playing
DXTFILTER_STATUS_MAX
DXTFILTER_STATUS_Stopped
DXTFILTER_STATUS_Applied
DXTFILTER_STATUS_Playing
DXTFILTER_STATUS_MAX
enum DXTMISCFLAGS
Enumerator
DXTMF_BLEND_WITH_OUTPUT
DXTMF_DITHER_OUTPUT
DXTMF_OPTION_MASK
DXTMF_VALID_OPTIONS
DXTMF_BLEND_SUPPORTED
DXTMF_DITHER_SUPPORTED
DXTMF_INPLACE_OPERATION
DXTMF_BOUNDS_SUPPORTED
DXTMF_PLACEMENT_SUPPORTED
DXTMF_QUALITY_SUPPORTED
DXTMF_OPAQUE_RESULT
DXTMF_BLEND_WITH_OUTPUT
DXTMF_DITHER_OUTPUT
DXTMF_OPTION_MASK
DXTMF_VALID_OPTIONS
DXTMF_BLEND_SUPPORTED
DXTMF_DITHER_SUPPORTED
DXTMF_INPLACE_OPERATION
DXTMF_BOUNDS_SUPPORTED
DXTMF_PLACEMENT_SUPPORTED
DXTMF_QUALITY_SUPPORTED
DXTMF_OPAQUE_RESULT
Function Documentation
DXBASESAMPLE ()
DXBASESAMPLE (const BYTE alpha, const BYTE red, const BYTE green, const BYTE blue)
DXBASESAMPLE (const DWORD val)
DXPMSAMPLE ()
DXPMSAMPLE (const BYTE alpha, const BYTE red, const BYTE green, const BYTE blue)
DXPMSAMPLE (const DWORD val)
DXSAMPLE ()
DXSAMPLE (const BYTE alpha, const BYTE red, const BYTE green, const BYTE blue)
DXSAMPLE (const DWORD val)
operator DWORD () const
DXSAMPLE::operator DXPMSAMPLE () const inline
DXPMSAMPLE::operator DXSAMPLE () const inline
DWORD operator= (const DWORD val)
Referenced by BDATuningModel::TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE >::Clone(), BDATuningModel::TNLocatorHelper< LOCATORTYPE >::Clone(), BDATuningModel::TNTuneRequestHelper< TUNEREQUESTTYPE, LOCATORTYPE >::Clone(), BDATuningModel::TNTuningSpaceContainer::operator=(), BDATuningModel::TNTuningSpaceHelper< TUNINGSPACETYPE, TUNEREQUESTTYPE >::operator=(), BDATuningModel::TNLocatorHelper< LOCATORTYPE >::operator=(), BDATuningModel::TNTuneRequestHelper< TUNEREQUESTTYPE, LOCATORTYPE >::operator=(), BDATuningModel::TNChannelTuneRequestHelper< TUNEREQUESTTYPE, LOCATORTYPE >::operator=(), BDATuningModel::TNATSCChannelTuneRequestHelper< TUNEREQUESTTYPE, LOCATORTYPE >::operator=(), and BDATuningModel::TNDVBTuneRequestHelper< TUNEREQUESTTYPE, LOCATORTYPE >::operator=().
typedef void (__stdcall DXTASKPROC)
Variable Documentation
BYTE Alpha
BYTE Blue {
EXTERN_C const GUID CATID_DX3DTransform
EXTERN_C const GUID CATID_DXAuthoringTransform
EXTERN_C const GUID CATID_DXImageTransform
EXTERN_C const GUID CATID_DXSurface
ULONG Count
Referenced by DECLARE_INTERFACE_(), CMyD3DApplication::FrameMove(), readData2(), CMyD3DApplication::Render(), CMyD3DApplication::RenderText(), and saveData().
EXTERN_C const GUID DDPF_A1
EXTERN_C const GUID DDPF_A2
EXTERN_C const GUID DDPF_A4
EXTERN_C const GUID DDPF_A8
EXTERN_C const GUID DDPF_ABGR32
EXTERN_C const GUID DDPF_ARGB1555
EXTERN_C const GUID DDPF_ARGB32
EXTERN_C const GUID DDPF_ARGB4444
EXTERN_C const GUID DDPF_BGR24
EXTERN_C const GUID DDPF_BGR32
EXTERN_C const GUID DDPF_BGR565
EXTERN_C const GUID DDPF_PMARGB32
EXTERN_C const GUID DDPF_RGB1
EXTERN_C const GUID DDPF_RGB2
EXTERN_C const GUID DDPF_RGB24
EXTERN_C const GUID DDPF_RGB32
EXTERN_C const GUID DDPF_RGB332
EXTERN_C const GUID DDPF_RGB4
EXTERN_C const GUID DDPF_RGB555
EXTERN_C const GUID DDPF_RGB565
EXTERN_C const GUID DDPF_RGB8
EXTERN_C const GUID DDPF_Z16
EXTERN_C const GUID DDPF_Z24
EXTERN_C const GUID DDPF_Z32
EXTERN_C const GUID DDPF_Z8
DWORD dwCompletionData
const ULONG DX_MAX_RUN_INFO_COUNT = 128
BYTE Green
PFNDXAPCPROC pfnCompletionAPC
const GUID* pRequestID
PVOID pTaskData
BYTE Red
EXTERN_C const GUID SID_SDirect3DRM
EXTERN_C const GUID SID_SDirectDraw