RigidChips: dxutil.cpp File Reference
dxutil.cpp File Reference
#include <windows.h>
#include <mmsystem.h>
#include <tchar.h>
#include <stdio.h>
#include <stdarg.h>
#include "DXUtil.h"
Macros
#define STRICT
Functions
const TCHAR * DXUtil_GetDXSDKMediaPath ()
HRESULT DXUtil_FindMediaFile (TCHAR *strPath, TCHAR *strFilename)
HRESULT DXUtil_ReadStringRegKey (HKEY hKey, TCHAR *strRegName, TCHAR *strValue, DWORD dwLength, TCHAR *strDefault)
HRESULT DXUtil_WriteStringRegKey (HKEY hKey, TCHAR *strRegName, TCHAR *strValue)
HRESULT DXUtil_ReadIntRegKey (HKEY hKey, TCHAR *strRegName, DWORD *pdwValue, DWORD dwDefault)
HRESULT DXUtil_WriteIntRegKey (HKEY hKey, TCHAR *strRegName, DWORD dwValue)
HRESULT DXUtil_ReadBoolRegKey (HKEY hKey, TCHAR *strRegName, BOOL *pbValue, BOOL bDefault)
HRESULT DXUtil_WriteBoolRegKey (HKEY hKey, TCHAR *strRegName, BOOL bValue)
HRESULT DXUtil_ReadGuidRegKey (HKEY hKey, TCHAR *strRegName, GUID *pGuidValue, GUID &guidDefault)
HRESULT DXUtil_WriteGuidRegKey (HKEY hKey, TCHAR *strRegName, GUID guidValue)
FLOAT __stdcall DXUtil_Timer (TIMER_COMMAND command)
VOID DXUtil_ConvertAnsiStringToWide (WCHAR *wstrDestination, const CHAR *strSource, int cchDestChar)
VOID DXUtil_ConvertWideStringToAnsi (CHAR *strDestination, const WCHAR *wstrSource, int cchDestChar)
VOID DXUtil_ConvertGenericStringToAnsi (CHAR *strDestination, const TCHAR *tstrSource, int cchDestChar)
VOID DXUtil_ConvertGenericStringToWide (WCHAR *wstrDestination, const TCHAR *tstrSource, int cchDestChar)
VOID DXUtil_ConvertAnsiStringToGeneric (TCHAR *tstrDestination, const CHAR *strSource, int cchDestChar)
VOID DXUtil_ConvertWideStringToGeneric (TCHAR *tstrDestination, const WCHAR *wstrSource, int cchDestChar)
HRESULT _DbgOut (TCHAR *strFile, DWORD dwLine, HRESULT hr, TCHAR *strMsg)
VOID DXUtil_Trace (TCHAR *strMsg,...)
BOOL DXUtil_ConvertStringToGUID (const TCHAR *strIn, GUID *pGuidOut)
VOID DXUtil_ConvertGUIDToString (const GUID *pGuidIn, TCHAR *strOut)
Macro Definition Documentation
#define STRICT
Function Documentation
HRESULT _DbgOut (TCHAR * strFile, DWORD dwLine, HRESULT hr, TCHAR * strMsg)
VOID DXUtil_ConvertAnsiStringToGeneric (TCHAR * tstrDestination, const CHAR * strSource, int cchDestChar)
Referenced by CD3DMesh::Create(), CD3DFile::LoadFrame(), and CD3DFile::LoadMesh().
VOID DXUtil_ConvertAnsiStringToWide (WCHAR * wstrDestination, const CHAR * strSource, int cchDestChar)
Referenced by DXUtil_ConvertAnsiStringToGeneric(), and DXUtil_ConvertGenericStringToWide().
VOID DXUtil_ConvertGenericStringToAnsi (CHAR * strDestination, const TCHAR * tstrSource, int cchDestChar)
Referenced by CD3DMesh::Create(), CD3DFile::Create(), and CD3DFile::CreateFromResource().
VOID DXUtil_ConvertGenericStringToWide (WCHAR * wstrDestination, const TCHAR * tstrSource, int cchDestChar)
Referenced by CMusicScript::CallRoutine(), CMusicManager::CreateChordMapFromFile(), CMusicManager::CreateScriptFromFile(), CMusicManager::CreateSegmentFromFile(), CMusicManager::CreateStyleFromFile(), CMusicManager::GetMotifFromStyle(), CMusicScript::GetVariableNumber(), CMusicManager::SetSearchDirectory(), and CMusicScript::SetVariableNumber().
VOID DXUtil_ConvertGUIDToString (const GUID * pGuidIn, TCHAR * strOut)
BOOL DXUtil_ConvertStringToGUID (const TCHAR * strIn, GUID * pGuidOut)
VOID DXUtil_ConvertWideStringToAnsi (CHAR * strDestination, const WCHAR * wstrSource, int cchDestChar)
Referenced by DXUtil_ConvertGenericStringToAnsi(), and DXUtil_ConvertWideStringToGeneric().
VOID DXUtil_ConvertWideStringToGeneric (TCHAR * tstrDestination, const WCHAR * wstrSource, int cchDestChar)
HRESULT DXUtil_FindMediaFile (TCHAR * strPath, TCHAR * strFilename)
Referenced by CD3DMesh::Create(), CD3DFile::Create(), D3DUtil_CreateTexture(), and D3DUtil_CreateVertexShader().
const TCHAR* DXUtil_GetDXSDKMediaPath ()
Referenced by DXUtil_FindMediaFile().
HRESULT DXUtil_ReadBoolRegKey (HKEY hKey, TCHAR * strRegName, BOOL * pbValue, BOOL bDefault)
HRESULT DXUtil_ReadGuidRegKey (HKEY hKey, TCHAR * strRegName, GUID * pGuidValue, GUID & guidDefault)
HRESULT DXUtil_ReadIntRegKey (HKEY hKey, TCHAR * strRegName, DWORD * pdwValue, DWORD dwDefault)
Referenced by CMyD3DApplication::ReadSettings().
HRESULT DXUtil_ReadStringRegKey (HKEY hKey, TCHAR * strRegName, TCHAR * strValue, DWORD dwLength, TCHAR * strDefault)
Referenced by CMyD3DApplication::ReadSettings().
FLOAT __stdcall DXUtil_Timer (TIMER_COMMAND command)
Referenced by CD3DApplication::Create(), CD3DApplication::Pause(), CD3DApplication::Render3DEnvironment(), CD3DApplication::Resize3DEnvironment(), and CD3DApplication::UserSelectNewDevice().
VOID DXUtil_Trace (TCHAR * strMsg, ...)
HRESULT DXUtil_WriteBoolRegKey (HKEY hKey, TCHAR * strRegName, BOOL bValue)
HRESULT DXUtil_WriteGuidRegKey (HKEY hKey, TCHAR * strRegName, GUID guidValue)
HRESULT DXUtil_WriteIntRegKey (HKEY hKey, TCHAR * strRegName, DWORD dwValue)
Referenced by CMyD3DApplication::WriteSettings().
HRESULT DXUtil_WriteStringRegKey (HKEY hKey, TCHAR * strRegName, TCHAR * strValue)
Referenced by CMyD3DApplication::WriteSettings().