RigidChips: dxutil.h File Reference
dxutil.h File Reference
Macros
#define SAFE_DELETE(p) { if(p) { delete (p); (p)=NULL; } }
#define SAFE_DELETE_ARRAY(p) { if(p) { delete[] (p); (p)=NULL; } }
#define SAFE_RELEASE(p) { if(p) { (p)->Release(); (p)=NULL; } }
#define DXTRACE sizeof
#define DEBUG_MSG(str) (0L)
Enumerations
enum TIMER_COMMAND {
TIMER_RESET, TIMER_START, TIMER_STOP, TIMER_ADVANCE,
TIMER_GETABSOLUTETIME, TIMER_GETAPPTIME, TIMER_GETELAPSEDTIME
}
Functions
const TCHAR * DXUtil_GetDXSDKMediaPath ()
HRESULT DXUtil_FindMediaFile (TCHAR *strPath, TCHAR *strFilename)
HRESULT DXUtil_WriteStringRegKey (HKEY hKey, TCHAR *strRegName, TCHAR *strValue)
HRESULT DXUtil_WriteIntRegKey (HKEY hKey, TCHAR *strRegName, DWORD dwValue)
HRESULT DXUtil_WriteGuidRegKey (HKEY hKey, TCHAR *strRegName, GUID guidValue)
HRESULT DXUtil_WriteBoolRegKey (HKEY hKey, TCHAR *strRegName, BOOL bValue)
HRESULT DXUtil_ReadStringRegKey (HKEY hKey, TCHAR *strRegName, TCHAR *strValue, DWORD dwLength, TCHAR *strDefault)
HRESULT DXUtil_ReadIntRegKey (HKEY hKey, TCHAR *strRegName, DWORD *pdwValue, DWORD dwDefault)
HRESULT DXUtil_ReadGuidRegKey (HKEY hKey, TCHAR *strRegName, GUID *pGuidValue, GUID &guidDefault)
HRESULT DXUtil_ReadBoolRegKey (HKEY hKey, TCHAR *strRegName, BOOL *pbValue, BOOL bDefault)
FLOAT __stdcall DXUtil_Timer (TIMER_COMMAND command)
VOID DXUtil_ConvertAnsiStringToWide (WCHAR *wstrDestination, const CHAR *strSource, int cchDestChar=-1)
VOID DXUtil_ConvertWideStringToAnsi (CHAR *strDestination, const WCHAR *wstrSource, int cchDestChar=-1)
VOID DXUtil_ConvertGenericStringToAnsi (CHAR *strDestination, const TCHAR *tstrSource, int cchDestChar=-1)
VOID DXUtil_ConvertGenericStringToWide (WCHAR *wstrDestination, const TCHAR *tstrSource, int cchDestChar=-1)
VOID DXUtil_ConvertAnsiStringToGeneric (TCHAR *tstrDestination, const CHAR *strSource, int cchDestChar=-1)
VOID DXUtil_ConvertWideStringToGeneric (TCHAR *tstrDestination, const WCHAR *wstrSource, int cchDestChar=-1)
VOID DXUtil_ConvertGUIDToString (const GUID *pGuidIn, TCHAR *strOut)
BOOL DXUtil_ConvertStringToGUID (const TCHAR *strIn, GUID *pGuidOut)
VOID DXUtil_Trace (TCHAR *strMsg,...)
HRESULT _DbgOut (TCHAR *, DWORD, HRESULT, TCHAR *)
Macro Definition Documentation
#define DEBUG_MSG (str) (0L)
#define DXTRACE sizeof
Referenced by CMusicManager::Initialize().
#define SAFE_DELETE (p) { if(p) { delete (p); (p)=NULL; } }
Referenced by CMyD3DApplication::CleanupDirectInput(), CSoundManager::Create(), CSoundManager::CreateFromMemory(), CSoundManager::CreateStreaming(), CD3DFrame::Destroy(), CMyD3DApplication::FinalCleanup(), CMyD3DApplication::FrameMove(), CWaveFile::ReadMMIO(), CD3DFrame::~CD3DFrame(), and CSound::~CSound().
#define SAFE_DELETE_ARRAY (p) { if(p) { delete[] (p); (p)=NULL; } }
Referenced by CWaveFile::Close(), D3DUtil_SetDeviceCursor(), CD3DMesh::Destroy(), CWaveFile::Open(), CSound::~CSound(), and CWaveFile::~CWaveFile().
#define SAFE_RELEASE (p) { if(p) { (p)->Release(); (p)=NULL; } }
Referenced by CMusicSegment::CMusicSegment(), CD3DMesh::Create(), CD3DFile::Create(), CD3DApplication::Create(), CD3DFile::CreateFromResource(), CSoundManager::CreateStreaming(), D3DUtil_SetDeviceCursor(), CD3DFont::DeleteDeviceObjects(), CMyD3DApplication::DeleteDeviceObjects(), CD3DMesh::Destroy(), CMyD3DApplication::FinalCleanup(), CSoundManager::Get3DListenerInterface(), CMusicManager::GetMotifFromStyle(), CSoundManager::Initialize(), CD3DApplication::Initialize3DEnvironment(), CD3DMesh::InvalidateDeviceObjects(), CD3DFont::InvalidateDeviceObjects(), CMyD3DApplication::InvalidateDeviceObjects(), CMyD3DApplication::RestoreDeviceObjects(), CD3DMesh::SetFVF(), CSoundManager::SetPrimaryBufferFormat(), CInputDeviceManager::~CInputDeviceManager(), CMusicManager::~CMusicManager(), CMusicScript::~CMusicScript(), CMusicSegment::~CMusicSegment(), CSound::~CSound(), and CSoundManager::~CSoundManager().
Enumeration Type Documentation
enum TIMER_COMMAND
Enumerator
TIMER_RESET
TIMER_START
TIMER_STOP
TIMER_ADVANCE
TIMER_GETABSOLUTETIME
TIMER_GETAPPTIME
TIMER_GETELAPSEDTIME
Function Documentation
HRESULT _DbgOut (TCHAR * , DWORD , HRESULT , TCHAR *)
VOID DXUtil_ConvertAnsiStringToGeneric (TCHAR * tstrDestination, const CHAR * strSource, int cchDestChar = -1)
Referenced by CD3DMesh::Create(), CD3DFile::LoadFrame(), and CD3DFile::LoadMesh().
VOID DXUtil_ConvertAnsiStringToWide (WCHAR * wstrDestination, const CHAR * strSource, int cchDestChar = -1)
Referenced by DXUtil_ConvertAnsiStringToGeneric(), and DXUtil_ConvertGenericStringToWide().
VOID DXUtil_ConvertGenericStringToAnsi (CHAR * strDestination, const TCHAR * tstrSource, int cchDestChar = -1)
Referenced by CD3DMesh::Create(), CD3DFile::Create(), and CD3DFile::CreateFromResource().
VOID DXUtil_ConvertGenericStringToWide (WCHAR * wstrDestination, const TCHAR * tstrSource, int cchDestChar = -1)
Referenced by CMusicScript::CallRoutine(), CMusicManager::CreateChordMapFromFile(), CMusicManager::CreateScriptFromFile(), CMusicManager::CreateSegmentFromFile(), CMusicManager::CreateStyleFromFile(), CMusicManager::GetMotifFromStyle(), CMusicScript::GetVariableNumber(), CMusicManager::SetSearchDirectory(), and CMusicScript::SetVariableNumber().
VOID DXUtil_ConvertGUIDToString (const GUID * pGuidIn, TCHAR * strOut)
BOOL DXUtil_ConvertStringToGUID (const TCHAR * strIn, GUID * pGuidOut)
VOID DXUtil_ConvertWideStringToAnsi (CHAR * strDestination, const WCHAR * wstrSource, int cchDestChar = -1)
Referenced by DXUtil_ConvertGenericStringToAnsi(), and DXUtil_ConvertWideStringToGeneric().
VOID DXUtil_ConvertWideStringToGeneric (TCHAR * tstrDestination, const WCHAR * wstrSource, int cchDestChar = -1)
HRESULT DXUtil_FindMediaFile (TCHAR * strPath, TCHAR * strFilename)
Referenced by CD3DMesh::Create(), CD3DFile::Create(), D3DUtil_CreateTexture(), and D3DUtil_CreateVertexShader().
const TCHAR* DXUtil_GetDXSDKMediaPath ()
Referenced by DXUtil_FindMediaFile().
HRESULT DXUtil_ReadBoolRegKey (HKEY hKey, TCHAR * strRegName, BOOL * pbValue, BOOL bDefault)
HRESULT DXUtil_ReadGuidRegKey (HKEY hKey, TCHAR * strRegName, GUID * pGuidValue, GUID & guidDefault)
HRESULT DXUtil_ReadIntRegKey (HKEY hKey, TCHAR * strRegName, DWORD * pdwValue, DWORD dwDefault)
Referenced by CMyD3DApplication::ReadSettings().
HRESULT DXUtil_ReadStringRegKey (HKEY hKey, TCHAR * strRegName, TCHAR * strValue, DWORD dwLength, TCHAR * strDefault)
Referenced by CMyD3DApplication::ReadSettings().
FLOAT __stdcall DXUtil_Timer (TIMER_COMMAND command)
Referenced by CD3DApplication::Create(), CD3DApplication::Pause(), CD3DApplication::Render3DEnvironment(), CD3DApplication::Resize3DEnvironment(), and CD3DApplication::UserSelectNewDevice().
VOID DXUtil_Trace (TCHAR * strMsg, ...)
HRESULT DXUtil_WriteBoolRegKey (HKEY hKey, TCHAR * strRegName, BOOL bValue)
HRESULT DXUtil_WriteGuidRegKey (HKEY hKey, TCHAR * strRegName, GUID guidValue)
HRESULT DXUtil_WriteIntRegKey (HKEY hKey, TCHAR * strRegName, DWORD dwValue)
Referenced by CMyD3DApplication::WriteSettings().
HRESULT DXUtil_WriteStringRegKey (HKEY hKey, TCHAR * strRegName, TCHAR * strValue)
Referenced by CMyD3DApplication::WriteSettings().