RigidChips: Lua/include/lua.h File Reference
lua.h File Reference
#include <stdarg.h>
#include <stddef.h>
Classes
struct lua_Debug
Macros
#define _MBCS
#define LUA_VERSION "Lua 5.0.2"
#define LUA_COPYRIGHT "Copyright (C) 1994-2004 Tecgraf, PUC-Rio"
#define LUA_AUTHORS "R. Ierusalimschy, L. H. de Figueiredo & W. Celes"
#define LUA_MULTRET (-1)
#define LUA_REGISTRYINDEX (-10000)
#define LUA_GLOBALSINDEX (-10001)
#define lua_upvalueindex(i) (LUA_GLOBALSINDEX-(i))
#define LUA_ERRRUN 1
#define LUA_ERRFILE 2
#define LUA_ERRSYNTAX 3
#define LUA_ERRMEM 4
#define LUA_ERRERR 5
#define LUA_TNONE (-1)
#define LUA_TNIL 0
#define LUA_TBOOLEAN 1
#define LUA_TLIGHTUSERDATA 2
#define LUA_TNUMBER 3
#define LUA_TSTRING 4
#define LUA_TTABLE 5
#define LUA_TFUNCTION 6
#define LUA_TUSERDATA 7
#define LUA_TTHREAD 8
#define LUA_MINSTACK 20
#define LUA_API extern
#define lua_boxpointer(L, u) (*(void **)(lua_newuserdata(L, sizeof(void *))) = (u))
#define lua_unboxpointer(L, i) (*(void **)(lua_touserdata(L, i)))
#define lua_pop(L, n) lua_settop(L, -(n)-1)
#define lua_register(L, n, f)
#define lua_pushcfunction(L, f) lua_pushcclosure(L, f, 0)
#define lua_isfunction(L, n) (lua_type(L,n) == LUA_TFUNCTION)
#define lua_istable(L, n) (lua_type(L,n) == LUA_TTABLE)
#define lua_islightuserdata(L, n) (lua_type(L,n) == LUA_TLIGHTUSERDATA)
#define lua_isnil(L, n) (lua_type(L,n) == LUA_TNIL)
#define lua_isboolean(L, n) (lua_type(L,n) == LUA_TBOOLEAN)
#define lua_isnone(L, n) (lua_type(L,n) == LUA_TNONE)
#define lua_isnoneornil(L, n) (lua_type(L,n) <= 0)
#define lua_pushliteral(L, s) lua_pushlstring(L, "" s, (sizeof(s)/sizeof(char))-1)
#define lua_getregistry(L) lua_pushvalue(L, LUA_REGISTRYINDEX)
#define lua_setglobal(L, s) (lua_pushstring(L, s), lua_insert(L, -2), lua_settable(L, LUA_GLOBALSINDEX))
#define lua_getglobal(L, s) (lua_pushstring(L, s), lua_gettable(L, LUA_GLOBALSINDEX))
#define LUA_NOREF (-2)
#define LUA_REFNIL (-1)
#define lua_ref(L, lock)
#define lua_unref(L, ref) luaL_unref(L, LUA_REGISTRYINDEX, (ref))
#define lua_getref(L, ref) lua_rawgeti(L, LUA_REGISTRYINDEX, ref)
#define LUA_NUMBER_SCAN "%lf"
#define LUA_NUMBER_FMT "%.14g"
#define LUA_HOOKCALL 0
#define LUA_HOOKRET 1
#define LUA_HOOKLINE 2
#define LUA_HOOKCOUNT 3
#define LUA_HOOKTAILRET 4
#define LUA_MASKCALL (1 << LUA_HOOKCALL)
#define LUA_MASKRET (1 << LUA_HOOKRET)
#define LUA_MASKLINE (1 << LUA_HOOKLINE)
#define LUA_MASKCOUNT (1 << LUA_HOOKCOUNT)
#define LUA_IDSIZE 60
Typedefs
typedef struct lua_State lua_State
typedef int(* lua_CFunction) (lua_State *L)
typedef const char *(* lua_Chunkreader) (lua_State *L, void *ud, size_t *sz)
typedef int(* lua_Chunkwriter) (lua_State *L, const void *p, size_t sz, void *ud)
typedef double lua_Number
typedef struct lua_Debug lua_Debug
typedef void(* lua_Hook) (lua_State *L, lua_Debug *ar)
Functions
LUA_API lua_State * lua_open (void)
LUA_API void lua_close (lua_State *L)
LUA_API lua_State * lua_newthread (lua_State *L)
LUA_API lua_CFunction lua_atpanic (lua_State *L, lua_CFunction panicf)
LUA_API int lua_gettop (lua_State *L)
LUA_API void lua_settop (lua_State *L, int idx)
LUA_API void lua_pushvalue (lua_State *L, int idx)
LUA_API void lua_remove (lua_State *L, int idx)
LUA_API void lua_insert (lua_State *L, int idx)
LUA_API void lua_replace (lua_State *L, int idx)
LUA_API int lua_checkstack (lua_State *L, int sz)
LUA_API void lua_xmove (lua_State *from, lua_State *to, int n)
LUA_API int lua_isnumber (lua_State *L, int idx)
LUA_API int lua_isstring (lua_State *L, int idx)
LUA_API int lua_iscfunction (lua_State *L, int idx)
LUA_API int lua_isuserdata (lua_State *L, int idx)
LUA_API int lua_type (lua_State *L, int idx)
LUA_API const char * lua_typename (lua_State *L, int tp)
LUA_API int lua_equal (lua_State *L, int idx1, int idx2)
LUA_API int lua_rawequal (lua_State *L, int idx1, int idx2)
LUA_API int lua_lessthan (lua_State *L, int idx1, int idx2)
LUA_API lua_Number lua_tonumber (lua_State *L, int idx)
LUA_API int lua_toboolean (lua_State *L, int idx)
LUA_API const char * lua_tostring (lua_State *L, int idx)
LUA_API size_t lua_strlen (lua_State *L, int idx)
LUA_API lua_CFunction lua_tocfunction (lua_State *L, int idx)
LUA_API void * lua_touserdata (lua_State *L, int idx)
LUA_API lua_State * lua_tothread (lua_State *L, int idx)
LUA_API const void * lua_topointer (lua_State *L, int idx)
LUA_API void lua_pushnil (lua_State *L)
LUA_API void lua_pushnumber (lua_State *L, lua_Number n)
LUA_API void lua_pushlstring (lua_State *L, const char *s, size_t l)
LUA_API void lua_pushstring (lua_State *L, const char *s)
LUA_API const char * lua_pushvfstring (lua_State *L, const char *fmt, va_list argp)
LUA_API const char * lua_pushfstring (lua_State *L, const char *fmt,...)
LUA_API void lua_pushcclosure (lua_State *L, lua_CFunction fn, int n)
LUA_API void lua_pushboolean (lua_State *L, int b)
LUA_API void lua_pushlightuserdata (lua_State *L, void *p)
LUA_API void lua_gettable (lua_State *L, int idx)
LUA_API void lua_rawget (lua_State *L, int idx)
LUA_API void lua_rawgeti (lua_State *L, int idx, int n)
LUA_API void lua_newtable (lua_State *L)
LUA_API void * lua_newuserdata (lua_State *L, size_t sz)
LUA_API int lua_getmetatable (lua_State *L, int objindex)
LUA_API void lua_getfenv (lua_State *L, int idx)
LUA_API void lua_settable (lua_State *L, int idx)
LUA_API void lua_rawset (lua_State *L, int idx)
LUA_API void lua_rawseti (lua_State *L, int idx, int n)
LUA_API int lua_setmetatable (lua_State *L, int objindex)
LUA_API int lua_setfenv (lua_State *L, int idx)
LUA_API void lua_call (lua_State *L, int nargs, int nresults)
LUA_API int lua_pcall (lua_State *L, int nargs, int nresults, int errfunc)
LUA_API int lua_cpcall (lua_State *L, lua_CFunction func, void *ud)
LUA_API int lua_load (lua_State *L, lua_Chunkreader reader, void *dt, const char *chunkname)
LUA_API int lua_dump (lua_State *L, lua_Chunkwriter writer, void *data)
LUA_API int lua_yield (lua_State *L, int nresults)
LUA_API int lua_resume (lua_State *L, int narg)
LUA_API int lua_getgcthreshold (lua_State *L)
LUA_API int lua_getgccount (lua_State *L)
LUA_API void lua_setgcthreshold (lua_State *L, int newthreshold)
LUA_API const char * lua_version (void)
LUA_API int lua_error (lua_State *L)
LUA_API int lua_next (lua_State *L, int idx)
LUA_API void lua_concat (lua_State *L, int n)
LUA_API int lua_pushupvalues (lua_State *L)
LUA_API int lua_getstack (lua_State *L, int level, lua_Debug *ar)
LUA_API int lua_getinfo (lua_State *L, const char *what, lua_Debug *ar)
LUA_API const char * lua_getlocal (lua_State *L, const lua_Debug *ar, int n)
LUA_API const char * lua_setlocal (lua_State *L, const lua_Debug *ar, int n)
LUA_API const char * lua_getupvalue (lua_State *L, int funcindex, int n)
LUA_API const char * lua_setupvalue (lua_State *L, int funcindex, int n)
LUA_API int lua_sethook (lua_State *L, lua_Hook func, int mask, int count)
LUA_API lua_Hook lua_gethook (lua_State *L)
LUA_API int lua_gethookmask (lua_State *L)
LUA_API int lua_gethookcount (lua_State *L)
Macro Definition Documentation
#define _MBCS
#define LUA_API extern
#define LUA_AUTHORS "R. Ierusalimschy, L. H. de Figueiredo & W. Celes"
#define lua_boxpointer (L, u) (*(void **)(lua_newuserdata(L, sizeof(void *))) = (u))
#define LUA_COPYRIGHT "Copyright (C) 1994-2004 Tecgraf, PUC-Rio"
#define LUA_ERRERR 5
#define LUA_ERRFILE 2
#define LUA_ERRMEM 4
Referenced by CMyD3DApplication::RenderText().
#define LUA_ERRRUN 1
#define LUA_ERRSYNTAX 3
Referenced by CMyD3DApplication::RenderText().
#define lua_getglobal (L, s) (lua_pushstring(L, s), lua_gettable(L, LUA_GLOBALSINDEX))
#define lua_getref (L, ref) lua_rawgeti(L, LUA_REGISTRYINDEX, ref)
#define lua_getregistry (L) lua_pushvalue(L, LUA_REGISTRYINDEX)
#define LUA_GLOBALSINDEX (-10001)
Referenced by luaScriptRun(), and luaSystemRun().
#define LUA_HOOKCALL 0
#define LUA_HOOKCOUNT 3
#define LUA_HOOKLINE 2
#define LUA_HOOKRET 1
#define LUA_HOOKTAILRET 4
#define LUA_IDSIZE 60
#define lua_isboolean (L, n) (lua_type(L,n) == LUA_TBOOLEAN)
Referenced by luaPrint(), and luaSystemPrint().
#define lua_isfunction (L, n) (lua_type(L,n) == LUA_TFUNCTION)
#define lua_islightuserdata (L, n) (lua_type(L,n) == LUA_TLIGHTUSERDATA)
#define lua_isnil (L, n) (lua_type(L,n) == LUA_TNIL)
Referenced by luaPrint(), and luaSystemPrint().
#define lua_isnone (L, n) (lua_type(L,n) == LUA_TNONE)
#define lua_isnoneornil (L, n) (lua_type(L,n) <= 0)
#define lua_istable (L, n) (lua_type(L,n) == LUA_TTABLE)
#define LUA_MASKCALL (1 << LUA_HOOKCALL)
#define LUA_MASKCOUNT (1 << LUA_HOOKCOUNT)
#define LUA_MASKLINE (1 << LUA_HOOKLINE)
#define LUA_MASKRET (1 << LUA_HOOKRET)
#define LUA_MINSTACK 20
#define LUA_MULTRET (-1)
#define LUA_NOREF (-2)
#define LUA_NUMBER_FMT "%.14g"
#define LUA_NUMBER_SCAN "%lf"
#define lua_pop (L, n) lua_settop(L, -(n)-1)
Referenced by luaScriptRun(), and luaSystemRun().
#define lua_pushcfunction (L, f) lua_pushcclosure(L, f, 0)
#define lua_pushliteral (L, s) lua_pushlstring(L, "" s, (sizeof(s)/sizeof(char))-1)
#define lua_ref (L, lock)
Value:
((lock) ? luaL_ref(L, LUA_REGISTRYINDEX) : \
      (lua_pushstring(L, "unlocked references are obsolete"), lua_error(L), 0))
#define LUA_REFNIL (-1)
#define lua_register (L, n, f)
Value:
(lua_pushstring(L, n), \
     lua_pushcfunction(L, f), \
     lua_settable(L, LUA_GLOBALSINDEX))
Referenced by luaScriptInit(), and luaSystemInit().
#define LUA_REGISTRYINDEX (-10000)
#define lua_setglobal (L, s) (lua_pushstring(L, s), lua_insert(L, -2), lua_settable(L, LUA_GLOBALSINDEX))
Referenced by luaScriptInit(), luaScriptRun(), luaSystemInit(), and luaSystemRun().
#define LUA_TBOOLEAN 1
#define LUA_TFUNCTION 6
#define LUA_TLIGHTUSERDATA 2
#define LUA_TNIL 0
#define LUA_TNONE (-1)
#define LUA_TNUMBER 3
#define LUA_TSTRING 4
#define LUA_TTABLE 5
#define LUA_TTHREAD 8
#define LUA_TUSERDATA 7
#define lua_unboxpointer (L, i) (*(void **)(lua_touserdata(L, i)))
#define lua_unref (L, ref) luaL_unref(L, LUA_REGISTRYINDEX, (ref))
#define lua_upvalueindex (i) (LUA_GLOBALSINDEX-(i))
#define LUA_VERSION "Lua 5.0.2"
Typedef Documentation
typedef int(* lua_CFunction) (lua_State *L)
typedef const char*(* lua_Chunkreader) (lua_State *L, void *ud, size_t *sz)
typedef int(* lua_Chunkwriter) (lua_State *L, const void *p, size_t sz, void *ud)
typedef struct lua_Debug lua_Debug
typedef void(* lua_Hook) (lua_State *L, lua_Debug *ar)
typedef double lua_Number
typedef struct lua_State lua_State
Function Documentation
LUA_API lua_CFunction lua_atpanic (lua_State * L, lua_CFunction panicf)
LUA_API void lua_call (lua_State * L, int nargs, int nresults)
LUA_API int lua_checkstack (lua_State * L, int sz)
LUA_API void lua_close (lua_State * L)
Referenced by luaScriptEnd(), luaScriptInit(), luaSystemEnd(), and luaSystemInit().
LUA_API void lua_concat (lua_State * L, int n)
LUA_API int lua_cpcall (lua_State * L, lua_CFunction func, void * ud)
LUA_API int lua_dump (lua_State * L, lua_Chunkwriter writer, void * data)
LUA_API int lua_equal (lua_State * L, int idx1, int idx2)
LUA_API int lua_error (lua_State * L)
LUA_API void lua_getfenv (lua_State * L, int idx)
LUA_API int lua_getgccount (lua_State * L)
LUA_API int lua_getgcthreshold (lua_State * L)
LUA_API lua_Hook lua_gethook (lua_State * L)
LUA_API int lua_gethookcount (lua_State * L)
LUA_API int lua_gethookmask (lua_State * L)
LUA_API int lua_getinfo (lua_State * L, const char * what, lua_Debug * ar)
LUA_API const char* lua_getlocal (lua_State * L, const lua_Debug * ar, int n)
LUA_API int lua_getmetatable (lua_State * L, int objindex)
LUA_API int lua_getstack (lua_State * L, int level, lua_Debug * ar)
LUA_API void lua_gettable (lua_State * L, int idx)
Referenced by luaScriptRun(), and luaSystemRun().
LUA_API int lua_gettop (lua_State * L)
Referenced by luaPrint(), and luaSystemPrint().
LUA_API const char* lua_getupvalue (lua_State * L, int funcindex, int n)
LUA_API void lua_insert (lua_State * L, int idx)
LUA_API int lua_iscfunction (lua_State * L, int idx)
LUA_API int lua_isnumber (lua_State * L, int idx)
Referenced by luaPrint(), and luaSystemPrint().
LUA_API int lua_isstring (lua_State * L, int idx)
Referenced by luaPrint(), and luaSystemPrint().
LUA_API int lua_isuserdata (lua_State * L, int idx)
LUA_API int lua_lessthan (lua_State * L, int idx1, int idx2)
LUA_API int lua_load (lua_State * L, lua_Chunkreader reader, void * dt, const char * chunkname)
LUA_API void lua_newtable (lua_State * L)
LUA_API lua_State* lua_newthread (lua_State * L)
LUA_API void* lua_newuserdata (lua_State * L, size_t sz)
LUA_API int lua_next (lua_State * L, int idx)
LUA_API lua_State* lua_open (void)
Referenced by luaScriptInit(), and luaSystemInit().
LUA_API int lua_pcall (lua_State * L, int nargs, int nresults, int errfunc)
Referenced by luaScriptRun(), and luaSystemRun().
LUA_API void lua_pushboolean (lua_State * L, int b)
LUA_API void lua_pushcclosure (lua_State * L, lua_CFunction fn, int n)
LUA_API const char* lua_pushfstring (lua_State * L, const char * fmt, ...)
LUA_API void lua_pushlightuserdata (lua_State * L, void * p)
LUA_API void lua_pushlstring (lua_State * L, const char * s, size_t l)
LUA_API void lua_pushnil (lua_State * L)
LUA_API void lua_pushnumber (lua_State * L, lua_Number n)
Referenced by luaAddBall(), luaAddChip(), luaAnalog(), luaAx(), luaAy(), luaAz(), luaCheckObjRingArea(), luaCheckRingArea(), luaChips(), luaCollisionObjRingArea(), luaCollisionRingArea(), luaEx(), luaEy(), luaEz(), luaFileClose(), luaFileOpen(), luaFilePuts(), luaFx(), luaFy(), luaFz(), luaGetAngle(), luaGetBase(), luaGetBrake(), luaGetCCD(), luaGetCCDBlue(), luaGetCCDGreen(), luaGetCCDRed(), luaGetChild(), luaGetChip(), luaGetColor(), luaGetDamper(), luaGetDir(), luaGetDt(), luaGetEffect(), luaGetEnergy(), luaGetFaces(), luaGetFps(), luaGetFuel(), luaGetFuelMax(), luaGetH(), luaGetHeight(), luaGetI(), luaGetM(), luaGetMouseL(), luaGetMouseM(), luaGetMouseR(), luaGetMouseX(), luaGetMouseY(), luaGetObjI(), luaGetObjM(), luaGetOption(), luaGetParent(), luaGetPlayerArms(), luaGetPlayerChips(), luaGetPlayerColor(), luaGetPlayerCrushes(), luaGetPlayerHostID(), luaGetPlayerID(), luaGetPlayerInits(), luaGetPlayerMyID(), luaGetPlayerResets(), luaGetPlayers(), luaGetPlayerX(), luaGetPlayerY(), luaGetPlayerYForces(), luaGetPlayerZ(), luaGetPower(), luaGetRing(), luaGetRingState(), luaGetSMouseL(), luaGetSMouseM(), luaGetSMouseR(), luaGetSMouseX(), luaGetSMouseY(), luaGetSpring(), luaGetSystemKey(), luaGetSystemKeyDown(), luaGetSystemKeyUp(), luaGetSystemTickCount(), luaGetTickCount(), luaGetTolerant(), luaGetTop(), luaGetType(), luaGetUserEffect(), luaGetUserOption(), luaGetView(), luaGetViewType(), luaGetViewZoom(), luaGetWidth(), luaGetWind(), luaGetY(), luaGx(), luaGy(), luaGz(), luaHat(), luaHitCount(), luaHitCountObj(), luaKey(), luaKey2(), luaKeyDown(), luaKeyDown2(), luaKeyUp(), luaKeyUp2(), luaLen2(), luaLen3(), luaLine2D(), luaLine3D(), luaLoadLand(), luaLx(), luaLy(), luaLz(), luaMove2D(), luaMove3D(), luaObjPosx(), luaObjPosy(), luaObjPosz(), luaPI(), luaPosx(), luaPosy(), luaPosz(), luaQw(), luaQx(), luaQy(), luaQz(), luaRnd(), luaRound(), luaRx(), luaRy(), luaRz(), luaSaveChips(), luaScriptInit(), luaScriptRun(), luaSetCCDZoom(), luaSetColor(), luaSetTicks(), luaSystemInit(), luaSystemRun(), luaToDeg(), luaToRad(), luaUnLink(), luaUnLinkBye(), luaUpdateChips(), luaVel(), luaVx(), luaVy(), luaVz(), luaWeight(), luaWx(), luaWy(), luaWz(), luaXx(), luaXy(), luaXz(), luaYx(), luaYy(), luaYz(), luaZx(), luaZy(), and luaZz().
LUA_API void lua_pushstring (lua_State * L, const char * s)
Referenced by luaFileGets(), luaGetLastChat(), luaGetPlayerName(), luaReceiveMessage(), luaScriptRun(), and luaSystemRun().
LUA_API int lua_pushupvalues (lua_State * L)
LUA_API void lua_pushvalue (lua_State * L, int idx)
LUA_API const char* lua_pushvfstring (lua_State * L, const char * fmt, va_list argp)
LUA_API int lua_rawequal (lua_State * L, int idx1, int idx2)
LUA_API void lua_rawget (lua_State * L, int idx)
LUA_API void lua_rawgeti (lua_State * L, int idx, int n)
LUA_API void lua_rawset (lua_State * L, int idx)
LUA_API void lua_rawseti (lua_State * L, int idx, int n)
LUA_API void lua_remove (lua_State * L, int idx)
LUA_API void lua_replace (lua_State * L, int idx)
LUA_API int lua_resume (lua_State * L, int narg)
LUA_API int lua_setfenv (lua_State * L, int idx)
LUA_API void lua_setgcthreshold (lua_State * L, int newthreshold)
LUA_API int lua_sethook (lua_State * L, lua_Hook func, int mask, int count)
LUA_API const char* lua_setlocal (lua_State * L, const lua_Debug * ar, int n)
LUA_API int lua_setmetatable (lua_State * L, int objindex)
LUA_API void lua_settable (lua_State * L, int idx)
LUA_API void lua_settop (lua_State * L, int idx)
LUA_API const char* lua_setupvalue (lua_State * L, int funcindex, int n)
LUA_API size_t lua_strlen (lua_State * L, int idx)
LUA_API int lua_toboolean (lua_State * L, int idx)
Referenced by luaPrint(), and luaSystemPrint().
LUA_API lua_CFunction lua_tocfunction (lua_State * L, int idx)
LUA_API lua_Number lua_tonumber (lua_State * L, int idx)
Referenced by luaAddBall(), luaAddChip(), luaAnalog(), luaApplyForce(), luaApplyForceObj(), luaApplyTorque(), luaApplyTorqueObj(), luaAx(), luaAy(), luaAz(), luaCheckObjRingArea(), luaCheckRingArea(), luaCollisionObjRingArea(), luaCollisionRingArea(), luaControlKeyLock(), luaDirect(), luaDirectObj(), luaEnervate(), luaEnervateObj(), luaEx(), luaEy(), luaEz(), luaFileClose(), luaFileGets(), luaFilePuts(), luaFx(), luaFy(), luaFz(), luaGetAngle(), luaGetBrake(), luaGetCCD(), luaGetCCDBlue(), luaGetCCDGreen(), luaGetCCDRed(), luaGetChild(), luaGetChip(), luaGetColor(), luaGetDamper(), luaGetDir(), luaGetEffect(), luaGetEnergy(), luaGetFuel(), luaGetFuelMax(), luaGetH(), luaGetI(), luaGetM(), luaGetObjI(), luaGetObjM(), luaGetOption(), luaGetParent(), luaGetPlayerArms(), luaGetPlayerChips(), luaGetPlayerColor(), luaGetPlayerCrushes(), luaGetPlayerID(), luaGetPlayerInits(), luaGetPlayerName(), luaGetPlayerResets(), luaGetPlayerX(), luaGetPlayerY(), luaGetPlayerYForces(), luaGetPlayerZ(), luaGetPower(), luaGetRing(), luaGetRingState(), luaGetSpring(), luaGetSystemKey(), luaGetSystemKeyDown(), luaGetSystemKeyUp(), luaGetTolerant(), luaGetTop(), luaGetType(), luaGetUserEffect(), luaGetUserOption(), luaGetY(), luaGx(), luaGy(), luaGz(), luaHat(), luaHitCount(), luaHitCountObj(), luaKey(), luaKey2(), luaKeyDown(), luaKeyDown2(), luaKeyLock(), luaKeyUp(), luaKeyUp2(), luaLen2(), luaLen3(), luaLine2D(), luaLine3D(), luaLx(), luaLy(), luaLz(), luaMove2D(), luaMove3D(), luaObjPosx(), luaObjPosy(), luaObjPosz(), luaPosx(), luaPosy(), luaPosz(), luaPrint(), luaQw(), luaQx(), luaQy(), luaQz(), luaReceiveMessage(), luaReceiveMessageClear(), luaReset(), luaRotate(), luaRotateObj(), luaRound(), luaRx(), luaRy(), luaRz(), luaScriptRun(), luaSetCCDZoom(), luaSetChip(), luaSetColor(), luaSetObjColor(), luaSetObjFix(), luaSetRegulationFlag(), luaSetRing(), luaSetRingColor(), luaSetRingState(), luaSetTarget(), luaSetTicks(), luaSetView(), luaSetViewType(), luaSetViewUp(), luaSetViewZoom(), luaSystemPrint(), luaSystemRun(), luaToDeg(), luaToRad(), luaUnLink(), luaUnLinkBye(), luaVel(), luaVx(), luaVy(), luaVz(), luaWarp(), luaWarpObj(), luaWind(), luaWx(), luaWy(), luaWz(), luaXx(), luaXy(), luaXz(), luaYx(), luaYy(), luaYz(), luaZx(), luaZy(), and luaZz().
LUA_API const void* lua_topointer (lua_State * L, int idx)
Referenced by luaPrint(), luaScriptRun(), luaSystemPrint(), and luaSystemRun().
LUA_API const char* lua_tostring (lua_State * L, int idx)
Referenced by luaAddChip(), luaFileOpen(), luaFilePuts(), luaGetChip(), luaHitCount(), luaHitCountObj(), luaLoadLand(), luaPrint(), luaSaveChips(), luaScriptInit(), luaScriptRun(), luaSendAllMessage(), luaSetChip(), luaSetRegulationFlag(), luaSystemInit(), luaSystemPrint(), and luaSystemRun().
LUA_API lua_State* lua_tothread (lua_State * L, int idx)
LUA_API void* lua_touserdata (lua_State * L, int idx)
LUA_API int lua_type (lua_State * L, int idx)
Referenced by luaPrint(), and luaSystemPrint().
LUA_API const char* lua_typename (lua_State * L, int tp)
Referenced by luaPrint(), and luaSystemPrint().
LUA_API const char* lua_version (void)
LUA_API void lua_xmove (lua_State * from, lua_State * to, int n)
LUA_API int lua_yield (lua_State * L, int nresults)