RigidChips: Lua/include/lualib.h File Reference
lualib.h File Reference
#include "lua.h"
Macros
#define LUALIB_API LUA_API
#define LUA_COLIBNAME "coroutine"
#define LUA_TABLIBNAME "table"
#define LUA_IOLIBNAME "io"
#define LUA_OSLIBNAME "os"
#define LUA_STRLIBNAME "string"
#define LUA_MATHLIBNAME "math"
#define LUA_DBLIBNAME "debug"
#define lua_assert(c) /* empty */
#define lua_baselibopen luaopen_base
#define lua_tablibopen luaopen_table
#define lua_iolibopen luaopen_io
#define lua_strlibopen luaopen_string
#define lua_mathlibopen luaopen_math
#define lua_dblibopen luaopen_debug
Functions
LUALIB_API int luaopen_base (lua_State *L)
LUALIB_API int luaopen_table (lua_State *L)
LUALIB_API int luaopen_io (lua_State *L)
LUALIB_API int luaopen_string (lua_State *L)
LUALIB_API int luaopen_math (lua_State *L)
LUALIB_API int luaopen_debug (lua_State *L)
LUALIB_API int luaopen_loadlib (lua_State *L)
Macro Definition Documentation
#define lua_assert (c) /* empty */
#define lua_baselibopen luaopen_base
#define LUA_COLIBNAME "coroutine"
#define LUA_DBLIBNAME "debug"
#define lua_dblibopen luaopen_debug
#define LUA_IOLIBNAME "io"
#define lua_iolibopen luaopen_io
#define LUA_MATHLIBNAME "math"
#define lua_mathlibopen luaopen_math
#define LUA_OSLIBNAME "os"
#define LUA_STRLIBNAME "string"
#define lua_strlibopen luaopen_string
#define LUA_TABLIBNAME "table"
#define lua_tablibopen luaopen_table
#define LUALIB_API LUA_API
Function Documentation
LUALIB_API int luaopen_base (lua_State * L)
Referenced by luaScriptInit(), and luaSystemInit().
LUALIB_API int luaopen_debug (lua_State * L)
LUALIB_API int luaopen_io (lua_State * L)
LUALIB_API int luaopen_loadlib (lua_State * L)
LUALIB_API int luaopen_math (lua_State * L)
Referenced by luaScriptInit(), and luaSystemInit().
LUALIB_API int luaopen_string (lua_State * L)
Referenced by luaScriptInit(), and luaSystemInit().
LUALIB_API int luaopen_table (lua_State * L)
Referenced by luaScriptInit(), and luaSystemInit().