RigidChips: luaScript.cpp File Reference
luaScript.cpp File Reference
#include <windows.h>
#include <basetsd.h>
#include <math.h>
#include <stdio.h>
#include <D3DX8.h>
#include <DXErr8.h>
#include <tchar.h>
#include <dinput.h>
#include "D3DApp.h"
#include "D3DFont.h"
#include "D3DFile.h"
#include "D3DUtil.h"
#include "DIUtil.h"
#include "DMUtil.h"
#include "DSUtil.h"
#include "DXUtil.h"
#include "D3Dtypes.h"
#include <stdlib.h>
#include <locale.h>
#include "string.h"
#include "ctype.h"
#include "readData.hpp"
#include "luaScript.hpp"
#include "luaSub.hpp"
#include <crtdbg.h>
Macros
#define STRICT
#define DIRECTINPUT_VERSION 0x0800
Functions
int luaPrint (lua_State *L)
lua_State * luaScriptInit (char *buff)
void luaScriptEnd (lua_State *L)
int luaScriptRun (lua_State *L, char *funcName)
Variables
char szUpdateFileName0 []
float luaL3dx
float luaL3dy
float luaL3dz
int luaGraColor
int randTime
Macro Definition Documentation
#define DIRECTINPUT_VERSION 0x0800
#define STRICT
Function Documentation
int luaPrint (lua_State * L)
Referenced by luaScriptInit().
void luaScriptEnd (lua_State * L)
Referenced by CMyD3DApplication::FinalCleanup(), CMyD3DApplication::FrameMove(), CMyD3DApplication::InitChips(), readData(), readData2(), and CMyD3DApplication::ResetChips().
lua_State* luaScriptInit (char * buff)
Referenced by CMyD3DApplication::FrameMove(), CMyD3DApplication::InitChips(), readData2(), and CMyD3DApplication::ResetChips().
int luaScriptRun (lua_State * L, char * funcName)
Referenced by CMyD3DApplication::FrameMove(), CMyD3DApplication::InitChips(), CMyD3DApplication::OneTimeSceneInit(), CMyD3DApplication::Render(), and CMyD3DApplication::ResetChips().
Variable Documentation
int luaGraColor
Referenced by luaScriptInit().
float luaL3dx
Referenced by luaScriptInit().
float luaL3dy
Referenced by luaScriptInit().
float luaL3dz
Referenced by luaScriptInit().
int randTime
Referenced by luaScriptRun().
char szUpdateFileName0[]
Referenced by luaScriptInit().