RigidChips: luaSystem.cpp File Reference
luaSystem.cpp File Reference
#include <windows.h>
#include <basetsd.h>
#include <math.h>
#include <stdio.h>
#include <D3DX8.h>
#include <DXErr8.h>
#include <tchar.h>
#include <dinput.h>
#include "D3DApp.h"
#include "D3DFont.h"
#include "D3DFile.h"
#include "D3DUtil.h"
#include "DIUtil.h"
#include "DMUtil.h"
#include "DSUtil.h"
#include "DXUtil.h"
#include "D3Dtypes.h"
#include <stdlib.h>
#include <locale.h>
#include "string.h"
#include "ctype.h"
#include "readData.hpp"
#include "luaSystem.hpp"
#include "luaSub.hpp"
#include "GDPlay.hpp"
#include "GPlayers.h"
#include <crtdbg.h>
Macros
#define STRICT
#define DIRECTINPUT_VERSION 0x0800
#define FILEMAX 32
Functions
int luaGetLastChat (lua_State *L)
int luaControlKeyLock (lua_State *L)
int OpenFp (char *name, char *mode)
int CloseFp (int n)
int luaSendAllMessage (lua_State *L)
int luaReceiveMessage (lua_State *L)
int luaReceiveMessageClear (lua_State *L)
int luaFileOpen (lua_State *L)
int luaFileClose (lua_State *L)
int luaFilePuts (lua_State *L)
int luaFileGets (lua_State *L)
int luaReset (lua_State *L)
int luaSetTarget (lua_State *L)
int luaKeyLock (lua_State *L)
int luaGetSystemTickCount (lua_State *L)
int luaSetView (lua_State *L)
int luaSetViewUp (lua_State *L)
int luaGetView (lua_State *L)
int luaSetViewType (lua_State *L)
int luaGetViewType (lua_State *L)
int luaSetViewZoom (lua_State *L)
int luaGetViewZoom (lua_State *L)
int luaSetRegulationFlag (lua_State *L)
int luaLoadLand (lua_State *L)
int luaSaveChips (lua_State *L)
int luaUpdateChips (lua_State *L)
int luaWind (lua_State *L)
int luaGetWind (lua_State *L)
int luaAddBall (lua_State *L)
int luaSetObjFix (lua_State *L)
int luaSetObjColor (lua_State *L)
int luaSetRingState (lua_State *L)
int luaGetRingState (lua_State *L)
int luaSetRingColor (lua_State *L)
int luaCheckRingArea (lua_State *L)
int luaCheckObjRingArea (lua_State *L)
int luaCollisionRingArea (lua_State *L)
int luaCollisionObjRingArea (lua_State *L)
int luaGetRing (lua_State *L)
int luaSetRing (lua_State *L)
int luaHitCountObj (lua_State *L)
int luaHitCount (lua_State *L)
int luaWarp (lua_State *L)
int luaWarpObj (lua_State *L)
int luaRotate (lua_State *L)
int luaRotateObj (lua_State *L)
int luaDirect (lua_State *L)
int luaDirectObj (lua_State *L)
int luaEnervate (lua_State *L)
int luaEnervateObj (lua_State *L)
int luaPause (lua_State *L)
int luaPlay (lua_State *L)
int luaGetSystemKey (lua_State *L)
int luaGetSystemKeyDown (lua_State *L)
int luaGetSystemKeyUp (lua_State *L)
int luaApplyTorqueObj (lua_State *L)
int luaApplyForceObj (lua_State *L)
int luaApplyTorque (lua_State *L)
int luaApplyForce (lua_State *L)
int luaGetH (lua_State *L)
int luaAddChip (lua_State *L)
int luaGetChild (lua_State *L)
int luaGetChip (lua_State *L)
int luaSetChip (lua_State *L)
int luaSystemPrint (lua_State *L)
int LoadSystem (char *fileName)
int luaSystemInit ()
void luaSystemEnd ()
int luaSystemRun (char *funcName)
Variables
CMyD3DApplication * g_pApp
char szUpdateFileName0 []
float luaL3dx
float luaL3dy
float luaL3dz
int luaGraColor
GVector CompassTarget
int ViewUpdate
char SystemOutput [GOUTPUTMAX][512]
char * SystemSource =NULL
int SystemErrorCode
char SystemErrorStr [512]
lua_State * SystemL =NULL
int scenarioCode
bool GravityFlag
bool AirFlag
bool TorqueFlag
bool JetFlag
bool UnbreakableFlag
bool ScriptFlag
bool CCDFlag
bool EfficientFlag
GRing Ring []
int ChipCount
float Zoom
GDPlay * DPlay
GPLAYERDATA PlayerData []
GMYDATA MyPlayerData
char LastChatData []
FILE * FpTable [32]
bool ControlKeysLock []
Macro Definition Documentation
#define DIRECTINPUT_VERSION 0x0800
#define FILEMAX 32
Referenced by CloseFp(), luaFileGets(), luaFilePuts(), luaSystemEnd(), luaSystemInit(), and OpenFp().
#define STRICT
Function Documentation
int CloseFp (int n)
Referenced by luaFileClose().
int LoadSystem (char * fileName)
Referenced by CMyD3DApplication::FrameMove(), and CMyD3DApplication::OneTimeSceneInit().
int luaAddBall (lua_State * L)
Referenced by luaSystemInit().
int luaAddChip (lua_State * L)
Referenced by luaSystemInit().
int luaApplyForce (lua_State * L)
Referenced by luaSystemInit().
int luaApplyForceObj (lua_State * L)
Referenced by luaSystemInit().
int luaApplyTorque (lua_State * L)
Referenced by luaSystemInit().
int luaApplyTorqueObj (lua_State * L)
Referenced by luaSystemInit().
int luaCheckObjRingArea (lua_State * L)
Referenced by luaSystemInit().
int luaCheckRingArea (lua_State * L)
Referenced by luaSystemInit().
int luaCollisionObjRingArea (lua_State * L)
Referenced by luaSystemInit().
int luaCollisionRingArea (lua_State * L)
Referenced by luaSystemInit().
int luaControlKeyLock (lua_State * L)
Referenced by luaSystemInit().
int luaDirect (lua_State * L)
Referenced by luaSystemInit().
int luaDirectObj (lua_State * L)
Referenced by luaSystemInit().
int luaEnervate (lua_State * L)
Referenced by luaSystemInit().
int luaEnervateObj (lua_State * L)
Referenced by luaSystemInit().
int luaFileClose (lua_State * L)
Referenced by luaSystemInit().
int luaFileGets (lua_State * L)
Referenced by luaSystemInit().
int luaFileOpen (lua_State * L)
Referenced by luaSystemInit().
int luaFilePuts (lua_State * L)
Referenced by luaSystemInit().
int luaGetChild (lua_State * L)
Referenced by luaSystemInit().
int luaGetChip (lua_State * L)
Referenced by luaSystemInit().
int luaGetH (lua_State * L)
Referenced by luaSystemInit().
int luaGetLastChat (lua_State * L)
Referenced by luaSystemInit().
int luaGetRing (lua_State * L)
Referenced by luaSystemInit().
int luaGetRingState (lua_State * L)
Referenced by luaSystemInit().
int luaGetSystemKey (lua_State * L)
Referenced by luaSystemInit().
int luaGetSystemKeyDown (lua_State * L)
Referenced by luaSystemInit().
int luaGetSystemKeyUp (lua_State * L)
Referenced by luaSystemInit().
int luaGetSystemTickCount (lua_State * L)
Referenced by luaSystemInit().
int luaGetView (lua_State * L)
Referenced by luaSystemInit().
int luaGetViewType (lua_State * L)
Referenced by luaSystemInit().
int luaGetViewZoom (lua_State * L)
Referenced by luaSystemInit().
int luaGetWind (lua_State * L)
Referenced by luaSystemInit().
int luaHitCount (lua_State * L)
Referenced by luaSystemInit().
int luaHitCountObj (lua_State * L)
Referenced by luaSystemInit().
int luaKeyLock (lua_State * L)
Referenced by luaSystemInit().
int luaLoadLand (lua_State * L)
Referenced by luaSystemInit().
int luaPause (lua_State * L)
Referenced by luaSystemInit().
int luaPlay (lua_State * L)
Referenced by luaSystemInit().
int luaReceiveMessage (lua_State * L)
Referenced by luaSystemInit().
int luaReceiveMessageClear (lua_State * L)
Referenced by luaSystemInit().
int luaReset (lua_State * L)
Referenced by luaSystemInit().
int luaRotate (lua_State * L)
Referenced by luaSystemInit().
int luaRotateObj (lua_State * L)
Referenced by luaSystemInit().
int luaSaveChips (lua_State * L)
Referenced by luaSystemInit().
int luaSendAllMessage (lua_State * L)
Referenced by luaSystemInit().
int luaSetChip (lua_State * L)
Referenced by luaSystemInit().
int luaSetObjColor (lua_State * L)
Referenced by luaSystemInit().
int luaSetObjFix (lua_State * L)
Referenced by luaSystemInit().
int luaSetRegulationFlag (lua_State * L)
Referenced by luaSystemInit().
int luaSetRing (lua_State * L)
Referenced by luaSystemInit().
int luaSetRingColor (lua_State * L)
Referenced by luaSystemInit().
int luaSetRingState (lua_State * L)
Referenced by luaSystemInit().
int luaSetTarget (lua_State * L)
Referenced by luaSystemInit().
int luaSetView (lua_State * L)
Referenced by luaSystemInit().
int luaSetViewType (lua_State * L)
Referenced by luaSystemInit().
int luaSetViewUp (lua_State * L)
Referenced by luaSystemInit().
int luaSetViewZoom (lua_State * L)
Referenced by luaSystemInit().
void luaSystemEnd ()
Referenced by CMyD3DApplication::FinalCleanup(), and luaSystemInit().
int luaSystemInit ()
Referenced by CMyD3DApplication::FrameMove(), and CMyD3DApplication::OneTimeSceneInit().
int luaSystemPrint (lua_State * L)
Referenced by luaSystemInit().
int luaSystemRun (char * funcName)
Referenced by DlgNetworkProc(), CMyD3DApplication::FrameMove(), CMyD3DApplication::InitChips(), MyReceiveFunc(), CMyD3DApplication::OneTimeSceneInit(), CMyD3DApplication::Render(), and CMyD3DApplication::ResetChips().
int luaUpdateChips (lua_State * L)
Referenced by luaSystemInit().
int luaWarp (lua_State * L)
Referenced by luaSystemInit().
int luaWarpObj (lua_State * L)
Referenced by luaSystemInit().
int luaWind (lua_State * L)
Referenced by luaSystemInit().
int OpenFp (char * name, char * mode)
Referenced by luaFileOpen().
Variable Documentation
bool AirFlag
Referenced by GRigid::ApplyExtForce(), CMyD3DApplication::FrameMove(), luaSetRegulationFlag(), CMyD3DApplication::MsgProc(), CMyD3DApplication::OneTimeSceneInit(), CMyD3DApplication::PlayLog(), CMyD3DApplication::RenderText(), and CMyD3DApplication::SetRegulationMenu().
bool CCDFlag
Referenced by CMyD3DApplication::FrameMove(), luaSetRegulationFlag(), CMyD3DApplication::MsgProc(), CMyD3DApplication::OneTimeSceneInit(), CMyD3DApplication::PlayLog(), CMyD3DApplication::Render(), CMyD3DApplication::RenderText(), and CMyD3DApplication::SetRegulationMenu().
int ChipCount
Referenced by luaAddChip(), luaCheckRingArea(), luaCollisionRingArea(), luaPause(), luaReset(), and luaUpdateChips().
GVector CompassTarget
Referenced by CMyD3DApplication::Render().
bool ControlKeysLock[]
Referenced by CMyD3DApplication::CMyD3DApplication(), CMyD3DApplication::FrameMove(), luaControlKeyLock(), and luaSystemInit().
GDPlay* DPlay
bool EfficientFlag
Referenced by CMyD3DApplication::FrameMove(), luaSetRegulationFlag(), CMyD3DApplication::MsgProc(), CMyD3DApplication::PlayLog(), CMyD3DApplication::RenderText(), CMyD3DApplication::SaveLog(), and CMyD3DApplication::SetRegulationMenu().
FILE* FpTable[32]
Referenced by CloseFp(), luaFileGets(), luaFilePuts(), luaSystemEnd(), luaSystemInit(), and OpenFp().
CMyD3DApplication* g_pApp
bool GravityFlag
Referenced by CMyD3DApplication::FrameMove(), luaSetRegulationFlag(), CMyD3DApplication::MsgProc(), CMyD3DApplication::OneTimeSceneInit(), CMyD3DApplication::PlayLog(), CMyD3DApplication::RenderText(), and CMyD3DApplication::SetRegulationMenu().
bool JetFlag
Referenced by GRigid::DispJet(), GWorld::DispNetJet(), CMyD3DApplication::FrameMove(), luaSetRegulationFlag(), CMyD3DApplication::MsgProc(), CMyD3DApplication::OneTimeSceneInit(), CMyD3DApplication::PlayLog(), CMyD3DApplication::RenderText(), and CMyD3DApplication::SetRegulationMenu().
char LastChatData[]
Referenced by CMyD3DApplication::CMyD3DApplication(), DlgNetworkProc(), luaGetLastChat(), and MyReceiveFunc().
int luaGraColor
Referenced by luaLine2D(), luaLine3D(), luaSetColor(), and luaSystemInit().
float luaL3dx
Referenced by luaLine3D(), luaMove3D(), and luaSystemInit().
float luaL3dy
Referenced by luaLine3D(), luaMove3D(), and luaSystemInit().
float luaL3dz
Referenced by luaLine3D(), luaMove3D(), and luaSystemInit().
GMYDATA MyPlayerData
GPLAYERDATA PlayerData[]
GRing Ring[]
int scenarioCode
Referenced by DlgNetworkProc(), CMyD3DApplication::FrameMove(), LoadSystem(), luaReceiveMessage(), and MyReceiveFunc().
bool ScriptFlag
Referenced by CMyD3DApplication::FrameMove(), luaSetRegulationFlag(), CMyD3DApplication::MsgProc(), CMyD3DApplication::PlayLog(), CMyD3DApplication::Render(), CMyD3DApplication::RenderText(), CMyD3DApplication::SaveLog(), and CMyD3DApplication::SetRegulationMenu().
int SystemErrorCode
Referenced by luaSystemInit(), luaSystemRun(), and CMyD3DApplication::RenderText().
char SystemErrorStr[512]
Referenced by luaSystemInit(), luaSystemRun(), and CMyD3DApplication::RenderText().
lua_State* SystemL =NULL
Referenced by DlgNetworkProc(), CMyD3DApplication::FrameMove(), CMyD3DApplication::InitChips(), luaSystemEnd(), luaSystemInit(), luaSystemRun(), MyReceiveFunc(), CMyD3DApplication::OneTimeSceneInit(), CMyD3DApplication::Render(), and CMyD3DApplication::ResetChips().
char SystemOutput[GOUTPUTMAX][512]
Referenced by luaSystemPrint(), luaSystemRun(), and CMyD3DApplication::RenderText().
char* SystemSource =NULL
Referenced by CMyD3DApplication::FinalCleanup(), LoadSystem(), and luaSystemInit().
char szUpdateFileName0[]
bool TorqueFlag
Referenced by CMyD3DApplication::FrameMove(), luaSetRegulationFlag(), CMyD3DApplication::MsgProc(), CMyD3DApplication::OneTimeSceneInit(), CMyD3DApplication::PlayLog(), CMyD3DApplication::RenderText(), and CMyD3DApplication::SetRegulationMenu().
bool UnbreakableFlag
Referenced by CMyD3DApplication::FrameMove(), luaSetRegulationFlag(), CMyD3DApplication::MsgProc(), CMyD3DApplication::OneTimeSceneInit(), CMyD3DApplication::PlayLog(), CMyD3DApplication::RenderText(), and CMyD3DApplication::SetRegulationMenu().
int ViewUpdate
Referenced by luaSetView(), luaSetViewUp(), luaSetViewZoom(), and CMyD3DApplication::Render().
float Zoom
Referenced by CMyD3DApplication::FrameMove(), Line2D(), luaGetViewZoom(), luaSetViewZoom(), CMyD3DApplication::OneTimeSceneInit(), CMyD3DApplication::RestoreDeviceObjects(), and CMyD3DApplication::ViewSet().