RigidChips: readSub.hpp File Reference
readSub.hpp File Reference
#include <stdio.h>
Functions
int getCharData (FILE *fp)
int getStrData (FILE *fp, char *str)
int getStrData2 (FILE *fp, char *str)
void searchData (FILE *fp, int c)
int getToken (FILE *fp, char *str)
void resetToken ()
int getToken2 (FILE *fp, char *str)
int GetTokenCh (void)
Function Documentation
int getCharData (FILE * fp)
Referenced by getStrData(), and getStrData2().
int getStrData (FILE * fp, char * str)
int getStrData2 (FILE * fp, char * str)
int getToken (FILE * fp, char * str)
Referenced by readChildData(), and readData2().
int getToken2 (FILE * fp, char * str)
Referenced by readData2().
int GetTokenCh (void)
Referenced by readData2().
void resetToken ()
void searchData (FILE * fp, int c)
Referenced by readData2().