RigidChips: readdata.cpp File Reference
readdata.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <float.h>
#include "GVector.hpp"
#include "GRigid.hpp"
#include "readData.hpp"
#include "readSub.hpp"
#include "luaScript.hpp"
#include "luaSystem.hpp"
#include "GDPlay.hpp"
#include "GPlayers.h"
#include <crtdbg.h>
Macros
#define GDEFCD 1.0
Functions
void MakeChip (int type, int rn)
int getValNo (char *name)
int getValNo2 (char *name, bool *minusFlag)
void setOption (GRigid *rigid, GFloat value)
int readChildData (FILE *fp, int parentNo, int parentType, bool checkFlag)
int readData (char *name, bool checkFlag)
int readData2 (FILE *fp, bool checkFlag)
char * checkVal (GFloat *ref, char *tmp)
int saveChips (FILE *fp, GRigid *rigid, int level)
int saveData (char *fname)
Variables
int dataCode
GValList ValList []
GKeyList KeyList []
GWorld * World
GRigid * Chip []
int DataCheck
int ChipCount
int VarCount
char * ScriptSource
int ScriptType
int ScriptPc
GMYDATA MyPlayerData
lua_State * ScriptL =NULL
Macro Definition Documentation
#define GDEFCD 1.0
Referenced by MakeChip().
Function Documentation
char* checkVal (GFloat * ref, char * tmp)
Referenced by saveChips().
int getValNo (char * name)
Referenced by readChildData(), and readData2().
int getValNo2 (char * name, bool * minusFlag)
void MakeChip (int type, int rn)
Referenced by luaAddChip(), and readChildData().
int readChildData (FILE * fp, int parentNo, int parentType, bool checkFlag)
Referenced by readData2().
int readData (char * name, bool checkFlag)
Referenced by CMyD3DApplication::FrameMove(), CMyD3DApplication::LoadData(), luaUpdateChips(), and CMyD3DApplication::OneTimeSceneInit().
int readData2 (FILE * fp, bool checkFlag)
Referenced by CMyD3DApplication::LoadLog(), and readData().
int saveChips (FILE * fp, GRigid * rigid, int level)
Referenced by saveData().
int saveData (char * fname)
Referenced by luaSaveChips().
void setOption (GRigid * rigid, GFloat value)
Referenced by luaSetChip(), and readChildData().
Variable Documentation
GRigid* Chip[]
int ChipCount
Referenced by MakeChip(), readChildData(), readData2(), and saveData().
int DataCheck
Referenced by readData(), and readData2().
int dataCode
Referenced by CMyD3DApplication::RenderText().
GKeyList KeyList[]
GMYDATA MyPlayerData
lua_State* ScriptL =NULL
Referenced by CMyD3DApplication::FinalCleanup(), CMyD3DApplication::FrameMove(), CMyD3DApplication::InitChips(), CMyD3DApplication::OneTimeSceneInit(), readData(), readData2(), CMyD3DApplication::Render(), and CMyD3DApplication::ResetChips().
int ScriptPc
Referenced by factor(), getCh(), getSym(), getVariable(), labelRead(), RunScript(), ScriptError(), and statement().
char* ScriptSource
Referenced by readData2().
int ScriptType
Referenced by readData2().
GValList ValList[]
int VarCount
Referenced by checkVal(), getValNo(), getValNo2(), readChildData(), readData2(), and saveData().
GWorld* World